package com.gatecraft.grindweld;

import android.app.Activity;import android.app.Dialog;import android.content.DialogInterface;import android.content.pm.ActivityInfo;import android.os.Handler;import android.os.Looper;import android.view.View;import android.view.ViewGroup;import android.view.Window;import android.view.WindowManager;import android.webkit.JavascriptInterface;import android.webkit.WebChromeClient;import android.webkit.WebSettings;import android.webkit.WebView;import android.widget.Button;
import com.google.appinventor.components.annotations.DesignerComponent;import com.google.appinventor.components.annotations.SimpleEvent;import com.google.appinventor.components.annotations.SimpleFunction;import com.google.appinventor.components.annotations.SimpleObject;import com.google.appinventor.components.common.ComponentCategory;import com.google.appinventor.components.runtime.AndroidNonvisibleComponent;import com.google.appinventor.components.runtime.ComponentContainer;import com.google.appinventor.components.runtime.EventDispatcher;import com.google.appinventor.components.runtime.OnDestroyListener;import com.google.appinventor.components.runtime.OnPauseListener;import com.google.appinventor.components.runtime.OnResumeListener;

@DesignerComponent(version=7,description="GRIND & WELD: RUST & STEEL v2.7 offline lazy isometric Three.js ARPG with Diablo-style front menu, animated gate loading, four-act campaign, dungeons, contracts, elite world events, Rune Words, sockets, relic cores, richer itemization and Rust Rift endgame.",category=ComponentCategory.EXTENSION,nonVisible=true,iconName="")
@SimpleObject(external=true)
public class GateCraftGrindWeld extends AndroidNonvisibleComponent implements OnPauseListener,OnResumeListener,OnDestroyListener{
 private final Activity activity;private final Handler main=new Handler(Looper.getMainLooper());private Dialog dialog;private WebView web;private Button launchButton;private boolean hooked;private int calculationCount;private int language=2;private boolean testMode=true;private String saveData="";private int previousOrientation=ActivityInfo.SCREEN_ORIENTATION_UNSPECIFIED;private boolean orientationChanged;
 public GateCraftGrindWeld(ComponentContainer c){super(c.$form());activity=c.$context();c.$form().registerForOnPause(this);c.$form().registerForOnResume(this);c.$form().registerForOnDestroy(this);scheduleHook(0);}
 private boolean unlocked(){return calculationCount>=(testMode?1:50);}private void scheduleHook(final int a){long d=a==0?1200L:500L;main.postDelayed(new Runnable(){public void run(){if(hooked){syncButton();return;}if(hookButton())return;if(a<24)scheduleHook(a+1);}},d);}private boolean hookButton(){try{Button b=findButton(activity.findViewById(android.R.id.content));if(b==null)return false;launchButton=b;b.setOnClickListener(new View.OnClickListener(){public void onClick(View v){StartGame();}});hooked=true;syncButton();return true;}catch(Throwable x){return false;}}private Button findButton(View r){if(r==null)return null;if(r instanceof Button){CharSequence cs=((Button)r).getText();if(cs!=null){String s=cs.toString().toLowerCase();if(s.contains("grind & weld")||s.contains("rust & steel"))return(Button)r;}}if(r instanceof ViewGroup){ViewGroup g=(ViewGroup)r;for(int i=0;i<g.getChildCount();i++){Button b=findButton(g.getChildAt(i));if(b!=null)return b;}}return null;}private void syncButton(){if(launchButton!=null)launchButton.setVisibility(unlocked()?View.VISIBLE:View.GONE);}
 @SimpleFunction public void SetCalculationCount(int c){calculationCount=Math.max(0,c);main.post(new Runnable(){public void run(){syncButton();}});}@SimpleFunction public void SetLanguage(int l){language=Math.max(1,Math.min(12,l));}@SimpleFunction public void SetTestMode(boolean e){testMode=e;main.post(new Runnable(){public void run(){syncButton();}});}@SimpleFunction public void SetSaveData(String j){saveData=j==null?"":j;}@SimpleFunction public String LastSaveData(){return saveData;}@SimpleFunction public boolean IsUnlocked(){return unlocked();}@SimpleFunction public void StartGame(){if(!unlocked())return;main.post(new Runnable(){public void run(){openGame();}});}@SimpleFunction public void StopGame(){main.post(new Runnable(){public void run(){closeGame(false);}});}@SimpleFunction public String Version(){return"2.7.0";}
 private void enterLandscape(){try{previousOrientation=activity.getRequestedOrientation();if(previousOrientation!=ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE){orientationChanged=true;activity.setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE);}}catch(Throwable x){orientationChanged=false;}}private void restoreOrientation(){if(!orientationChanged)return;orientationChanged=false;try{activity.setRequestedOrientation(previousOrientation);}catch(Throwable x){}}
 private String payloadHtml()throws Exception{Class<?> p=Class.forName("com.gatecraft.grindweld.Payload",true,getClass().getClassLoader());java.lang.reflect.Method m=p.getDeclaredMethod("html");m.setAccessible(true);Object r=m.invoke(null);return r==null?"":String.valueOf(r);}
 private void openGame(){closeGame(false);try{enterLandscape();final WebView wv=new WebView(activity);web=wv;WebSettings s=wv.getSettings();s.setJavaScriptEnabled(true);s.setDomStorageEnabled(true);s.setAllowFileAccess(false);s.setAllowContentAccess(false);s.setMediaPlaybackRequiresUserGesture(true);s.setCacheMode(WebSettings.LOAD_NO_CACHE);wv.setWebChromeClient(new WebChromeClient());wv.setLayerType(View.LAYER_TYPE_HARDWARE,null);wv.setBackgroundColor(android.graphics.Color.BLACK);wv.addJavascriptInterface(new Bridge(),"GateCraftNative");dialog=new Dialog(activity,android.R.style.Theme_Black_NoTitleBar_Fullscreen);dialog.requestWindowFeature(Window.FEATURE_NO_TITLE);dialog.setCancelable(true);dialog.setContentView(wv);dialog.setOnDismissListener(new DialogInterface.OnDismissListener(){public void onDismiss(DialogInterface d){destroyWebView();restoreOrientation();}});Window win=dialog.getWindow();if(win!=null){win.setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN,WindowManager.LayoutParams.FLAG_FULLSCREEN);win.setLayout(WindowManager.LayoutParams.MATCH_PARENT,WindowManager.LayoutParams.MATCH_PARENT);}dialog.show();win=dialog.getWindow();if(win!=null){win.setLayout(WindowManager.LayoutParams.MATCH_PARENT,WindowManager.LayoutParams.MATCH_PARENT);View decor=win.getDecorView();if(decor!=null)decor.setSystemUiVisibility(View.SYSTEM_UI_FLAG_FULLSCREEN|View.SYSTEM_UI_FLAG_LOW_PROFILE);}wv.loadDataWithBaseURL("https://gatecraft.local/",payloadHtml(),"text/html","UTF-8",null);}catch(Throwable t){closeGame(false);GameError(String.valueOf(t.getMessage()));}}
 private void closeGame(boolean e){try{if(web!=null)web.evaluateJavascript("window.GW&&GW.shutdown&&GW.shutdown();",null);}catch(Throwable x){}try{if(dialog!=null&&dialog.isShowing())dialog.dismiss();}catch(Throwable x){}destroyWebView();dialog=null;restoreOrientation();if(e)ExitRequested();}private void destroyWebView(){final WebView wv=web;web=null;if(wv==null)return;try{wv.onPause();}catch(Throwable x){}try{wv.stopLoading();}catch(Throwable x){}try{wv.loadUrl("about:blank");}catch(Throwable x){}try{wv.clearHistory();}catch(Throwable x){}try{wv.clearCache(false);}catch(Throwable x){}try{wv.removeJavascriptInterface("GateCraftNative");}catch(Throwable x){}try{ViewGroup p=(ViewGroup)wv.getParent();if(p!=null)p.removeView(wv);}catch(Throwable x){}try{wv.destroy();}catch(Throwable x){}}
 private final class Bridge{@JavascriptInterface public int language(){return language;}@JavascriptInterface public String load(){return saveData==null?"":saveData;}@JavascriptInterface public void save(final String j){saveData=j==null?"":j;main.post(new Runnable(){public void run(){SaveChanged(saveData);}});}@JavascriptInterface public void exit(){main.post(new Runnable(){public void run(){closeGame(true);}});}@JavascriptInterface public void ready(){main.post(new Runnable(){public void run(){GameReady();}});}}
 @SimpleEvent public void SaveChanged(String j){EventDispatcher.dispatchEvent(this,"SaveChanged",j);}@SimpleEvent public void GameReady(){EventDispatcher.dispatchEvent(this,"GameReady");}@SimpleEvent public void ExitRequested(){EventDispatcher.dispatchEvent(this,"ExitRequested");}@SimpleEvent public void GameError(String m){EventDispatcher.dispatchEvent(this,"GameError",m);}@Override public void onPause(){if(web!=null)try{web.onPause();}catch(Throwable x){}}@Override public void onResume(){if(web!=null)try{web.onResume();}catch(Throwable x){}}@Override public void onDestroy(){closeGame(false);main.removeCallbacksAndMessages(null);}
}
