/* GRIND & WELD v2.1 campaign-map patch: one large overworld + Diablo-like sub-levels */
if(!Array.isArray(state.qprog))state.qprog=[0,0,0,0];while(state.qprog.length<4)state.qprog.push(0);state.quest=Math.max(0,Math.min(4,state.quest||0));if(state.campaignDone==null)state.campaignDone=false;
var CAMPAIGN={name:['Rozsda-medence','Rust Basin','Rostbecken','Cuenca de Oxido','Bassin de Rouille','锈蚀盆地','Bacino della Ruggine','Bacia da Ferrugem','Kotlina Rdzy','Roestbekken','Bazinul Ruginii','Ржавая котловина']};
var QUESTS=[
{name:['Elveszett szállítmány','Lost Shipment','Verlorene Lieferung','Cargamento Perdido','Cargaison Perdue','失落货运','Carico Perduto','Carga Perdida','Zaginiony Ładunek','Verloren Lading','Transport Pierdut','Потерянный груз'],desc:['Találd meg a 3 lezárt anyagkonténert a gyártelepen.','Find 3 sealed material caches across the factory grounds.','Finde 3 versiegelte Materiallager auf dem Fabrikgelände.','Encuentra 3 depósitos de material sellados.','Trouvez 3 caches de matériaux scellées.','找到3个封存物资箱。','Trova 3 depositi di materiale sigillati.','Encontre 3 depósitos de material lacrados.','Znajdź 3 zapieczętowane składy materiałów.','Vind 3 verzegelde materiaaldepots.','Găsește 3 depozite sigilate de materiale.','Найдите 3 запечатанных склада материалов.'],req:1},
{name:['Öntödei lezárás','Foundry Lockdown','Gießerei-Abriegelung','Bloqueo de Fundición','Confinement de Fonderie','铸造厂封锁','Blocco Fonderia','Bloqueio da Fundição','Blokada Odlewni','Gieterijvergrendeling','Blocajul Turnătoriei','Блокировка литейного цеха'],desc:['Menj le az öntöde alpályára, állíts le 3 vezérlőt és győzd le az őrt.','Enter the foundry sub-level, shut down 3 controls and defeat the Warden.','Betritt die Gießerei-Unterebene, schalte 3 Steuerungen ab und besiege den Wächter.','Entra al subnivel de fundición, apaga 3 controles y derrota al guardián.','Entrez dans le sous-niveau de fonderie, coupez 3 contrôles et battez le gardien.','进入铸造厂地下层，关闭3个控制器并击败守卫。','Entra nel sottolivello della fonderia, disattiva 3 controlli e sconfiggi il guardiano.','Entre no subnível da fundição, desligue 3 controles e derrote o guardião.','Wejdź do podpoziomu odlewni, wyłącz 3 sterowniki i pokonaj strażnika.','Ga de gieterij-sublaag in, schakel 3 besturingen uit en versla de bewaker.','Intră în subnivelul turnătoriei, oprește 3 controale și învinge gardianul.','Спуститесь в литейный подуровень, отключите 3 блока и победите Стража.'],req:2},
{name:['Kábelmélység','Cable Depths','Kabeltiefen','Profundidades de Cable','Profondeurs de Câbles','电缆深处','Profondità dei Cavi','Profundezas dos Cabos','Głębie Kablowe','Kabeldiepten','Adâncurile Cablurilor','Кабельные глубины'],desc:['Szerezd vissza a 4 rézmagot a kábelalagút alpályáról.','Recover 4 copper cores from the cable-tunnel sub-level.','Berge 4 Kupferkerne aus der Kabeltunnel-Unterebene.','Recupera 4 núcleos de cobre del subnivel de túneles.','Récupérez 4 noyaux de cuivre dans le sous-niveau des câbles.','从电缆隧道地下层找回4个铜芯。','Recupera 4 nuclei di rame dal sottolivello dei cavi.','Recupere 4 núcleos de cobre do subnível de cabos.','Odzyskaj 4 rdzenie miedziane z podpoziomu tuneli.','Haal 4 koperkernen uit de kabel-sublaag.','Recuperează 4 miezuri de cupru din subnivelul cablurilor.','Верните 4 медных сердечника из кабельного подуровня.'],req:4},
{name:['Apex protokoll','Apex Protocol','Apex-Protokoll','Protocolo Apex','Protocole Apex','Apex协议','Protocollo Apex','Protocolo Apex','Protokół Apex','Apex-protocol','Protocolul Apex','Протокол Apex'],desc:['Nyisd meg a reaktormagot, törd össze a 3 tápcellát és öld meg az Apex automatát.','Open the reactor core, break 3 power cells and destroy the Apex Automaton.','Öffne den Reaktorkern, zerstöre 3 Energiezellen und den Apex-Automaten.','Abre el núcleo, destruye 3 celdas y al Autómata Apex.','Ouvrez le cœur, détruisez 3 cellules et l’Automate Apex.','进入反应堆核心，摧毁3个电源单元和Apex自动机。','Apri il nucleo, distruggi 3 celle e l’Automa Apex.','Abra o núcleo, destrua 3 células e o Autômato Apex.','Otwórz rdzeń, zniszcz 3 ogniwa i Automat Apex.','Open de kern, vernietig 3 cellen en de Apex Automaat.','Deschide miezul, distruge 3 celule și Automatul Apex.','Откройте ядро, уничтожьте 3 энергоблока и автомат Apex.'],req:6}
];
var AREA_NAMES={surface:['Rozsda-medence','Rust Basin','Rostbecken','Cuenca de Oxido','Bassin de Rouille','锈蚀盆地','Bacino della Ruggine','Bacia da Ferrugem','Kotlina Rdzy','Roestbekken','Bazinul Ruginii','Ржавая котловина'],foundry:['Öntöde alsó szint','Foundry Lower Works','Gießerei-Unterwerk','Fundición Inferior','Fonderie Inférieure','铸造厂下层','Fonderia Inferiore','Fundição Inferior','Dolna Odlewnia','Onderste Gieterij','Turnătoria Inferioară','Нижняя литейная'],cable:['Kábelkatakombák','Cable Catacombs','Kabelkatakomben','Catacumbas de Cable','Catacombes de Câbles','电缆地下墓道','Catacombe dei Cavi','Catacumbas de Cabos','Katakumby Kablowe','Kabelcatacomben','Catacombele Cablurilor','Кабельные катакомбы'],reactor:['Apex reaktormag','Apex Reactor Core','Apex-Reaktorkern','Núcleo Reactor Apex','Cœur Réacteur Apex','Apex反应堆核心','Nucleo Reattore Apex','Núcleo do Reator Apex','Rdzeń Reaktora Apex','Apex Reactorkern','Miezul Reactorului Apex','Ядро реактора Apex']};
var areaKey='surface',areaBounds={minX:-48,maxX:48,minZ:-48,maxZ:48},areaEntry={x:-39,z:-37},questBeacons=[],bossSpawned=false;
function questStatus(i){if(i<state.quest)return '✓';if(i>state.quest)return T.locked;return '▶';}
function questProgressText(){if(state.quest>=4)return 'COMPLETE';var p=state.qprog[state.quest]||0;if(state.quest===0)return p+'/3';if(state.quest===1)return p<3?p+'/3 CONTROL':'WARDEN';if(state.quest===2)return p<4?p+'/4 CORE':'CAPTAIN';if(state.quest===3)return p<3?p+'/3 CELL':'APEX';return '';}
renderWorkshop=function(){
 $('classPage').classList.add('hidden');$('workshopPage').classList.remove('hidden');var ci=clsIndex();var eq=state.equipped>=0&&state.inventory[state.equipped]?itemName(state.inventory[state.equipped]):'-';
 $('profileBox').innerHTML='<b>'+l(CLASS_NAMES[ci])+'</b><br>'+T.level+' '+state.level+' · XP '+state.xp+'/'+xpNeed()+'<br>'+T.weapon+' +'+state.weapon+' · '+T.armor+' +'+state.armor+'<br><span class="eq">'+T.equipped+': '+eq+'</span>';
 $('resourceBox').innerHTML='<b>'+l(CAMPAIGN.name)+'</b><br><span class="gold">'+T.gold+': '+state.gold+'</span><br>'+T.steel+': '+state.steel+' · '+T.runes+': '+state.runes+'<br>Kills: '+state.kills+(state.campaignDone?'<br><span class="gold">CAMPAIGN COMPLETE</span>':'');
 var zr=$('zones');zr.innerHTML='';for(var i=0;i<QUESTS.length;i++){var q=QUESTS[i],active=i===state.quest,d=document.createElement('div');d.className='card zone'+(active?' sel':'');d.innerHTML='<strong>'+questStatus(i)+' '+l(q.name)+'</strong><p>'+l(q.desc)+'</p><p>LV '+q.req+(active?' · '+questProgressText():'')+'</p>';if(i>state.quest)d.style.opacity='.5';zr.appendChild(d);}
 var lr=$('loadout');lr.innerHTML='';if(!state.inventory.length)lr.innerHTML='<div class="tiny">-</div>';for(var j=0;j<state.inventory.length;j++){(function(j){var it=state.inventory[j],d=document.createElement('div');d.className='lootrow '+rarityNames[it.r];d.innerHTML='<b>'+itemName(it)+'</b>'+it.slot.toUpperCase()+' +'+it.power+(state.equipped===j?' · '+T.equipped:'');d.onclick=function(){state.equipped=j;save();renderWorkshop();};lr.appendChild(d);})(j);}
 $('startBtn').disabled=state.quest<QUESTS.length&&state.level<QUESTS[state.quest].req;
};
function setCampaignBounds(a,b,c,d){areaBounds={minX:a,maxX:b,minZ:c,maxZ:d};}
function campaignGround(){var sx=areaBounds.maxX-areaBounds.minX,sz=areaBounds.maxZ-areaBounds.minZ,tex=canvasTexture('floor');tex.repeat.set(Math.max(8,sx/5),Math.max(8,sz/5));var col=areaKey==='surface'?0x4e4b45:areaKey==='foundry'?0x403b38:areaKey==='cable'?0x343e43:0x43383a;var m=new THREE.MeshStandardMaterial({map:tex,color:col,roughness:.95,metalness:.08}),f=new THREE.Mesh(new THREE.PlaneGeometry(sx,sz),m);f.rotation.x=-Math.PI/2;f.position.set((areaBounds.minX+areaBounds.maxX)/2,0,(areaBounds.minZ+areaBounds.maxZ)/2);root.add(f);}
function campaignRoad(x,z,w,d,c){var o=box(w,.025,d,c||0x26292b,x,.018,z,.05);root.add(o);}
function campaignBoundary(){var cx=(areaBounds.minX+areaBounds.maxX)/2,cz=(areaBounds.minZ+areaBounds.maxZ)/2,w=areaBounds.maxX-areaBounds.minX,d=areaBounds.maxZ-areaBounds.minZ;addObstacle(cx,areaBounds.minZ+.25,w,.5,2.3,0x42484b,'wall');addObstacle(cx,areaBounds.maxZ-.25,w,.5,2.3,0x42484b,'wall');addObstacle(areaBounds.minX+.25,cz,.5,d,2.3,0x42484b,'wall');addObstacle(areaBounds.maxX-.25,cz,.5,d,2.3,0x42484b,'wall');}
function campaignBeacon(x,z,color,label){var g=new THREE.Group(),ring=new THREE.Mesh(new THREE.TorusGeometry(.8,.06,7,24),new THREE.MeshBasicMaterial({color:color,transparent:true,opacity:.88}));ring.rotation.x=Math.PI/2;ring.position.y=.12;g.add(ring);var beam=box(.11,3,.11,color,0,1.5,0,.05);beam.material=new THREE.MeshBasicMaterial({color:color,transparent:true,opacity:.38});g.add(beam);g.position.set(x,0,z);g.userData.label=label||'';root.add(g);questBeacons.push(g);return g;}
function portalUnlocked(t){return t==='foundry'?state.quest>=1:t==='cable'?state.quest>=2:t==='reactor'?state.quest>=3:true;}
function campaignPortal(x,z,target){var locked=!portalUnlocked(target),g=new THREE.Group();addTo(g,box(.35,2.7,.45,0x4a4f52,-1.1,1.35,0,.7));addTo(g,box(.35,2.7,.45,0x4a4f52,1.1,1.35,0,.7));addTo(g,box(2.55,.35,.5,0x6c4b32,0,2.6,0,.5));var core=box(1.55,1.7,.08,locked?0x5a2a28:0x2f6780,0,1.25,0,.25);core.material=new THREE.MeshBasicMaterial({color:locked?0x8c302a:0x3a9ac8,transparent:true,opacity:.33});g.add(core);g.position.set(x,0,z);root.add(g);interactables.push({type:'portal',g:g,x:x,z:z,target:target,used:false});campaignBeacon(x,z,locked?0xb04b3f:0x58b7df,l(AREA_NAMES[target]));}
function campaignReturn(x,z,targetX,targetZ){var g=new THREE.Group();addTo(g,box(2.2,.2,1.2,0x43515a,0,.1,0,.7));addTo(g,sphere(.22,0x70d6a0,0,.5,0,.1,10));g.position.set(x,0,z);root.add(g);interactables.push({type:'return',g:g,x:x,z:z,targetX:targetX,targetZ:targetZ,used:false});campaignBeacon(x,z,0x70d6a0,'RETURN');}
function questObject(type,x,z,color){var g=new THREE.Group();addTo(g,box(.95,.72,.72,0x343b3f,0,.36,0,.75));var core=sphere(.18,color,0,.85,0,.1,10);core.material=new THREE.MeshBasicMaterial({color:color});g.add(core);g.position.set(x,0,z);root.add(g);interactables.push({type:type,g:g,x:x,z:z,used:false});campaignBeacon(x,z,color,type);}
function spawnAmbient(count){var tries=0;for(var i=0;i<count&&tries<240;){tries++;var x=areaBounds.minX+4+Math.random()*(areaBounds.maxX-areaBounds.minX-8),z=areaBounds.minZ+4+Math.random()*(areaBounds.maxZ-areaBounds.minZ-8);if(collides(x,z,.7)||Math.hypot(x-areaEntry.x,z-areaEntry.z)<7)continue;var kind=areaKey==='surface'?(i%4===0?1:(i%5===0?2:0)):areaKey==='foundry'?(i%3===0?2:0):areaKey==='cable'?(i%3===0?3:2):(i%2?2:1);spawnEnemy(kind,false,x,z);i++;}}
function buildSurface(){areaKey='surface';zoneIndex=0;setCampaignBounds(-48,48,-48,48);scene.background.set(0x090b0c);scene.fog.color.copy(scene.background);campaignGround();campaignBoundary();campaignRoad(0,0,10,94);campaignRoad(0,0,94,10);campaignRoad(-28,-28,27,5,0x303235);campaignRoad(28,28,27,5,0x303235);
 addObstacle(-25,18,26,.7,2.2,0x4d4e4a,'wall');addObstacle(-14,30,.7,24,2.2,0x4d4e4a,'wall');addObstacle(24,-20,28,.7,2.2,0x4a4d4f,'wall');addObstacle(14,-31,.7,22,2.2,0x4a4d4f,'wall');
 for(var i=0;i<8;i++){crate(-37+i*3.6,-18+(i%2)*3,1.1);barrel(18+i*3,-38+(i%3)*2,i%2?0x6a3328:0x36525a);}for(i=0;i<6;i++){cableDrum(27+(i%2)*4,8+i*4.2);pallet(-8+i*3.4,34+(i%2)*2);}fence(-30,-4,14,0);fence(30,5,13,Math.PI/2);pipeRun(-39,9,13,true);pipeRun(40,-5,12,true);weldingTable(-34,32);weldingTable(-29,35);lamp(-40,-40,0xffa04c);lamp(-20,0,0xff9a48);lamp(0,20,0x6caee0);lamp(22,0,0xffa04c);lamp(37,34,0x72aee0);lamp(34,-35,0xff7842);chest(-42,8);chest(5,42);chest(42,-5);chest(7,-42);
 campaignPortal(-35,35,'foundry');campaignPortal(36,34,'cable');campaignPortal(35,-35,'reactor');var tr=new THREE.Group();addTo(tr,box(3.1,1.25,1.5,0x59666d,0,1.05,0,.65));addTo(tr,box(1.15,.8,1.4,0x85472f,-1.3,1.45,0,.45));tr.position.set(-41,0,-41);root.add(tr);interactables.push({type:'workshop',g:tr,x:-41,z:-41,used:false});campaignBeacon(-41,-41,0x63d38a,'WORKSHOP');
 if(state.quest===0){var cp=[[-31,-8],[8,32],[38,-4]],got=state.qprog[0]||0;for(i=got;i<3;i++)questObject('cache',cp[i][0],cp[i][1],0xe0ae3d);}areaEntry={x:-39,z:-37};spawnAmbient(18);}
function dungeonShell(w,d){setCampaignBounds(-w/2,w/2,-d/2,d/2);campaignGround();campaignBoundary();campaignRoad(0,0,w-2,d-2,0x292d30);}
function buildFoundry(){areaKey='foundry';zoneIndex=1;scene.background.set(0x0b0908);scene.fog.color.copy(scene.background);dungeonShell(56,52);areaEntry={x:0,z:-23};campaignReturn(0,-23,-33,32);addObstacle(-10,-5,.7,30,2.5,0x4d4a45,'wall');addObstacle(10,7,.7,30,2.5,0x4d4a45,'wall');addObstacle(0,10,16,.7,2.5,0x4d4a45,'wall');for(var z=-15;z<=15;z+=10){weldingTable(-18,z);weldingTable(18,z);barrel(-14,z+3,0x733426);barrel(14,z-3,0x733426);}for(var i=0;i<5;i++){lamp(-22+i*11,20,i%2?0xff7e3a:0xffb05b);crate(-20+i*10,-16+(i%2)*3,1.2);}chest(-23,20);chest(23,18);if(state.quest===1){var pts=[[-19,-5],[0,18],[20,-4]],p=state.qprog[1]||0;for(i=p;i<3;i++)questObject('control',pts[i][0],pts[i][1],0xff8b3d);if(p>=3&&!bossSpawned){spawnEnemy(4,true,0,20);enemies[enemies.length-1].userData.e.tag='warden';bossSpawned=true;}}spawnAmbient(12);}
function buildCable(){areaKey='cable';zoneIndex=2;scene.background.set(0x06090c);scene.fog.color.copy(scene.background);dungeonShell(62,48);areaEntry={x:-26,z:-18};campaignReturn(-26,-18,33,31);addObstacle(-12,0,.7,34,2.4,0x394348,'wall');addObstacle(2,-7,.7,29,2.4,0x394348,'wall');addObstacle(16,7,.7,28,2.4,0x394348,'wall');addObstacle(-5,14,13,.7,2.4,0x394348,'wall');for(var z=-17;z<=17;z+=6){pipeRun(-24,z,4,false);pipeRun(24,z,4,false);}for(var i=0;i<8;i++){cableDrum(-20+i*5.5,-12+(i%3)*8);barrel(-17+i*5,17-(i%2)*4,i%2?0x4b5960:0x663426);}lamp(-25,17,0x6da6d6);lamp(0,17,0xff8e42);lamp(25,17,0x6da6d6);chest(25,-18);if(state.quest===2){var pts=[[-20,8],[-3,-15],[12,14],[24,-5]],p=state.qprog[2]||0;for(i=p;i<4;i++)questObject('core',pts[i][0],pts[i][1],0xb977ff);if(p>=4&&!bossSpawned){spawnEnemy(3,true,22,15);enemies[enemies.length-1].userData.e.tag='captain';bossSpawned=true;}}spawnAmbient(14);}
function buildReactor(){areaKey='reactor';zoneIndex=3;scene.background.set(0x0a0708);scene.fog.color.copy(scene.background);dungeonShell(50,50);areaEntry={x:0,z:-21};campaignReturn(0,-21,32,-32);for(var a=0;a<8;a++){var ang=a*Math.PI/4,x=Math.cos(ang)*15,z=Math.sin(ang)*15;addObstacle(x,z,3.2,3.2,2.1,0x45464a,'wall');lamp(x*.8,z*.8,a%2?0xff6f45:0x67b9de);}addObstacle(0,0,8,8,1.1,0x3d4144,'wall');for(var i=0;i<6;i++)barrel(-18+i*7,-15+(i%2)*30,0x6a3128);chest(-20,20);chest(20,20);if(state.quest===3){var pts=[[-14,0],[14,0],[0,15]],p=state.qprog[3]||0;for(i=p;i<3;i++)questObject('cell',pts[i][0],pts[i][1],0xff4d3b);if(p>=3&&!bossSpawned){spawnEnemy(4,true,0,18);enemies[enemies.length-1].userData.e.tag='apex';bossSpawned=true;}}spawnAmbient(10);}
function buildArea(key,spawnX,spawnZ){clearWorld();matCache={};questBeacons=[];areaKey=key;bossSpawned=false;if(key==='surface')buildSurface();else if(key==='foundry')buildFoundry();else if(key==='cable')buildCable();else buildReactor();player=makeHumanoid(clsIndex(),false);player.position.set(spawnX!=null?spawnX:areaEntry.x,0,spawnZ!=null?spawnZ:areaEntry.z);root.add(player);playerParts=player.userData.parts;updateMission();}
collides=function(x,z,r){for(var i=0;i<obstacles.length;i++){var o=obstacles[i],dx=Math.max(Math.abs(x-o.x)-o.w/2,0),dz=Math.max(Math.abs(z-o.z)-o.d/2,0);if(dx*dx+dz*dz<r*r)return true;}return x<areaBounds.minX+r||x>areaBounds.maxX-r||z<areaBounds.minZ+r||z>areaBounds.maxZ-r;};
spawnWave=function(n){};waveDelay=0;
function completeQuest(index){if(state.quest!==index)return;var rewards=[[100,4,0,110],[150,5,1,170],[210,6,1,240],[350,8,2,420]][index];state.gold+=rewards[0];state.steel+=rewards[1];state.runes+=rewards[2];addXp(rewards[3]);state.quest=index+1;if(state.quest>=4){state.campaignDone=true;toast('RUST BASIN COMPLETE','legend');}else toast(l(QUESTS[index].name)+' ✓','legend');save();updateMission();}
enemyDeath=function(e){var d=e.userData.e||{},idx=enemies.indexOf(e);if(idx>=0)enemies.splice(idx,1);state.kills++;state.gold+=5+zoneIndex*3;state.steel+=Math.random()<.23?1:0;addXp(18+zoneIndex*8+(d.boss?120:0));spawnSparks(e.position,rarityColors[d.boss?3:1],d.boss?28:12);if(Math.random()<(d.boss?.95:.30))spawnLoot(e.position,d.boss?3:null);if(d.tag==='warden'&&state.quest===1&&state.qprog[1]>=3)completeQuest(1);if(d.tag==='captain'&&state.quest===2&&state.qprog[2]>=4)completeQuest(2);if(d.tag==='apex'&&state.quest===3&&state.qprog[3]>=3){completeQuest(3);openExtraction();}root.remove(e);disposeObject(e);save();};
openExtraction=function(){extraction=true;toast(T.ready,'legend');var g=new THREE.Group();addTo(g,box(3,1.2,1.5,0x59666d,0,1.05,0,.65));addTo(g,box(1.15,.8,1.4,0x85472f,-1.3,1.45,0,.45));g.position.set(0,0,-18);root.add(g);extractionObj=g;interactables.push({type:'extract',g:g,x:g.position.x,z:g.position.z,used:false});campaignBeacon(g.position.x,g.position.z,0x6fd077,'EXTRACT');updateMission();};
function enterArea(target,x,z){buildArea(target,x,z);toast(l(AREA_NAMES[target]),'magic');}
interact=function(){var q=nearestInteract();if(!q)return;if(q.type==='chest'){q.used=true;spawnSparks(q.g.position,0xe0ae3d,18);for(var i=0;i<2;i++){var p=q.g.position.clone();p.x+=(Math.random()-.5);p.z+=(Math.random()-.5);spawnLoot(p,i===1?2:null);}state.gold+=35;state.steel+=2;save();toast(T.pickup+': +35 '+T.gold,'legend');}
 else if(q.type==='portal'){if(!portalUnlocked(q.target)){toast(T.locked,'rare');return;}enterArea(q.target);}
 else if(q.type==='return')enterArea('surface',q.targetX,q.targetZ);
 else if(q.type==='workshop')finishMission(false);
 else if(q.type==='cache'&&state.quest===0){q.used=true;state.qprog[0]++;spawnSparks(q.g.position,0xe0ae3d,20);state.steel+=2;state.gold+=25;toast(T.pickup+': '+state.qprog[0]+'/3','legend');if(state.qprog[0]>=3)completeQuest(0);save();updateMission();}
 else if(q.type==='control'&&state.quest===1){q.used=true;state.qprog[1]++;spawnSparks(q.g.position,0xff8b3d,24);toast('CONTROL '+state.qprog[1]+'/3','rare');if(state.qprog[1]>=3&&!bossSpawned){spawnEnemy(4,true,0,20);enemies[enemies.length-1].userData.e.tag='warden';bossSpawned=true;toast(T.boss+': FOUNDRY WARDEN','legend');}save();updateMission();}
 else if(q.type==='core'&&state.quest===2){q.used=true;state.qprog[2]++;state.steel++;spawnSparks(q.g.position,0xb977ff,24);toast('COPPER CORE '+state.qprog[2]+'/4','magic');if(state.qprog[2]>=4&&!bossSpawned){spawnEnemy(3,true,22,15);enemies[enemies.length-1].userData.e.tag='captain';bossSpawned=true;toast(T.boss+': CABLE CAPTAIN','legend');}save();updateMission();}
 else if(q.type==='cell'&&state.quest===3){q.used=true;state.qprog[3]++;spawnSparks(q.g.position,0xff4d3b,30);toast('POWER CELL '+state.qprog[3]+'/3','rare');if(state.qprog[3]>=3&&!bossSpawned){spawnEnemy(4,true,0,18);enemies[enemies.length-1].userData.e.tag='apex';bossSpawned=true;toast(T.boss+': APEX WELDING AUTOMATON v4','legend');}save();updateMission();}
 else if(q.type==='extract')finishMission(true);};
finishMission=function(finalReward){if(finalReward){state.gold+=250;state.steel+=6;state.runes+=2;addXp(300);}mission=false;$('hud').classList.add('hidden');$('menu').classList.remove('hidden');clearWorld();matCache={};renderWorkshop();save();};
startMission=function(){init3D();mission=true;extraction=false;wave=0;waveDelay=0;bossSpawned=false;playerStats();hp=maxHp;en=maxEn;attackCd=s1Cd=s2Cd=dashCd=dashTime=hitInv=0;$('menu').classList.add('hidden');$('hud').classList.remove('hidden');$('drawer').classList.add('hidden');$('s1').querySelector('.label').textContent=l(skillNames[clsIndex()][0]);$('s2').querySelector('.label').textContent=l(skillNames[clsIndex()][1]);buildArea('surface');clock.getDelta();try{bridge&&bridge.ready();}catch(e){}loop();};
updateMission=function(){if(!mission)return;var title=state.quest<4?l(QUESTS[state.quest].name):l(CAMPAIGN.name);$('missionTitle').textContent=T.mission+': '+title+' · '+l(AREA_NAMES[areaKey]);$('missionText').textContent=state.quest>=4?(extraction?T.extract:'CAMPAIGN COMPLETE · '+T.extract):(l(QUESTS[state.quest].desc)+' · '+questProgressText());};
updateHud=function(){playerStats();$('heroName').textContent=l(CLASS_NAMES[clsIndex()]);$('heroSub').textContent=T.level+' '+state.level+' · '+T.gold+' '+state.gold+' · '+T.steel+' '+state.steel;$('hpBar').style.width=Math.max(0,hp/maxHp*100)+'%';$('enBar').style.width=Math.max(0,en/maxEn*100)+'%';$('xpBar').style.width=Math.max(0,state.xp/xpNeed()*100)+'%';updateMission();var nc=nearestInteract();$('interact').style.opacity=nc?'1':'.48';renderMini();for(var i=0;i<questBeacons.length;i++)questBeacons[i].rotation.y+=.03;};
renderMini=function(){var c=$('minimap'),x=c.getContext('2d'),w=c.width,h=c.height;x.fillStyle='#081014';x.fillRect(0,0,w,h);x.strokeStyle='#46545d';x.strokeRect(2,2,w-4,h-4);var sx=areaBounds.maxX-areaBounds.minX,sz=areaBounds.maxZ-areaBounds.minZ;function mx(v){return (v-areaBounds.minX)/sx*w;}function mz(v){return (v-areaBounds.minZ)/sz*h;}x.fillStyle='#38434a';for(var i=0;i<obstacles.length;i++){var o=obstacles[i];x.fillRect(mx(o.x-o.w/2),mz(o.z-o.d/2),Math.max(1,o.w/sx*w),Math.max(1,o.d/sz*h));}x.fillStyle='#d95b47';for(i=0;i<enemies.length;i++){x.beginPath();x.arc(mx(enemies[i].position.x),mz(enemies[i].position.z),enemies[i].userData.e&&enemies[i].userData.e.boss?5:2.4,0,Math.PI*2);x.fill();}x.fillStyle='#dcb84d';for(i=0;i<loot.length;i++)x.fillRect(mx(loot[i].position.x)-2,mz(loot[i].position.z)-2,4,4);x.fillStyle='#53d7df';for(i=0;i<interactables.length;i++){var q=interactables[i];if(q.used)continue;if(q.type==='portal'||q.type==='cache'||q.type==='control'||q.type==='core'||q.type==='cell'){x.beginPath();x.arc(mx(q.x),mz(q.z),4,0,Math.PI*2);x.fill();}}if(extractionObj){x.fillStyle='#6fd077';x.fillRect(mx(extractionObj.position.x)-5,mz(extractionObj.position.z)-5,10,10);}x.fillStyle='#61b6ee';x.beginPath();x.arc(mx(player.position.x),mz(player.position.z),5,0,Math.PI*2);x.fill();};