(function(){
'use strict';
var bridge=window.GateCraftNative||null;
var $=function(id){return document.getElementById(id);};
var lang=1;try{lang=Math.max(1,Math.min(12,bridge?bridge.language():2))-1;}catch(e){}
var T=[
{tag:'Sötét ipari izometrikus akció-RPG',choose:'Válassz szakágat',enter:'BELÉPÉS A MŰHELYBE',zone:'MEGBÍZÁSOK',loadout:'FELSZERELÉS / ZSÁKMÁNY',forge:'KOVÁCSOLÁS',heal:'JAVÍTÁS / GYÓGYÍTÁS',start:'KISZÁLLÁS',exit:'KILÉPÉS',inv:'TÁSKA',use:'HASZNÁL',attack:'TÁMADÁS',dash:'KITÉRÉS',workshop:'MŰHELY',steel:'Acél',runes:'Rúnák',gold:'Arany',level:'Szint',weapon:'Fegyver',armor:'Páncél',mission:'Megbízás',objective:'Tisztítsd meg a zónát',extract:'Kivonás: menj a teherautóhoz és nyomd a HASZNÁL gombot',locked:'ZÁROLVA',tip:'A 3D motor csak játék közben él; kilépéskor minden WebGL erőforrás felszabadul.',wave:'Hullám',boss:'FŐNÖK',pickup:'Felvetted',equipped:'Felszerelve',nores:'Nincs elég alapanyag',full:'A táska megtelt',ready:'Kivonási pont megnyílt',dead:'Kiütöttek – visszatérés a műhelybe'},
{tag:'Dark industrial isometric action RPG',choose:'Choose your specialist',enter:'ENTER WORKSHOP',zone:'CONTRACTS',loadout:'EQUIPMENT / LOOT',forge:'FORGE',heal:'REPAIR / HEAL',start:'DEPLOY',exit:'EXIT',inv:'INVENTORY',use:'USE',attack:'ATTACK',dash:'DODGE',workshop:'WORKSHOP',steel:'Steel',runes:'Runes',gold:'Gold',level:'Level',weapon:'Weapon',armor:'Armor',mission:'Contract',objective:'Clear the zone',extract:'Extraction: reach the truck and press USE',locked:'LOCKED',tip:'The 3D engine exists only while playing; all WebGL resources are released on exit.',wave:'Wave',boss:'BOSS',pickup:'Picked up',equipped:'Equipped',nores:'Not enough materials',full:'Inventory full',ready:'Extraction point opened',dead:'You were knocked out – returning to workshop'},
{tag:'Düsteres industrielles isometrisches Action-RPG',choose:'Wähle deine Klasse',enter:'WERKSTATT BETRETEN',zone:'AUFTRÄGE',loadout:'AUSRÜSTUNG / BEUTE',forge:'SCHMIEDEN',heal:'REPARIEREN / HEILEN',start:'EINSATZ',exit:'ENDE',inv:'INVENTAR',use:'BENUTZEN',attack:'ANGRIFF',dash:'AUSWEICHEN',workshop:'WERKSTATT',steel:'Stahl',runes:'Runen',gold:'Gold',level:'Stufe',weapon:'Waffe',armor:'Rüstung',mission:'Auftrag',objective:'Säubere die Zone',extract:'Evakuierung: zum LKW gehen und BENUTZEN drücken',locked:'GESPERRT',tip:'Die 3D-Engine läuft nur im Spiel und wird beim Beenden vollständig freigegeben.',wave:'Welle',boss:'BOSS',pickup:'Aufgenommen',equipped:'Ausgerüstet',nores:'Nicht genug Material',full:'Inventar voll',ready:'Evakuierung geöffnet',dead:'K. o. – Rückkehr zur Werkstatt'},
{tag:'RPG de acción isométrico industrial oscuro',choose:'Elige especialista',enter:'ENTRAR AL TALLER',zone:'CONTRATOS',loadout:'EQUIPO / BOTÍN',forge:'FORJAR',heal:'REPARAR / CURAR',start:'DESPLEGAR',exit:'SALIR',inv:'INVENTARIO',use:'USAR',attack:'ATACAR',dash:'ESQUIVAR',workshop:'TALLER',steel:'Acero',runes:'Runas',gold:'Oro',level:'Nivel',weapon:'Arma',armor:'Armadura',mission:'Contrato',objective:'Limpia la zona',extract:'Extracción: llega al camión y pulsa USAR',locked:'BLOQUEADO',tip:'El motor 3D solo vive durante la partida y libera WebGL al salir.',wave:'Oleada',boss:'JEFE',pickup:'Recogido',equipped:'Equipado',nores:'Faltan materiales',full:'Inventario lleno',ready:'Extracción abierta',dead:'Has caído – regreso al taller'},
{tag:'RPG d’action isométrique industriel sombre',choose:'Choisissez votre classe',enter:'ENTRER DANS L’ATELIER',zone:'CONTRATS',loadout:'ÉQUIPEMENT / BUTIN',forge:'FORGER',heal:'RÉPARER / SOIGNER',start:'DÉPLOYER',exit:'QUITTER',inv:'INVENTAIRE',use:'UTILISER',attack:'ATTAQUE',dash:'ESQUIVE',workshop:'ATELIER',steel:'Acier',runes:'Runes',gold:'Or',level:'Niveau',weapon:'Arme',armor:'Armure',mission:'Contrat',objective:'Nettoyez la zone',extract:'Extraction : rejoignez le camion et appuyez sur UTILISER',locked:'VERROUILLÉ',tip:'Le moteur 3D ne vit que pendant la partie et libère WebGL à la sortie.',wave:'Vague',boss:'BOSS',pickup:'Ramassé',equipped:'Équipé',nores:'Matériaux insuffisants',full:'Inventaire plein',ready:'Extraction ouverte',dead:'K.-O. – retour à l’atelier'},
{tag:'暗黑工业等距动作RPG',choose:'选择职业',enter:'进入工坊',zone:'任务',loadout:'装备 / 战利品',forge:'锻造',heal:'修理 / 治疗',start:'出发',exit:'退出',inv:'背包',use:'使用',attack:'攻击',dash:'闪避',workshop:'工坊',steel:'钢材',runes:'符文',gold:'金币',level:'等级',weapon:'武器',armor:'护甲',mission:'任务',objective:'清理区域',extract:'撤离：到达卡车并按“使用”',locked:'未解锁',tip:'3D引擎仅在游戏中运行，退出时释放全部WebGL资源。',wave:'波次',boss:'首领',pickup:'获得',equipped:'已装备',nores:'材料不足',full:'背包已满',ready:'撤离点已开启',dead:'你被击倒了——返回工坊'},
{tag:'GDR d’azione isometrico industriale oscuro',choose:'Scegli specialista',enter:'ENTRA IN OFFICINA',zone:'INCARICHI',loadout:'EQUIPAGGIAMENTO / LOOT',forge:'FORGIA',heal:'RIPARA / CURA',start:'PARTI',exit:'ESCI',inv:'INVENTARIO',use:'USA',attack:'ATTACCA',dash:'SCHIVA',workshop:'OFFICINA',steel:'Acciaio',runes:'Rune',gold:'Oro',level:'Livello',weapon:'Arma',armor:'Armatura',mission:'Incarico',objective:'Ripulisci la zona',extract:'Estrazione: raggiungi il camion e premi USA',locked:'BLOCCATO',tip:'Il motore 3D vive solo durante il gioco e libera WebGL all’uscita.',wave:'Ondata',boss:'BOSS',pickup:'Raccolto',equipped:'Equipaggiato',nores:'Materiali insufficienti',full:'Inventario pieno',ready:'Estrazione aperta',dead:'Sei stato abbattuto – ritorno in officina'},
{tag:'RPG de ação isométrico industrial sombrio',choose:'Escolha especialista',enter:'ENTRAR NA OFICINA',zone:'CONTRATOS',loadout:'EQUIPAMENTO / LOOT',forge:'FORJAR',heal:'REPARAR / CURAR',start:'PARTIR',exit:'SAIR',inv:'INVENTÁRIO',use:'USAR',attack:'ATACAR',dash:'ESQUIVAR',workshop:'OFICINA',steel:'Aço',runes:'Runas',gold:'Ouro',level:'Nível',weapon:'Arma',armor:'Armadura',mission:'Contrato',objective:'Limpe a zona',extract:'Extração: alcance o caminhão e pressione USAR',locked:'BLOQUEADO',tip:'O motor 3D só existe durante o jogo e libera o WebGL ao sair.',wave:'Onda',boss:'CHEFE',pickup:'Coletado',equipped:'Equipado',nores:'Materiais insuficientes',full:'Inventário cheio',ready:'Extração aberta',dead:'Você foi derrubado – retorno à oficina'},
{tag:'Mroczne industrialne izometryczne action RPG',choose:'Wybierz specjalistę',enter:'WEJDŹ DO WARSZTATU',zone:'ZLECENIA',loadout:'EKWIPUNEK / ŁUP',forge:'KUJ',heal:'NAPRAW / LECZ',start:'WYPRAWA',exit:'WYJDŹ',inv:'EKWIPUNEK',use:'UŻYJ',attack:'ATAK',dash:'UNIK',workshop:'WARSZTAT',steel:'Stal',runes:'Runy',gold:'Złoto',level:'Poziom',weapon:'Broń',armor:'Pancerz',mission:'Zlecenie',objective:'Oczyść strefę',extract:'Ewakuacja: dotrzyj do ciężarówki i naciśnij UŻYJ',locked:'ZABLOKOWANE',tip:'Silnik 3D działa tylko podczas gry i zwalnia WebGL po wyjściu.',wave:'Fala',boss:'BOSS',pickup:'Podniesiono',equipped:'Założono',nores:'Za mało materiałów',full:'Ekwipunek pełny',ready:'Ewakuacja otwarta',dead:'Powalono cię – powrót do warsztatu'},
{tag:'Donkere industriële isometrische actie-RPG',choose:'Kies specialist',enter:'WERKPLAATS IN',zone:'OPDRACHTEN',loadout:'UITRUSTING / LOOT',forge:'SMEDEN',heal:'REPAREREN / GENEZEN',start:'VERTREK',exit:'AFSLUITEN',inv:'INVENTARIS',use:'GEBRUIK',attack:'AANVAL',dash:'ONTWIJK',workshop:'WERKPLAATS',steel:'Staal',runes:'Runen',gold:'Goud',level:'Niveau',weapon:'Wapen',armor:'Pantser',mission:'Opdracht',objective:'Maak de zone vrij',extract:'Extractie: bereik de truck en druk GEBRUIK',locked:'VERGRENDELD',tip:'De 3D-engine draait alleen tijdens het spel en geeft WebGL vrij bij afsluiten.',wave:'Golf',boss:'BAAS',pickup:'Opgeraapt',equipped:'Uitgerust',nores:'Niet genoeg materiaal',full:'Inventaris vol',ready:'Extractie geopend',dead:'Uitgeschakeld – terug naar de werkplaats'},
{tag:'RPG de acțiune izometric industrial întunecat',choose:'Alege specialistul',enter:'INTRĂ ÎN ATELIER',zone:'CONTRACTE',loadout:'ECHIPAMENT / LOOT',forge:'FORJEAZĂ',heal:'REPARĂ / VINDECĂ',start:'PLECARE',exit:'IEȘIRE',inv:'INVENTAR',use:'FOLOSEȘTE',attack:'ATAC',dash:'ESCHIVĂ',workshop:'ATELIER',steel:'Oțel',runes:'Rune',gold:'Aur',level:'Nivel',weapon:'Armă',armor:'Armură',mission:'Contract',objective:'Curăță zona',extract:'Extracție: ajungi la camion și apasă FOLOSEȘTE',locked:'BLOCAT',tip:'Motorul 3D rulează doar în joc și eliberează WebGL la ieșire.',wave:'Val',boss:'BOSS',pickup:'Ridicat',equipped:'Echipat',nores:'Materiale insuficiente',full:'Inventar plin',ready:'Extracția s-a deschis',dead:'Ai fost doborât – întoarcere la atelier'},
{tag:'Тёмная индустриальная изометрическая action RPG',choose:'Выберите класс',enter:'ВОЙТИ В МАСТЕРСКУЮ',zone:'КОНТРАКТЫ',loadout:'СНАРЯЖЕНИЕ / ЛУТ',forge:'КОВКА',heal:'РЕМОНТ / ЛЕЧЕНИЕ',start:'ВЫЕЗД',exit:'ВЫХОД',inv:'ИНВЕНТАРЬ',use:'ИСПОЛЬЗОВАТЬ',attack:'АТАКА',dash:'УКЛОН',workshop:'МАСТЕРСКАЯ',steel:'Сталь',runes:'Руны',gold:'Золото',level:'Уровень',weapon:'Оружие',armor:'Броня',mission:'Контракт',objective:'Очистите зону',extract:'Эвакуация: доберитесь до грузовика и нажмите ИСПОЛЬЗОВАТЬ',locked:'ЗАКРЫТО',tip:'3D-движок работает только во время игры и освобождает WebGL при выходе.',wave:'Волна',boss:'БОСС',pickup:'Получено',equipped:'Экипировано',nores:'Недостаточно материалов',full:'Инвентарь полон',ready:'Точка эвакуации открыта',dead:'Вас вырубили – возвращение в мастерскую'}
][lang];

var CLASS_NAMES=[
['Nehéz-Lakatos','Heavy Metalworker','Schwerer Metallbauer','Metalúrgico Pesado','Métallier Lourd','重装金工','Fabbro Pesante','Serralheiro Pesado','Ciężki Ślusarz','Zware Metaalwerker','Lăcătuș Greu','Тяжёлый Слесарь'],
['Plazma-Vágó','Plasma Cutter','Plasma-Schneider','Cortador de Plasma','Découpeur Plasma','等离子切割手','Tagliatore Plasma','Cortador Plasma','Przecinacz Plazmowy','Plasmasnijder','Tăietor Plasma','Плазморезчик'],
['Automatizáló','Automation Tech','Automatisierer','Automatizador','Automaticien','自动化专家','Automatizzatore','Automatizador','Automatyk','Automatiseerder','Automatist','Автоматизатор']
];
var CLASS_DESC=[
['Tank · pöröly · szervo-pajzs','Tank · hammer · servo shield','Tank · Hammer · Servo-Schild','Tanque · martillo · escudo servo','Tank · marteau · bouclier servo','坦克 · 战锤 · 伺服盾','Tank · martello · scudo servo','Tanque · martelo · escudo servo','Tank · młot · tarcza servo','Tank · hamer · servoschild','Tank · ciocan · scut servo','Танк · молот · сервощит'],
['Távolsági DPS · plazma · ívfény','Ranged DPS · plasma · arc flash','Fernkampf · Plasma · Lichtbogen','DPS a distancia · plasma · arco','DPS distance · plasma · arc','远程输出 · 等离子 · 电弧','DPS distanza · plasma · arco','DPS à distância · plasma · arco','DPS dystans · plazma · łuk','Ranged DPS · plasma · boog','DPS distanță · plasmă · arc','Дальний бой · плазма · дуга'],
['Dron · löveg · területkontroll','Drone · turret · area control','Drohne · Geschütz · Kontrolle','Dron · torreta · control','Drone · tourelle · contrôle','无人机 · 炮塔 · 控场','Drone · torretta · controllo','Drone · torre · controle','Dron · wieżyczka · kontrola','Drone · turret · controle','Dronă · turelă · control','Дрон · турель · контроль']
];
var skillNames=[
[['Flex-Tornado','Flex Tornado','Flex-Tornado','Tornado Flex','Tornade Flex','砂轮旋风','Tornado Flex','Tornado Flex','Tornado Flex','Flex Tornado','Tornada Flex','Флекс-Торнадо'],['Pörölycsapás','Hammer Slam','Hammerschlag','Golpe de Martillo','Coup de Marteau','重锤震击','Colpo di Martello','Golpe de Martelo','Uderzenie Młotem','Hamerslag','Lovitură de Ciocan','Удар Молотом']],
[['Plazmasugár','Plasma Beam','Plasmastrahl','Rayo de Plasma','Rayon Plasma','等离子束','Raggio Plasma','Raio Plasma','Promień Plazmy','Plasmastraal','Rază Plasma','Плазменный Луч'],['Ívfény','Arc Flash','Lichtbogen','Destello de Arco','Flash d’Arc','电弧闪光','Lampo d’Arco','Flash de Arco','Błysk Łuku','Boogflits','Flash de Arc','Дуговая Вспышка']],
[['Hegesztő-Dron','Welding Drone','Schweißdrohne','Dron Soldador','Drone Soudeur','焊接无人机','Drone Saldatore','Drone Soldador','Dron Spawalniczy','Lasdrone','Dronă de Sudură','Сварочный Дрон'],['Fotocellás Löveg','Photocell Turret','Fotozellen-Geschütz','Torreta Fotocélula','Tourelle Photocellule','光电炮塔','Torretta Fotocellula','Torre Fotocélula','Wieżyczka Fotokomórki','Fotocel-turret','Turelă Fotocelulă','Фототурель']]
];
var classes=[
{id:'jug',hp:160,en:100,speed:5.1,damage:28,color:0xb45532},
{id:'plasma',hp:112,en:125,speed:5.7,damage:24,color:0x2f87c5},
{id:'tech',hp:125,en:120,speed:5.4,damage:21,color:0x7960b8}
];
function l(a){return a[lang]||a[1]||a[0];}

var state={cls:'jug',level:1,xp:0,gold:180,steel:8,runes:1,weapon:1,armor:1,zone:0,kills:0,inventory:[],equipped:-1};
try{var old=bridge&&bridge.load();if(old){var parsed=JSON.parse(old);for(var k in parsed)state[k]=parsed[k];}}catch(e){}
function save(){try{bridge&&bridge.save(JSON.stringify(state));}catch(e){}}
function clsIndex(){for(var i=0;i<classes.length;i++)if(classes[i].id===state.cls)return i;return 0;}
var selected=clsIndex();

var rarityNames=['common','magic','rare','legend'];
var rarityColors=[0xc7cbd0,0x3c8fea,0xaa4fe2,0xe0ae3d];
var prefixes=[
['Edzett','Hardened','Gehärtet','Templado','Trempé','淬硬','Temprato','Temperado','Hartowany','Gehard','Călit','Закалённый'],
['Túlhevített','Overheated','Überhitzt','Sobrecalentado','Surchauffé','过热','Surriscaldato','Superaquecido','Przegrzany','Oververhit','Supraîncălzit','Перегретый'],
['Precíziós','Precision','Präzisions','Precisión','Précision','精密','Precisione','Precisão','Precyzyjny','Precisie','Precizie','Точный'],
['Titán','Titanium','Titan','Titanio','Titane','钛合金','Titanio','Titânio','Tytanowy','Titanium','Titan','Титановый'],
['Mágneses','Magnetic','Magnetisch','Magnético','Magnétique','磁性','Magnetico','Magnético','Magnetyczny','Magnetisch','Magnetic','Магнитный']
];
var bases=[
['Flexkorong','Flex Disc','Trennscheibe','Disco Flex','Disque Flex','砂轮片','Disco Flex','Disco Flex','Tarcza Flex','Flexschijf','Disc Flex','Диск Болгарки'],
['Ipari Pöröly','Industrial Hammer','Industriehammer','Martillo Industrial','Marteau Industriel','工业战锤','Martello Industriale','Martelo Industrial','Młot Przemysłowy','Industriële Hamer','Ciocan Industrial','Промышленный Молот'],
['Hegesztőpajzs','Welding Shield','Schweißschild','Escudo de Soldadura','Bouclier de Soudage','焊接护盾','Scudo da Saldatura','Escudo de Solda','Tarcza Spawalnicza','Lasschild','Scut de Sudură','Сварочный Щит'],
['Plazmavágó','Plasma Cutter','Plasmaschneider','Cortador Plasma','Découpeur Plasma','等离子切割器','Tagliatore Plasma','Cortador Plasma','Przecinarka Plazmowa','Plasmasnijder','Tăietor Plasma','Плазморез'],
['Dronmag','Drone Core','Drohnenkern','Núcleo de Dron','Noyau de Drone','无人机核心','Nucleo Drone','Núcleo de Drone','Rdzeń Drona','Dronekern','Miez Dronă','Ядро Дрона'],
['Kábeltekercs','Cable Coil','Kabelspule','Bobina de Cable','Bobine de Câble','电缆卷','Bobina Cavo','Bobina de Cabo','Zwój Kabla','Kabelspoel','Bobină Cablu','Катушка Кабеля']
];
var suffixes=[
['a Gyorsaságnak','of Speed','der Geschwindigkeit','de Velocidad','de Vitesse','迅捷','della Velocità','da Velocidade','Szybkości','van Snelheid','al Vitezei','Скорости'],
['az Átütésnek','of Penetration','der Durchdringung','de Penetración','de Pénétration','穿透','della Penetrazione','da Penetração','Przebicia','van Penetratie','al Penetrării','Пробития'],
['a Szikrának','of Sparks','der Funken','de Chispas','des Étincelles','火花','delle Scintille','das Faíscas','Iskier','van Vonken','al Scânteilor','Искр'],
['a Pajzsnak','of Shielding','des Schildes','de Blindaje','du Bouclier','护盾','dello Scudo','do Escudo','Osłony','van Schild','al Scutului','Щита']
];
function rand(a){return a[(Math.random()*a.length)|0];}
function makeItem(tier){var r=Math.random(),ri=r<.035?3:r<.14?2:r<.42?1:0;var item={r:ri,p:(Math.random()*prefixes.length)|0,b:(Math.random()*bases.length)|0,s:(Math.random()*suffixes.length)|0,power:Math.max(1,tier+ri*2+((Math.random()*4)|0)),slot:Math.random()<.55?'weapon':'armor'};return item;}
function itemName(it){return l(prefixes[it.p])+' '+l(bases[it.b])+' '+l(suffixes[it.s]);}
function equippedBonus(type){if(state.equipped<0||!state.inventory[state.equipped])return 0;var it=state.inventory[state.equipped];return it.slot===type?it.power:0;}

$('tagline').textContent=T.tag;$('chooseTitle').textContent=T.choose;$('toWorkshop').textContent=T.enter;$('zoneTitle').textContent=T.zone;$('loadoutTitle').textContent=T.loadout;$('forgeBtn').textContent=T.forge;$('healBtn').textContent=T.heal;$('startBtn').textContent=T.start;$('exit').textContent=T.exit;$('inventoryBtn').textContent=T.inv;$('interact').querySelector('.label').textContent=T.use;$('atk').querySelector('.label').textContent=T.attack;$('dash').querySelector('.label').textContent=T.dash;$('workshopTip').textContent=T.tip;

function renderClasses(){var root=$('classCards');root.innerHTML='';for(var i=0;i<classes.length;i++){(function(i){var d=document.createElement('div');d.className='card'+(i===selected?' sel':'');d.innerHTML='<h3>'+l(CLASS_NAMES[i])+'</h3><p>'+l(CLASS_DESC[i])+'</p><p>'+l(skillNames[i][0])+' · '+l(skillNames[i][1])+'</p>';d.onclick=function(){selected=i;state.cls=classes[i].id;save();renderClasses();};root.appendChild(d);})(i);}}
renderClasses();
var ZONES=[
{name:['Elhagyott Műhely','Abandoned Workshop','Verlassene Werkstatt','Taller Abandonado','Atelier Abandonné','废弃工坊','Officina Abbandonata','Oficina Abandonada','Opuszczony Warsztat','Verlaten Werkplaats','Atelier Abandonat','Заброшенная Мастерская'],desc:['Tanuló zóna · kontárok · drónok','Starter zone · rivals · drones','Startzone · Pfuscher · Drohnen','Zona inicial · rivales · drones','Zone initiale · rivaux · drones','初始区域 · 对手 · 无人机','Zona iniziale · rivali · droni','Zona inicial · rivais · drones','Strefa startowa · rywale · drony','Startzone · rivalen · drones','Zonă de început · rivali · drone','Стартовая зона · соперники · дроны'],req:1},
{name:['Rozsdás Gyárudvar','Rust Factory Yard','Rostiger Fabrikhof','Patio de Fábrica Oxidado','Cour d’Usine Rouillée','锈蚀厂区','Cortile di Fabbrica Arrugginito','Pátio de Fábrica Enferrujado','Rdzawy Dziedziniec Fabryczny','Roestige Fabriekshof','Curte de Fabrică Ruginită','Ржавый Заводской Двор'],desc:['Nyílt terep · automaták · több loot','Open ground · automatons · more loot','Offenes Gelände · Automaten · mehr Beute','Terreno abierto · autómatas · más botín','Terrain ouvert · automates · plus de butin','开阔地 · 自动机 · 更多战利品','Area aperta · automi · più loot','Área aberta · autômatos · mais loot','Otwarty teren · automaty · więcej łupu','Open terrein · automaten · meer loot','Teren deschis · automate · mai mult loot','Открытая зона · автоматы · больше лута'],req:2},
{name:['Kábelalagút','Cable Service Tunnel','Kabeltunnel','Túnel de Cables','Tunnel de Câbles','电缆隧道','Tunnel Cavi','Túnel de Cabos','Tunel Kablowy','Kabeltunnel','Tunel de Cabluri','Кабельный Тоннель'],desc:['Szűk folyosók · tolvajok · Rozsda Gólem','Tight corridors · thieves · Rust Golem','Enge Gänge · Diebe · Rostgolem','Pasillos estrechos · ladrones · Gólem de Óxido','Couloirs étroits · voleurs · Golem de Rouille','狭窄通道 · 窃贼 · 锈蚀魔像','Corridoi stretti · ladri · Golem di Ruggine','Corredores estreitos · ladrões · Golem de Ferrugem','Wąskie korytarze · złodzieje · Rdzawy Golem','Smalle gangen · dieven · Roestgolem','Coridoare înguste · hoți · Golem de Rugină','Узкие коридоры · воры · Ржавый Голем'],req:4}
];
function renderWorkshop(){
 $('classPage').classList.add('hidden');$('workshopPage').classList.remove('hidden');
 var ci=clsIndex();var eq=state.equipped>=0&&state.inventory[state.equipped]?itemName(state.inventory[state.equipped]):'-';
 $('profileBox').innerHTML='<b>'+l(CLASS_NAMES[ci])+'</b><br>'+T.level+' '+state.level+' · XP '+state.xp+'/'+xpNeed()+'<br>'+T.weapon+' +'+state.weapon+' · '+T.armor+' +'+state.armor+'<br><span class="eq">'+T.equipped+': '+eq+'</span>';
 $('resourceBox').innerHTML='<span class="gold">'+T.gold+': '+state.gold+'</span><br>'+T.steel+': '+state.steel+' · '+T.runes+': '+state.runes+'<br>Kills: '+state.kills;
 var zr=$('zones');zr.innerHTML='';for(var i=0;i<ZONES.length;i++){(function(i){var z=ZONES[i],ok=state.level>=z.req,d=document.createElement('div');d.className='card zone'+(state.zone===i?' sel':'');d.innerHTML='<strong>'+l(z.name)+'</strong><p>'+l(z.desc)+'</p><p>'+(ok?'LV '+z.req:T.locked+' · LV '+z.req)+'</p>';if(ok)d.onclick=function(){state.zone=i;save();renderWorkshop();};zr.appendChild(d);})(i);}
 var lr=$('loadout');lr.innerHTML='';if(!state.inventory.length)lr.innerHTML='<div class="tiny">—</div>';for(var j=0;j<state.inventory.length;j++){(function(j){var it=state.inventory[j],d=document.createElement('div');d.className='lootrow '+rarityNames[it.r];d.innerHTML='<b>'+itemName(it)+'</b>'+it.slot.toUpperCase()+' +'+it.power+(state.equipped===j?' · '+T.equipped:'');d.onclick=function(){state.equipped=j;save();renderWorkshop();};lr.appendChild(d);})(j);}
}
$('toWorkshop').onclick=function(){renderWorkshop();};
$('forgeBtn').onclick=function(){if(state.steel>=4&&state.gold>=70){state.steel-=4;state.gold-=70;state.weapon++;if(state.runes>0&&state.weapon%3===0){state.runes--;state.armor++;}save();renderWorkshop();toast(T.forge+' +'+state.weapon,'legend');}else toast(T.nores,'rare');};
$('healBtn').onclick=function(){state.gold=Math.max(0,state.gold-20);save();renderWorkshop();};
$('startBtn').onclick=function(){startMission(state.zone);};
$('exit').onclick=function(){shutdown();try{bridge&&bridge.exit();}catch(e){}};
$('inventoryBtn').onclick=function(){$('drawer').classList.toggle('hidden');renderDrawer();};
function renderDrawer(){var d=$('drawer');d.innerHTML='<b>'+T.inv+'</b>';for(var i=0;i<state.inventory.length;i++){var it=state.inventory[i],s=document.createElement('div');s.className='slot '+rarityNames[it.r];s.innerHTML='<b>'+itemName(it)+'</b>'+it.slot.toUpperCase()+' +'+it.power+(state.equipped===i?' · '+T.equipped:'');d.appendChild(s);}}
function xpNeed(){return 220+state.level*110;}
function addXp(n){state.xp+=n;while(state.xp>=xpNeed()){state.xp-=xpNeed();state.level++;state.gold+=80;state.steel+=2;toast('LEVEL '+state.level,'legend');}save();}
function toast(msg,rar){var d=$('lootToast');d.className=rar||'common';d.textContent=msg;d.style.opacity='1';clearTimeout(toast.t);toast.t=setTimeout(function(){d.style.opacity='0';},1800);}

var renderer=null,scene=null,camera=null,clock=null,root=null,player=null,playerParts=null;
var enemies=[],loot=[],particles=[],projectiles=[],summons=[],interactables=[],obstacles=[],lights=[];
var mission=false,zoneIndex=0,wave=0,waveDelay=0,extraction=false,extractionObj=null,time=0,uiClock=0,fpsClock=0,fpsFrames=0,quality=2;
var hp=100,maxHp=100,en=100,maxEn=100,attackCd=0,s1Cd=0,s2Cd=0,dashCd=0,dashTime=0,hitInv=0,attackAnim=0,moveMag=0;
var joy={x:0,y:0,id:-1},keys={};
var tempV=new THREE.Vector3(),tempV2=new THREE.Vector3();
var matCache={};
function mat(color,metal,rough,em){var key=color+'_'+metal+'_'+rough+'_'+em;if(matCache[key])return matCache[key];var m=new THREE.MeshStandardMaterial({color:color,metalness:metal||0,roughness:rough==null?.75:rough,emissive:em||0,flatShading:true});matCache[key]=m;return m;}
function mesh(g,m,x,y,z){var o=new THREE.Mesh(g,m);o.position.set(x||0,y||0,z||0);o.castShadow=false;o.receiveShadow=false;return o;}
function box(w,h,d,c,x,y,z,metal){return mesh(new THREE.BoxGeometry(w,h,d),mat(c,metal||0,.78),x,y,z);}
function cyl(r1,r2,h,c,x,y,z,metal,seg){return mesh(new THREE.CylinderGeometry(r1,r2,h,seg||8),mat(c,metal||0,.72),x,y,z);}
function sphere(r,c,x,y,z,metal,seg){return mesh(new THREE.SphereGeometry(r,seg||10,seg||8),mat(c,metal||0,.75),x,y,z);}
function addTo(g,o){g.add(o);return o;}
function fakeShadow(g,scale){var geo=new THREE.CircleGeometry(scale||.65,18),mm=new THREE.MeshBasicMaterial({color:0x000000,transparent:true,opacity:.32,depthWrite:false});var s=new THREE.Mesh(geo,mm);s.rotation.x=-Math.PI/2;s.position.y=.012;g.add(s);return s;}
function canvasTexture(kind){var c=document.createElement('canvas');c.width=c.height=256;var x=c.getContext('2d'),i;if(kind==='floor'){x.fillStyle='#343638';x.fillRect(0,0,256,256);for(i=0;i<900;i++){var v=(38+Math.random()*30)|0;x.fillStyle='rgb('+v+','+v+','+(v+2)+')';x.fillRect(Math.random()*256,Math.random()*256,1+Math.random()*3,1+Math.random()*3);}x.strokeStyle='#1d1f21';x.lineWidth=3;for(i=0;i<=256;i+=64){x.beginPath();x.moveTo(i,0);x.lineTo(i,256);x.stroke();x.beginPath();x.moveTo(0,i);x.lineTo(256,i);x.stroke();}x.strokeStyle='#77776a';x.lineWidth=1;for(i=0;i<12;i++){var sx=Math.random()*256,sy=Math.random()*256;x.beginPath();x.moveTo(sx,sy);for(var j=0;j<4;j++){sx+=(Math.random()-.5)*28;sy+=(Math.random()-.5)*28;x.lineTo(sx,sy);}x.stroke();}}
 else{x.fillStyle='#563a25';x.fillRect(0,0,256,256);x.strokeStyle='#2b1c12';x.lineWidth=5;for(i=0;i<256;i+=42){x.strokeRect(i,0,38,256);}}
 var t=new THREE.CanvasTexture(c);t.wrapS=t.wrapT=THREE.RepeatWrapping;t.repeat.set(8,8);t.colorSpace=THREE.SRGBColorSpace;return t;}
function init3D(){if(renderer)return;renderer=new THREE.WebGLRenderer({canvas:$('c'),antialias:true,alpha:false,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(window.devicePixelRatio||1,1.4));renderer.setSize(innerWidth,innerHeight,false);renderer.outputColorSpace=THREE.SRGBColorSpace;scene=new THREE.Scene();scene.background=new THREE.Color(0x07090b);scene.fog=new THREE.Fog(0x080a0c,25,48);clock=new THREE.Clock();root=new THREE.Group();scene.add(root);var aspect=innerWidth/innerHeight,view=11.3;camera=new THREE.OrthographicCamera(-view*aspect,view*aspect,view,-view,.1,90);camera.position.set(14,17,14);camera.lookAt(0,0,0);scene.add(new THREE.HemisphereLight(0x98b0b8,0x20140d,1.05));var d=new THREE.DirectionalLight(0xffd1a0,1.25);d.position.set(8,16,6);scene.add(d);var cold=new THREE.DirectionalLight(0x5f91b8,.45);cold.position.set(-8,9,-5);scene.add(cold);window.addEventListener('resize',resize);}
function resize(){if(!renderer)return;var a=innerWidth/innerHeight,v=11.3;camera.left=-v*a;camera.right=v*a;camera.top=v;camera.bottom=-v;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight,false);}
function disposeObject(o){if(!o)return;o.traverse(function(n){if(n.geometry)try{n.geometry.dispose();}catch(e){}if(n.material){var a=Array.isArray(n.material)?n.material:[n.material];for(var i=0;i<a.length;i++)try{a[i].dispose();}catch(e){}}});}
function clearWorld(){if(!root)return;while(root.children.length){var o=root.children.pop();disposeObject(o);}if(scene){for(var li=0;li<lights.length;li++)try{scene.remove(lights[li]);}catch(e){}}enemies.length=loot.length=particles.length=projectiles.length=summons.length=interactables.length=obstacles.length=0;lights.length=0;extractionObj=null;}

function makeHumanoid(kind,enemy){var g=new THREE.Group();fakeShadow(g,enemy?.62:.68);var skin=enemy?0xb98663:0xc9966b,cloth=enemy?0x793d30:classes[clsIndex()].color,dark=0x272b2e,steel=0x7d898e;var torso=box(.72,.9,.42,cloth,0,1.25,0,.18);g.add(torso);var head=sphere(.29,skin,0,1.98,0,0,10);g.add(head);var helmet=cyl(.32,.37,.16,enemy?0x5c2b25:0xc68d2d,0,2.22,0,.25,10);g.add(helmet);var lArm=new THREE.Group(),rArm=new THREE.Group(),lLeg=new THREE.Group(),rLeg=new THREE.Group();lArm.position.set(-.48,1.54,0);rArm.position.set(.48,1.54,0);lLeg.position.set(-.2,.8,0);rLeg.position.set(.2,.8,0);g.add(lArm);g.add(rArm);g.add(lLeg);g.add(rLeg);addTo(lArm,box(.22,.72,.22,cloth,0,-.31,0,.1));addTo(rArm,box(.22,.72,.22,cloth,0,-.31,0,.1));addTo(lLeg,box(.27,.82,.3,dark,0,-.39,0,.05));addTo(rLeg,box(.27,.82,.3,dark,0,-.39,0,.05));addTo(lLeg,box(.31,.18,.46,0x16191b,0,-.83,.1,.1));addTo(rLeg,box(.31,.18,.46,0x16191b,0,-.83,.1,.1));var weapon=new THREE.Group();weapon.position.set(.0,-.48,.08);rArm.add(weapon);
 if(kind===0){addTo(weapon,cyl(.07,.07,1.15,0x4a3425,0,-.46,0,.1,7));var h=box(.62,.24,.26,steel,0,-1.02,0,.65);weapon.add(h);}
 else if(kind===1){var gun=box(.25,.24,.95,0x59666e,0,-.62,-.3,.8);weapon.add(gun);addTo(weapon,cyl(.13,.09,.36,0x2799d1,0,-.62,-.82,.6,8));gun.rotation.x=Math.PI/2;}
 else{addTo(weapon,box(.48,.2,.38,0x475b66,0,-.72,-.1,.7));addTo(weapon,sphere(.13,0x7d58bb,.16,-.72,-.25,.2,8));}
 g.userData.parts={torso:torso,head:head,lArm:lArm,rArm:rArm,lLeg:lLeg,rLeg:rLeg,weapon:weapon};return g;}
function makeDrone(){var g=new THREE.Group();fakeShadow(g,.58);addTo(g,cyl(.48,.58,.32,0x6c7477,0,1.15,0,.75,10));addTo(g,sphere(.26,0xa53b27,0,1.28,0,.4,8));for(var i=0;i<4;i++){var a=i*Math.PI/2,arm=box(.7,.1,.12,0x4f5557,Math.cos(a)*.55,1.2,Math.sin(a)*.55,.7);arm.rotation.y=-a;g.add(arm);addTo(g,cyl(.18,.18,.1,0x2b2e30,Math.cos(a)*.9,1.18,Math.sin(a)*.9,.6,8));}return g;}
function makeBot(){var g=new THREE.Group();fakeShadow(g,.7);addTo(g,box(.9,.9,.72,0x586269,0,.78,0,.8));addTo(g,box(.62,.33,.55,0x9b4b2c,0,1.45,0,.5));addTo(g,sphere(.09,0xff9e32,-.18,1.48,.3,.1,8));addTo(g,sphere(.09,0xff9e32,.18,1.48,.3,.1,8));addTo(g,cyl(.11,.11,.95,0x363d41,-.5,.5,0,.7,8));addTo(g,cyl(.11,.11,.95,0x363d41,.5,.5,0,.7,8));return g;}
function makeGolem(){var g=new THREE.Group();fakeShadow(g,1.05);addTo(g,box(1.3,1.45,.95,0x5f5650,0,1.35,0,.8));addTo(g,box(.82,.7,.72,0x7d6b58,0,2.35,0,.75));addTo(g,sphere(.12,0xff4e2d,-.22,2.45,.38,.1,8));addTo(g,sphere(.12,0xff4e2d,.22,2.45,.38,.1,8));for(var s=-1;s<=1;s+=2){addTo(g,cyl(.24,.3,1.55,0x514b48,s*.9,1.2,0,.8,8));addTo(g,box(.45,.5,.55,0x6a5d52,s*.9,.28,.1,.8));}return g;}
function makeEnemy(kind,boss){var g;if(kind===1)g=makeDrone();else if(kind===2)g=makeBot();else if(kind===4)g=makeGolem();else g=makeHumanoid(kind===3?2:0,true);if(boss)g.scale.setScalar(1.28);var max=boss?300+zoneIndex*90:55+zoneIndex*25+wave*12;g.userData.e={kind:kind,boss:boss,hp:max,max:max,speed:boss?1.65:(2.0+Math.random()*.65),damage:boss?20:8+zoneIndex*3,cd:Math.random(),stun:0,flash:0,anim:Math.random()*6};return g;}
function animateHumanoid(g,dt,moving,attacking){var p=g.userData.parts;if(!p)return;var a=g.userData.anim=(g.userData.anim||0)+dt*(moving?8:2);var swing=moving?Math.sin(a)*.65:Math.sin(a)*.06;p.lLeg.rotation.x=swing;p.rLeg.rotation.x=-swing;p.lArm.rotation.x=-swing*.75;p.rArm.rotation.x=swing*.65-(attacking?1.25:0);p.torso.position.y=1.25+(moving?Math.abs(Math.sin(a))*0.035:Math.sin(a)*.015);}

function floorMaterial(){var tex=canvasTexture('floor');tex.repeat.set(zoneIndex===2?12:9,zoneIndex===2?12:9);return new THREE.MeshStandardMaterial({map:tex,color:zoneIndex===1?0x55514b:zoneIndex===2?0x3b4245:0x4a4a45,roughness:.95,metalness:.08});}
function addObstacle(x,z,w,d,h,color,type){var g=new THREE.Group(),o;if(type==='wall'){o=box(w,h,d,color,0,h/2,0,.35);g.add(o);for(var i=-w/2+.3;i<w/2;i+=.8)addTo(g,box(.06,h+.12,d+.05,0x292e30,i,h/2,0,.7));}
 else{o=box(w,h,d,color,0,h/2,0,.45);g.add(o);}g.position.set(x,0,z);root.add(g);obstacles.push({x:x,z:z,w:w,d:d});return g;}
function crate(x,z,s){var g=new THREE.Group(),c=box(s,.8*s,s,0x6f4a2c,0,.4*s,0,.15);g.add(c);for(var i=-1;i<=1;i+=2){addTo(g,box(.08*s,.84*s,s+.03,0x30231a,i*.32*s,.42*s,0,.1));addTo(g,box(s+.03,.08*s,.08*s,0x30231a,0,.42*s,i*.32*s,.1));}g.position.set(x,0,z);root.add(g);obstacles.push({x:x,z:z,w:s,d:s});return g;}
function barrel(x,z,c){var g=new THREE.Group();addTo(g,cyl(.38,.38,.9,c||0x6f3326,0,.45,0,.65,12));addTo(g,cyl(.4,.4,.05,0x24282a,0,.2,0,.8,12));addTo(g,cyl(.4,.4,.05,0x24282a,0,.7,0,.8,12));g.position.set(x,0,z);root.add(g);obstacles.push({x:x,z:z,w:.75,d:.75});return g;}
function cableDrum(x,z){var g=new THREE.Group();var ax=cyl(.12,.12,1.05,0x34383b,0,.65,0,.8,8);ax.rotation.z=Math.PI/2;g.add(ax);for(var s=-1;s<=1;s+=2){var d=cyl(.62,.62,.12,0x765037,s*.5,.65,0,.15,12);d.rotation.z=Math.PI/2;g.add(d);}for(var r=.25;r<.55;r+=.1){var ring=new THREE.Mesh(new THREE.TorusGeometry(r,.035,6,18),mat(0x17191a,.4,.75));ring.rotation.y=Math.PI/2;g.add(ring);}g.position.set(x,0,z);root.add(g);obstacles.push({x:x,z:z,w:1.25,d:1.25});}
function pallet(x,z){var g=new THREE.Group();for(var i=-2;i<=2;i++){addTo(g,box(.22,.08,1.4,0x725033,i*.28,.08,0,.1));}addTo(g,box(1.4,.1,.18,0x4b3423,0,.16,-.42,.1));addTo(g,box(1.4,.1,.18,0x4b3423,0,.16,.42,.1));g.position.set(x,0,z);root.add(g);}
function lamp(x,z,c){var g=new THREE.Group();addTo(g,cyl(.08,.1,3.2,0x444b4f,0,1.6,0,.75,8));addTo(g,box(.65,.18,.35,0x42484c,0,3.12,0,.75));var bulb=addTo(g,box(.42,.05,.22,c||0xffb05b,0,3.01,.08,.1));bulb.material=new THREE.MeshBasicMaterial({color:c||0xffb05b});g.position.set(x,0,z);root.add(g);var pl=new THREE.PointLight(c||0xffa34e,1.0,7);pl.position.set(x,2.7,z);scene.add(pl);lights.push(pl);}
function fence(x,z,w,rot){var g=new THREE.Group();for(var i=-w/2;i<=w/2;i+=.45)addTo(g,box(.035,1.45,.035,0x596267,i,.75,0,.8));for(var y=.25;y<=1.3;y+=.35)addTo(g,box(w,.035,.035,0x596267,0,y,0,.8));g.position.set(x,0,z);g.rotation.y=rot||0;root.add(g);var ww=Math.abs(Math.cos(rot||0))*w+.2,dd=Math.abs(Math.sin(rot||0))*w+.2;obstacles.push({x:x,z:z,w:Math.max(.2,ww),d:Math.max(.2,dd)});}
function pipeRun(x,z,len,vertical){var g=new THREE.Group();for(var k=0;k<2;k++){var p=cyl(.11,.11,len,0x6b3c28,k*.34,1.55,0,.65,8);p.rotation[vertical?'x':'z']=Math.PI/2;g.add(p);}g.position.set(x,0,z);root.add(g);}
function weldingTable(x,z){var g=new THREE.Group();addTo(g,box(1.8,.12,.9,0x4b5256,0,1.05,0,.85));for(var sx=-1;sx<=1;sx+=2)for(var sz=-1;sz<=1;sz+=2)addTo(g,box(.1,1,.1,0x303539,sx*.75,.5,sz*.34,.8));addTo(g,box(.65,.42,.55,0x334d5b,.38,1.32,0,.55));g.position.set(x,0,z);root.add(g);obstacles.push({x:x,z:z,w:1.9,d:1.0});}
function chest(x,z){var g=new THREE.Group();addTo(g,box(1,.5,.72,0x644326,0,.25,0,.15));addTo(g,box(1.04,.1,.76,0x242a2c,0,.53,0,.7));addTo(g,box(.14,.22,.05,0xd0a33a,0,.38,.39,.7));g.position.set(x,0,z);root.add(g);interactables.push({type:'chest',g:g,x:x,z:z,used:false});}
function buildZone(z){clearWorld();zoneIndex=z;scene.background.set(z===1?0x0a0908:z===2?0x06090b:0x07090b);scene.fog.color.copy(scene.background);var floor=new THREE.Mesh(new THREE.PlaneGeometry(42,42),floorMaterial());floor.rotation.x=-Math.PI/2;floor.position.y=0;root.add(floor);
 addObstacle(0,-20,40,.65,2.4,0x4b4f50,'wall');addObstacle(-20,0,.65,40,2.4,0x454a4b,'wall');addObstacle(20,0,.65,40,2.4,0x454a4b,'wall');
 if(z===0){addObstacle(0,6,8,.65,2.0,0x5a5c59,'wall');addObstacle(-8,-2,5,.6,1.8,0x555954,'wall');weldingTable(-5,5);weldingTable(7,7);for(var i=0;i<7;i++)crate(-12+i*3.1,-9+(i%2)*2,1.1);barrel(10,-4);barrel(11,-4.5,0x344d55);cableDrum(12,8);pallet(-12,8);fence(9,1,5,Math.PI/2);pipeRun(-15,3,6,true);lamp(-8,10,0xff9f55);lamp(10,10,0x6da6d6);chest(-14,12);chest(14,-12);}
 else if(z===1){for(var i=0;i<5;i++){crate(-13+i*6,-8+(i%2)*4,1.2);barrel(-10+i*5,9-(i%3)*2,i%2?0x6f3326:0x345360);}cableDrum(-13,2);cableDrum(13,4);pallet(-4,-11);pallet(8,-10);fence(-9,2,7,0);fence(8,-2,6,Math.PI/2);addObstacle(0,8,7,.7,1.6,0x4c5152,'wall');lamp(-12,12,0xff8b43);lamp(0,12,0xffb05b);lamp(12,12,0x72a9d1);chest(-15,-13);chest(15,13);chest(1,-14);}
 else{addObstacle(-7,0,.7,28,2.5,0x394144,'wall');addObstacle(7,0,.7,28,2.5,0x394144,'wall');for(var zz=-12;zz<=12;zz+=6){pipeRun(-5.8,zz,4,false);pipeRun(5.8,zz,4,false);}for(var i=0;i<6;i++){barrel((i%2?4:-4),-12+i*5,i%2?0x4b5960:0x663426);}cableDrum(0,-8);cableDrum(0,8);weldingTable(0,1);lamp(0,-11,0x6da6d6);lamp(0,11,0xff8e42);chest(4,13);}
 player=makeHumanoid(clsIndex(),false);player.position.set(z===2?0:-14,0,z===2?-15:-13);root.add(player);playerParts=player.userData.parts;spawnWave(1);}
function collides(x,z,r){for(var i=0;i<obstacles.length;i++){var o=obstacles[i],dx=Math.max(Math.abs(x-o.x)-o.w/2,0),dz=Math.max(Math.abs(z-o.z)-o.d/2,0);if(dx*dx+dz*dz<r*r)return true;}return x<-18.5||x>18.5||z<-18.5||z>18.5;}
function moveEntity(g,dx,dz,r){var nx=g.position.x+dx,nz=g.position.z;if(!collides(nx,nz,r))g.position.x=nx;nx=g.position.x;nz=g.position.z+dz;if(!collides(nx,nz,r))g.position.z=nz;}
function spawnEnemy(kind,boss,x,z){var e=makeEnemy(kind,boss);e.position.set(x,0,z);root.add(e);enemies.push(e);}
function spawnWave(n){wave=n;waveDelay=0;var count=3+zoneIndex*2+n;for(var i=0;i<count;i++){var kind=zoneIndex===0?(i%3===0?1:0):zoneIndex===1?(i%3===0?2:(i%2?1:0)):(i%3===0?3:2);var a=Math.random()*Math.PI*2,rr=10+Math.random()*6;spawnEnemy(kind,false,Math.cos(a)*rr,Math.sin(a)*rr);}if(n===4)spawnEnemy(4,true,zoneIndex===2?0:10,zoneIndex===2?11:10);updateMission();}
function enemyDeath(e){var idx=enemies.indexOf(e);if(idx>=0)enemies.splice(idx,1);state.kills++;state.gold+=5+zoneIndex*3;state.steel+=Math.random()<.25?1:0;addXp(20+zoneIndex*9+(e.userData.e.boss?120:0));spawnSparks(e.position,rarityColors[e.userData.e.boss?3:1],e.userData.e.boss?28:12);if(Math.random()<(e.userData.e.boss?.95:.42))spawnLoot(e.position,e.userData.e.boss?3:null);root.remove(e);disposeObject(e);save();if(!enemies.length){if(wave<4)waveDelay=1.4;else openExtraction();}}
function spawnLoot(pos,forceR){var it=makeItem(state.level+zoneIndex);if(forceR!=null)it.r=forceR;var g=new THREE.Group(),core=sphere(.22,rarityColors[it.r],0,.35,0,.15,10);core.material=new THREE.MeshStandardMaterial({color:rarityColors[it.r],emissive:rarityColors[it.r],emissiveIntensity:.55,roughness:.35,metalness:.35});g.add(core);var ring=new THREE.Mesh(new THREE.TorusGeometry(.38,.035,6,20),new THREE.MeshBasicMaterial({color:rarityColors[it.r],transparent:true,opacity:.75}));ring.rotation.x=Math.PI/2;ring.position.y=.18;g.add(ring);g.position.copy(pos);g.userData.item=it;root.add(g);loot.push(g);}
function pickupLoot(g){var i=loot.indexOf(g);if(i>=0)loot.splice(i,1);if(state.inventory.length>=14){toast(T.full,'rare');root.remove(g);disposeObject(g);return;}state.inventory.push(g.userData.item);toast(T.pickup+': '+itemName(g.userData.item),rarityNames[g.userData.item.r]);save();root.remove(g);disposeObject(g);}
function spawnSparks(pos,color,n){if(quality<1)n=Math.min(n,5);for(var i=0;i<n&&particles.length<70;i++){var m=sphere(.035,color,pos.x,.6+Math.random(),pos.z,0,5);m.material=new THREE.MeshBasicMaterial({color:color});m.userData.fx={vx:(Math.random()-.5)*5,vy:2+Math.random()*4,vz:(Math.random()-.5)*5,life:.35+Math.random()*.45};root.add(m);particles.push(m);}}
function projectile(pos,dir,color,dmg,speed,ownerType){var m=sphere(.11,color,pos.x,1.05,pos.z,.1,8);m.material=new THREE.MeshBasicMaterial({color:color});m.userData.pr={dx:dir.x*speed,dz:dir.z*speed,life:1.5,dmg:dmg,type:ownerType};root.add(m);projectiles.push(m);}
function openExtraction(){extraction=true;toast(T.ready,'legend');var g=new THREE.Group();addTo(g,box(2.8,1.15,1.35,0x59666d,0,1.05,0,.65));addTo(g,box(1.1,.78,1.28,0x85472f,-1.25,1.45,0,.45));for(var s=-1;s<=1;s+=2){var w=cyl(.36,.36,.28,0x151718,s*.9,.42,.72,.1,12);w.rotation.x=Math.PI/2;g.add(w);var w2=w.clone();w2.position.z=-.72;g.add(w2);}var beacon=sphere(.13,0xffb13b,1.1,1.85,0,.1,8);beacon.material=new THREE.MeshBasicMaterial({color:0xffb13b});g.add(beacon);g.position.set(zoneIndex===2?0:14,0,zoneIndex===2?15:14);root.add(g);extractionObj=g;interactables.push({type:'extract',g:g,x:g.position.x,z:g.position.z,used:false});updateMission();}
function nearestInteract(){var best=null,bd=2.1;for(var i=0;i<interactables.length;i++){var q=interactables[i];if(q.used)continue;var dx=player.position.x-q.x,dz=player.position.z-q.z,d=Math.sqrt(dx*dx+dz*dz);if(d<bd){bd=d;best=q;}}return best;}
function interact(){var q=nearestInteract();if(!q)return;if(q.type==='chest'){q.used=true;spawnSparks(q.g.position,0xe0ae3d,18);for(var i=0;i<2;i++){var p=q.g.position.clone();p.x+=(Math.random()-.5);p.z+=(Math.random()-.5);spawnLoot(p,i===1?2:null);}state.gold+=40;state.steel+=2;save();toast(T.pickup+': +40 '+T.gold,'legend');}else if(q.type==='extract'){finishMission();}}
function finishMission(){state.gold+=80+zoneIndex*55;state.steel+=2+zoneIndex;state.runes+=Math.random()<(.2+zoneIndex*.15)?1:0;addXp(80+zoneIndex*60);mission=false;$('hud').classList.add('hidden');$('menu').classList.remove('hidden');clearWorld();renderWorkshop();save();}
function playerStats(){var c=classes[clsIndex()];maxHp=c.hp+state.armor*8+equippedBonus('armor')*4;maxEn=c.en+state.level*2;return c;}
function startMission(z){init3D();zoneIndex=z;mission=true;extraction=false;wave=0;waveDelay=0;var c=playerStats();hp=maxHp;en=maxEn;attackCd=s1Cd=s2Cd=dashCd=dashTime=hitInv=0;$('menu').classList.add('hidden');$('hud').classList.remove('hidden');$('drawer').classList.add('hidden');$('s1').querySelector('.label').textContent=l(skillNames[clsIndex()][0]);$('s2').querySelector('.label').textContent=l(skillNames[clsIndex()][1]);buildZone(z);clock.getDelta();try{bridge&&bridge.ready();}catch(e){}loop();}
function updateMission(){if(!mission)return;$('missionTitle').textContent=T.mission+': '+l(ZONES[zoneIndex].name);$('missionText').textContent=extraction?T.extract:(T.objective+' · '+T.wave+' '+wave+'/4 · '+enemies.length);}
function updateHud(){var c=playerStats();$('heroName').textContent=l(CLASS_NAMES[clsIndex()]);$('heroSub').textContent=T.level+' '+state.level+' · '+T.gold+' '+state.gold+' · '+T.steel+' '+state.steel;$('hpBar').style.width=Math.max(0,hp/maxHp*100)+'%';$('enBar').style.width=Math.max(0,en/maxEn*100)+'%';$('xpBar').style.width=Math.max(0,state.xp/xpNeed()*100)+'%';updateMission();var nc=nearestInteract();$('interact').style.opacity=nc?'1':'.48';renderMini();}
function renderMini(){var c=$('minimap'),x=c.getContext('2d'),w=c.width,h=c.height;x.fillStyle='#081014';x.fillRect(0,0,w,h);x.strokeStyle='#46545d';x.strokeRect(2,2,w-4,h-4);function mx(v){return (v+20)/40*w;}function mz(v){return (v+20)/40*h;}x.fillStyle='#38434a';for(var i=0;i<obstacles.length;i++){var o=obstacles[i];x.fillRect(mx(o.x-o.w/2),mz(o.z-o.d/2),o.w/40*w,o.d/40*h);}x.fillStyle='#d95b47';for(i=0;i<enemies.length;i++){x.beginPath();x.arc(mx(enemies[i].position.x),mz(enemies[i].position.z),4,0,Math.PI*2);x.fill();}x.fillStyle='#dcb84d';for(i=0;i<loot.length;i++){x.fillRect(mx(loot[i].position.x)-2,mz(loot[i].position.z)-2,4,4);}if(extractionObj){x.fillStyle='#6fd077';x.fillRect(mx(extractionObj.position.x)-5,mz(extractionObj.position.z)-5,10,10);}x.fillStyle='#61b6ee';x.beginPath();x.arc(mx(player.position.x),mz(player.position.z),6,0,Math.PI*2);x.fill();}
function facing(){var f=new THREE.Vector3(0,0,1);f.applyQuaternion(player.quaternion);f.y=0;return f.normalize();}
function attack(){if(!mission||attackCd>0)return;attackCd=.34;attackAnim=.22;var c=playerStats(),range=1.65,dmg=c.damage+state.weapon*4+equippedBonus('weapon')*3;hitArc(range,dmg,1.4);spawnSparks(player.position,0xffad48,5);}
function hitArc(range,dmg,arc){var f=facing();for(var i=enemies.length-1;i>=0;i--){var e=enemies[i],v=tempV.copy(e.position).sub(player.position);v.y=0;var dist=v.length();if(dist>range)continue;v.normalize();if(f.dot(v)<Math.cos(arc))continue;damageEnemy(e,dmg);}}
function damageEnemy(e,dmg){var d=e.userData.e;if(!d)return;d.hp-=dmg;d.flash=.1;spawnSparks(e.position,0xff8b3d,d.boss?10:5);var away=tempV.copy(e.position).sub(player.position).setY(0).normalize();if(!d.boss)moveEntity(e,away.x*.25,away.z*.25,.5);if(d.hp<=0)enemyDeath(e);}
function skill1(){if(!mission||s1Cd>0||en<24)return;en-=24;s1Cd=clsIndex()===0?3.0:clsIndex()===1?2.2:4.5;var ci=clsIndex();if(ci===0){attackAnim=.6;for(var i=enemies.length-1;i>=0;i--)if(enemies[i].position.distanceTo(player.position)<3.0)damageEnemy(enemies[i],32+state.weapon*3);for(var k=0;k<28;k++)spawnSparks(player.position,0xf1a03f,1);}else if(ci===1){var f=facing();projectile(player.position,f,0x57c6ff,42+state.weapon*4,16,'player');projectile(player.position,new THREE.Vector3(f.x+.08,0,f.z-.08).normalize(),0x82dcff,26,15,'player');}else{var dr=makeDrone();dr.scale.setScalar(.82);dr.position.copy(player.position);dr.userData.sum={life:12,cd:0,type:'drone'};root.add(dr);summons.push(dr);toast(l(skillNames[ci][0]),'magic');}}
function skill2(){if(!mission||s2Cd>0||en<34)return;en-=34;s2Cd=clsIndex()===0?4.5:clsIndex()===1?5.2:6.0;var ci=clsIndex();if(ci===0){attackAnim=.55;for(var i=enemies.length-1;i>=0;i--)if(enemies[i].position.distanceTo(player.position)<2.6){damageEnemy(enemies[i],58+state.weapon*5);enemies[i].userData.e.stun=1.1;}spawnSparks(player.position,0xffd06a,24);}else if(ci===1){for(i=0;i<enemies.length;i++)if(enemies[i].position.distanceTo(player.position)<5.1){enemies[i].userData.e.stun=2.2;damageEnemy(enemies[i],18);}spawnSparks(player.position,0xbcecff,30);}else{var t=makeBot();t.scale.setScalar(.72);t.position.copy(player.position);t.position.x+=1.2;t.userData.sum={life:15,cd:0,type:'turret'};root.add(t);summons.push(t);toast(l(skillNames[ci][1]),'magic');}}
function dash(){if(!mission||dashCd>0||en<12)return;en-=12;dashCd=1.1;dashTime=.18;hitInv=.28;}
function playerHit(dmg,from){if(hitInv>0)return;var armor=state.armor*1.4+equippedBonus('armor');dmg=Math.max(2,dmg-armor*.25);hp-=dmg;hitInv=.55;spawnSparks(player.position,0xff4939,12);if(from){var v=tempV.copy(player.position).sub(from.position).setY(0).normalize();moveEntity(player,v.x*.35,v.z*.35,.55);}if(hp<=0){toast(T.dead,'rare');setTimeout(function(){mission=false;$('hud').classList.add('hidden');$('menu').classList.remove('hidden');clearWorld();renderWorkshop();},650);}}
function update(dt){time+=dt;attackCd=Math.max(0,attackCd-dt);s1Cd=Math.max(0,s1Cd-dt);s2Cd=Math.max(0,s2Cd-dt);dashCd=Math.max(0,dashCd-dt);dashTime=Math.max(0,dashTime-dt);hitInv=Math.max(0,hitInv-dt);attackAnim=Math.max(0,attackAnim-dt);en=Math.min(maxEn,en+dt*8.5);var c=playerStats();var mx=joy.x,my=joy.y;if(keys['ArrowLeft']||keys['a'])mx-=1;if(keys['ArrowRight']||keys['d'])mx+=1;if(keys['ArrowUp']||keys['w'])my-=1;if(keys['ArrowDown']||keys['s'])my+=1;var wx=mx-my,wz=-mx-my,mag=Math.sqrt(wx*wx+wz*wz);if(mag>1){wx/=mag;wz/=mag;mag=1;}moveMag=mag;var sp=c.speed*(dashTime>0?2.5:1);if(mag>.05){var dx=wx*sp*dt,dz=wz*sp*dt;moveEntity(player,dx,dz,.52);player.rotation.y=Math.atan2(wx,wz);}animateHumanoid(player,dt,mag>.08,attackAnim>0);
 if(dashTime>0)spawnSparks(player.position,0x8ca8b7,1);
 for(var li=loot.length-1;li>=0;li--){var lg=loot[li];lg.rotation.y+=dt*1.8;lg.position.y=.08+Math.sin(time*3+li)*.08;if(lg.position.distanceTo(player.position)<1.1)pickupLoot(lg);}
 for(var i=enemies.length-1;i>=0;i--){var e=enemies[i],d=e.userData.e;if(!d)continue;d.anim+=dt;d.cd-=dt;d.stun=Math.max(0,d.stun-dt);d.flash=Math.max(0,d.flash-dt);var v=tempV.copy(player.position).sub(e.position);v.y=0;var dist=v.length();if(d.stun<=0){if(dist>1.2){v.normalize();moveEntity(e,v.x*d.speed*dt,v.z*d.speed*dt,d.boss?.9:.5);e.rotation.y=Math.atan2(v.x,v.z);}else if(d.cd<=0){d.cd=d.boss?.8:1.25+Math.random()*.45;playerHit(d.damage,e);}}if(e.userData.parts)animateHumanoid(e,dt,dist>1.3,d.cd>.9);else{e.position.y=(d.kind===1?.75:0)+Math.sin(d.anim*4+i)*.04;e.rotation.y+=d.kind===1?dt*.8:0;}if(d.flash>0)e.scale.setScalar((d.boss?1.28:1)*(1+d.flash*.4));else e.scale.setScalar(d.boss?1.28:1);}
 for(i=projectiles.length-1;i>=0;i--){var pr=projectiles[i],pd=pr.userData.pr;pd.life-=dt;pr.position.x+=pd.dx*dt;pr.position.z+=pd.dz*dt;pr.rotation.y+=dt*8;var hit=false;if(pd.type==='player'){for(var ei=enemies.length-1;ei>=0;ei--){if(pr.position.distanceTo(enemies[ei].position)<.75){damageEnemy(enemies[ei],pd.dmg);hit=true;break;}}}if(hit||pd.life<=0||collides(pr.position.x,pr.position.z,.1)){root.remove(pr);disposeObject(pr);projectiles.splice(i,1);}}
 for(i=summons.length-1;i>=0;i--){var sm=summons[i],sd=sm.userData.sum;sd.life-=dt;sd.cd-=dt;if(sd.type==='drone'){var target=closestEnemy(sm.position,7);if(target){var vv=tempV.copy(target.position).sub(sm.position);var dd=vv.length();vv.normalize();if(dd>3)sm.position.addScaledVector(vv,dt*3.3);if(sd.cd<=0){sd.cd=.7;projectile(sm.position,vv,0xa468ff,14+state.level,12,'player');}}else{var follow=tempV.copy(player.position).sub(sm.position);if(follow.length()>2.2)sm.position.addScaledVector(follow.normalize(),dt*3.4);}sm.position.y=.7+Math.sin(time*5)*.08;}else{target=closestEnemy(sm.position,8);if(target&&sd.cd<=0){sd.cd=.85;projectile(sm.position,tempV.copy(target.position).sub(sm.position).normalize(),0xffb13d,18+state.level,13,'player');}}if(sd.life<=0){root.remove(sm);disposeObject(sm);summons.splice(i,1);}}
 for(i=particles.length-1;i>=0;i--){var p=particles[i],f=p.userData.fx;f.life-=dt;f.vy-=9*dt;p.position.x+=f.vx*dt;p.position.y+=f.vy*dt;p.position.z+=f.vz*dt;if(p.position.y<.03)p.position.y=.03;if(f.life<=0){root.remove(p);disposeObject(p);particles.splice(i,1);}}
 if(!enemies.length&&!extraction){if(waveDelay>0){waveDelay-=dt;if(waveDelay<=0)spawnWave(wave+1);}}
 var target=tempV.copy(player.position);var desired=tempV2.set(target.x+13,target.y+16,target.z+13);camera.position.lerp(desired,Math.min(1,dt*4.4));camera.lookAt(target.x,target.y+.6,target.z);
 uiClock-=dt;if(uiClock<=0){uiClock=.12;updateHud();}
}
function closestEnemy(pos,range){var b=null,bd=range;for(var i=0;i<enemies.length;i++){var d=pos.distanceTo(enemies[i].position);if(d<bd){bd=d;b=enemies[i];}}return b;}
function loop(){if(!mission||!renderer)return;var dt=Math.min(.04,clock.getDelta());update(dt);renderer.render(scene,camera);fpsFrames++;fpsClock+=dt;if(fpsClock>2.2){var fps=fpsFrames/fpsClock;if(fps<34&&quality>0){quality--;renderer.setPixelRatio(quality===0?.75:1.0);resize();}else if(fps>53&&quality<2){quality++;renderer.setPixelRatio(Math.min(window.devicePixelRatio||1,quality===2?1.4:1.0));resize();}fpsFrames=0;fpsClock=0;}requestAnimationFrame(loop);}

function joyPoint(e){var r=$('joy').getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,dx=e.clientX-cx,dy=e.clientY-cy,max=r.width*.33,d=Math.sqrt(dx*dx+dy*dy);if(d>max){dx=dx/d*max;dy=dy/d*max;}joy.x=dx/max;joy.y=dy/max;$('knob').style.transform='translate('+dx+'px,'+dy+'px)';}
$('joy').addEventListener('pointerdown',function(e){joy.id=e.pointerId;this.setPointerCapture(e.pointerId);joyPoint(e);});$('joy').addEventListener('pointermove',function(e){if(e.pointerId===joy.id)joyPoint(e);});function joyEnd(e){if(e.pointerId!==joy.id)return;joy.id=-1;joy.x=joy.y=0;$('knob').style.transform='translate(0,0)';}$('joy').addEventListener('pointerup',joyEnd);$('joy').addEventListener('pointercancel',joyEnd);
function bind(id,fn){$(id).addEventListener('pointerdown',function(e){e.preventDefault();fn();});}bind('atk',attack);bind('s1',skill1);bind('s2',skill2);bind('dash',dash);bind('interact',interact);
window.addEventListener('keydown',function(e){keys[e.key]=true;if(e.key===' ')attack();if(e.key==='q')skill1();if(e.key==='e')skill2();if(e.key==='Shift')dash();if(e.key==='f')interact();});window.addEventListener('keyup',function(e){keys[e.key]=false;});

function shutdown(){mission=false;try{window.removeEventListener('resize',resize);}catch(e){}clearWorld();if(scene){for(var i=0;i<lights.length;i++)scene.remove(lights[i]);lights.length=0;}for(var k in matCache)try{matCache[k].dispose();}catch(e){}matCache={};try{if(renderer){renderer.renderLists.dispose();renderer.dispose();renderer.forceContextLoss();}}catch(e){}renderer=scene=camera=clock=root=player=null;enemies.length=loot.length=particles.length=projectiles.length=summons.length=interactables.length=obstacles.length=0;}
window.GW={shutdown:shutdown};
renderWorkshop();$('workshopPage').classList.add('hidden');$('classPage').classList.remove('hidden');
})();
