/* GRIND & WELD v2.2 world layer: NPCs, side quests, waypoints, fog-of-war, elite packs and procedural salvage vault. */
if(!state.world2)state.world2={};
if(!state.world2.waypoints)state.world2.waypoints={surface:true,foundry:false,cable:false,reactor:false,vault:false};
if(!state.world2.fog)state.world2.fog={};
if(!state.world2.side)state.world2.side={accepted:false,kills:0,chests:0,done:false,rewarded:false};
if(!state.world2.vaultSeed)state.world2.vaultSeed=(Math.random()*2147483646|0)+1;
if(!state.world2.vaultRuns)state.world2.vaultRuns=0;
if(!state.world2.lastArea)state.world2.lastArea='surface';
AREA_NAMES.vault=['Bontókamra','Salvage Vault','Schrottgewölbe','Bóveda de Salvamento','Caveau de Récupération','回收密库','Cripta di Recupero','Cofre de Sucata','Skarbiec Złomu','Schrootkluis','Seiful de Recuperare','Хранилище лома'];
var W2={
npcName:['Varga művezető','Foreman Varga','Vorarbeiter Varga','Capataz Varga','Contremaître Varga','工头瓦尔加','Caposquadra Varga','Encarregado Varga','Brygadzista Varga','Voorman Varga','Maistrul Varga','Прораб Варга'],
sideName:['Mellékmunka: A bontómester tartozása','Side Job: The Salvager’s Debt','Nebenauftrag: Schuld des Schrotters','Encargo: La deuda del chatarrero','Mission secondaire : Dette du ferrailleur','支线：废料商的债务','Incarico: Il debito del rottamatore','Serviço: A dívida do sucateiro','Zlecenie: Dług złomiarza','Bijbaan: Schuld van de sloper','Misiune: Datoria recuperatorului','Побочный заказ: Долг сборщика'],
sideAsk:['Tisztíts meg 12 fosztogatót és nyiss ki 3 ládát. Utána megmutatom a Bontókamra bejáratát.','Clear 12 raiders and open 3 caches. Then I will reveal the Salvage Vault.','Besiege 12 Plünderer und öffne 3 Kisten. Dann zeige ich dir das Schrottgewölbe.','Elimina 12 saqueadores y abre 3 cofres. Después revelaré la Bóveda.','Éliminez 12 pillards et ouvrez 3 caches. Ensuite je révélerai le Caveau.','消灭12名掠夺者并打开3个补给箱，然后我会揭示回收密库。','Elimina 12 predoni e apri 3 casse. Poi rivelerò la Cripta.','Elimine 12 saqueadores e abra 3 caixas. Depois revelarei o Cofre.','Pokonaj 12 rabusiów i otwórz 3 skrzynie. Potem ujawnię Skarbiec.','Versla 12 plunderaars en open 3 kisten. Dan onthul ik de Schrootkluis.','Elimină 12 jefuitori și deschide 3 lăzi. Apoi dezvălui Seiful.','Уничтожьте 12 мародёров и откройте 3 тайника. Потом я покажу Хранилище.'],
accepted:['Mellékmunka felvéve','Side job accepted','Nebenauftrag angenommen','Encargo aceptado','Mission acceptée','已接受支线','Incarico accettato','Serviço aceito','Zlecenie przyjęte','Bijbaan aangenomen','Misiune acceptată','Заказ принят'],
done:['Bontókamra feloldva','Salvage Vault unlocked','Schrottgewölbe freigeschaltet','Bóveda desbloqueada','Caveau débloqué','回收密库已解锁','Cripta sbloccata','Cofre desbloqueado','Skarbiec odblokowany','Schrootkluis ontgrendeld','Seiful deblocat','Хранилище открыто'],
waypoint:['Útpont','Waypoint','Wegpunkt','Punto de ruta','Point de passage','传送点','Punto di viaggio','Ponto de rota','Punkt trasy','Reispunt','Punct de traseu','Путевая точка'],
activated:['aktiválva','activated','aktiviert','activado','activé','已激活','attivato','ativado','aktywowany','geactiveerd','activat','активирована'],
elite:['ELIT','ELITE','ELITE','ÉLITE','ÉLITE','精英','ÉLITE','ELITE','ELITA','ELITE','ELITĂ','ЭЛИТА'],
vaultObjective:['Találd meg a 3 ipari relikviát, majd öld meg a Bontókamra őrét.','Recover 3 industrial relics, then defeat the Salvage Warden.','Finde 3 Industrie-Relikte und besiege dann den Gewölbewächter.','Recupera 3 reliquias industriales y derrota al Guardián.','Récupérez 3 reliques industrielles puis battez le Gardien.','找回3件工业遗物，然后击败密库守卫。','Recupera 3 reliquie industriali e sconfiggi il Guardiano.','Recupere 3 relíquias industriais e derrote o Guardião.','Odzyskaj 3 relikty przemysłowe i pokonaj Strażnika.','Vind 3 industriële relikwieën en versla de Kluiswachter.','Recuperează 3 relicve industriale și învinge Gardianul.','Найдите 3 промышленные реликвии и победите Стража.'],
relic:['Relikvia','Relic','Relikt','Reliquia','Relique','遗物','Reliquia','Relíquia','Relikt','Relikwie','Relicvă','Реликвия'],
vaultClear:['Bontókamra megtisztítva','Salvage Vault cleared','Schrottgewölbe gesäubert','Bóveda despejada','Caveau nettoyé','回收密库已清理','Cripta ripulita','Cofre limpo','Skarbiec oczyszczony','Schrootkluis gezuiverd','Seiful curățat','Хранилище очищено']};
function w2l(a){return a[Math.max(0,Math.min(11,lang))]||a[1];}
function w2Seeded(seed){var x=seed|0;return function(){x=(x*1664525+1013904223)|0;return ((x>>>0)/4294967296);};}
function w2Reveal(){if(!mission||!player)return;var f=state.world2.fog[areaKey]||(state.world2.fog[areaKey]={});var gx=Math.floor((player.position.x-areaBounds.minX)/6),gz=Math.floor((player.position.z-areaBounds.minZ)/6);for(var x=gx-1;x<=gx+1;x++)for(var z=gz-1;z<=gz+1;z++)f[x+','+z]=1;}
function w2Npc(x,z){var g=makeHumanoid(0,false);g.scale.setScalar(.92);g.position.set(x,0,z);g.rotation.y=Math.PI*.75;root.add(g);var ring=new THREE.Mesh(new THREE.TorusGeometry(.72,.055,7,24),new THREE.MeshBasicMaterial({color:0xe3b45a,transparent:true,opacity:.88}));ring.rotation.x=Math.PI/2;ring.position.y=.08;g.add(ring);interactables.push({type:'npc_varga',g:g,x:x,z:z,used:false});campaignBeacon(x,z,0xe3b45a,w2l(W2.npcName));}
function w2Waypoint(x,z,key){var g=new THREE.Group();addTo(g,cyl(.72,.86,.28,0x3c4c55,0,.14,0,.7,12));var r=new THREE.Mesh(new THREE.TorusGeometry(.58,.075,8,30),new THREE.MeshBasicMaterial({color:state.world2.waypoints[key]?0x54d5ee:0x7a6e61,transparent:true,opacity:.9}));r.rotation.x=Math.PI/2;r.position.y=.34;g.add(r);addTo(g,sphere(.18,state.world2.waypoints[key]?0x6deaff:0x8a7c68,0,.64,0,.1,10));g.position.set(x,0,z);root.add(g);interactables.push({type:'waypoint',g:g,x:x,z:z,wp:key,used:false});}
function w2UnlockedWaypointKeys(){var order=['surface','foundry','cable','reactor','vault'],a=[];for(var i=0;i<order.length;i++)if(state.world2.waypoints[order[i]])a.push(order[i]);return a;}
function w2WaypointTravel(q){if(!state.world2.waypoints[q.wp]){state.world2.waypoints[q.wp]=true;state.world2.lastArea=q.wp;save();toast(w2l(W2.waypoint)+' '+w2l(W2.activated),'magic');return;}var a=w2UnlockedWaypointKeys(),idx=a.indexOf(q.wp),next=a[(idx+1)%a.length];if(next===q.wp){toast(w2l(W2.waypoint)+' '+w2l(W2.activated),'magic');return;}state.world2.lastArea=next;save();buildArea(next);toast(w2l(W2.waypoint)+': '+l(AREA_NAMES[next]),'magic');}
function w2SideProgress(){var s=state.world2.side;return s.kills+'/12 · '+s.chests+'/3';}
function w2NpcInteract(){var s=state.world2.side;if(!s.accepted){s.accepted=true;s.kills=0;s.chests=0;toast(w2l(W2.accepted),'magic');save();updateMission();return;}if(!s.done){if(s.kills>=12&&s.chests>=3){s.done=true;state.world2.waypoints.vault=true;state.gold+=180;state.steel+=5;addXp(160);toast(w2l(W2.done),'legend');save();updateMission();}else toast(w2l(W2.sideName)+': '+w2SideProgress(),'magic');return;}if(!s.rewarded){s.rewarded=true;state.runes+=1;state.gold+=75;save();toast('+75 '+T.gold+' · +1 '+T.runes,'legend');return;}toast(w2l(W2.done),'magic');}
function w2UpgradeElite(e,index){if(!e||!e.userData||!e.userData.e||e.userData.e.boss||e.userData.e.elite)return;var d=e.userData.e;d.elite=true;d.hp=Math.round(d.hp*2.15);d.max=d.hp;d.damage=Math.round(d.damage*1.42);d.speed*=1.06;d.eliteRank=1+(index%3);var ring=new THREE.Mesh(new THREE.TorusGeometry(.7,.055,7,20),new THREE.MeshBasicMaterial({color:d.eliteRank===3?0xe5b34f:0xb05bd8,transparent:true,opacity:.82}));ring.rotation.x=Math.PI/2;ring.position.y=.08;ring.name='eliteAura';e.add(ring);}
var _w2SpawnAmbient=spawnAmbient;spawnAmbient=function(count){var before=enemies.length;_w2SpawnAmbient(count);for(var i=before;i<enemies.length;i++)if((i-before)%5===2)w2UpgradeElite(enemies[i],i-before);};
function w2VaultRelic(x,z){var g=new THREE.Group();addTo(g,box(.52,.55,.52,0x4b5154,0,.28,0,.75));var c=sphere(.14,0x72e1ff,0,.66,0,.1,10);c.material=new THREE.MeshBasicMaterial({color:0x72e1ff});g.add(c);g.position.set(x,0,z);root.add(g);interactables.push({type:'vault_relic',g:g,x:x,z:z,used:false});campaignBeacon(x,z,0x72e1ff,w2l(W2.relic));}
function w2BuildVault(){areaKey='vault';zoneIndex=2;setCampaignBounds(-30,30,-30,30);areaEntry={x:-25,z:-25};scene.background.set(0x070a0c);scene.fog.color.copy(scene.background);campaignGround();campaignBoundary();var rnd=w2Seeded((state.world2.vaultSeed+state.world2.vaultRuns*7919)|0);campaignReturn(-25,-25,-33,32);w2Waypoint(-22,-22,'vault');campaignRoad(0,0,8,54,0x292d30);campaignRoad(0,0,54,8,0x292d30);for(var i=0;i<14;i++){var x=-22+rnd()*44,z=-22+rnd()*44,w=2.2+rnd()*4.5,d=2.2+rnd()*4.5;if(Math.abs(x)<6||Math.abs(z)<6||Math.hypot(x+25,z+25)<8)continue;addObstacle(x,z,w,d,1.8+rnd()*.8,rnd()>.5?0x40464a:0x4b4038,'wall');if(rnd()>.5)barrel(x+(rnd()-.5)*(w+2),z+(rnd()-.5)*(d+2),rnd()>.5?0x6b3528:0x405764);}for(i=0;i<8;i++){var cx=-20+rnd()*40,cz=-20+rnd()*40;if(!collides(cx,cz,.8))crate(cx,cz,.85+rnd()*.45);}for(i=0;i<5;i++){var lx=-20+rnd()*40,lz=-20+rnd()*40;if(!collides(lx,lz,.8))lamp(lx,lz,i%2?0xff904e:0x6abfe7);}chest(-20,20);chest(21,-8);chest(16,22);if(state.world2.vaultRelics==null)state.world2.vaultRelics=0;var spots=[[-18,9],[10,-17],[19,17]],p=Math.max(0,Math.min(3,state.world2.vaultRelics||0));for(i=p;i<3;i++)w2VaultRelic(spots[i][0],spots[i][1]);if(p>=3){spawnEnemy(4,true,20,20);enemies[enemies.length-1].userData.e.tag='vaultwarden';}spawnAmbient(16);}
var _w2BuildSurface=buildSurface;buildSurface=function(){_w2BuildSurface();w2Npc(-37,-29);w2Waypoint(-35,-35,'surface');if(state.world2.side.done)campaignPortal(-37,20,'vault');};
var _w2BuildFoundry=buildFoundry;buildFoundry=function(){_w2BuildFoundry();w2Waypoint(0,-18,'foundry');};
var _w2BuildCable=buildCable;buildCable=function(){_w2BuildCable();w2Waypoint(-21,-14,'cable');};
var _w2BuildReactor=buildReactor;buildReactor=function(){_w2BuildReactor();w2Waypoint(0,-16,'reactor');};
buildArea=function(key,spawnX,spawnZ){clearWorld();matCache={};questBeacons=[];areaKey=key;bossSpawned=false;if(key==='surface')buildSurface();else if(key==='foundry')buildFoundry();else if(key==='cable')buildCable();else if(key==='reactor')buildReactor();else w2BuildVault();player=makeHumanoid(clsIndex(),false);player.position.set(spawnX!=null?spawnX:areaEntry.x,0,spawnZ!=null?spawnZ:areaEntry.z);root.add(player);playerParts=player.userData.parts;state.world2.lastArea=key;w2Reveal();updateMission();save();};
var _w2PortalUnlocked=portalUnlocked;portalUnlocked=function(t){if(t==='vault')return !!state.world2.side.done;return _w2PortalUnlocked(t);};
var _w2Interact=interact;interact=function(){var q=nearestInteract();if(!q)return;if(q.type==='npc_varga'){w2NpcInteract();return;}if(q.type==='waypoint'){w2WaypointTravel(q);return;}if(q.type==='vault_relic'){q.used=true;state.world2.vaultRelics=Math.min(3,(state.world2.vaultRelics||0)+1);spawnSparks(q.g.position,0x72e1ff,22);toast(w2l(W2.relic)+' '+state.world2.vaultRelics+'/3','magic');if(state.world2.vaultRelics>=3&&!bossSpawned){spawnEnemy(4,true,20,20);enemies[enemies.length-1].userData.e.tag='vaultwarden';bossSpawned=true;toast(T.boss+': SALVAGE WARDEN','legend');}save();updateMission();return;}var wasChest=q.type==='chest'&&!q.used;_w2Interact();if(wasChest&&state.world2.side.accepted&&!state.world2.side.done){state.world2.side.chests=Math.min(3,state.world2.side.chests+1);save();updateMission();}};
var _w2EnemyDeath=enemyDeath;enemyDeath=function(e){var d=e&&e.userData?e.userData.e:null,elite=!!(d&&d.elite),tag=d&&d.tag;if(state.world2.side.accepted&&!state.world2.side.done&&!(d&&d.boss))state.world2.side.kills=Math.min(12,state.world2.side.kills+1);if(elite){state.gold+=18;addXp(22);if(Math.random()<.55)spawnLoot(e.position,d.eliteRank>=3?2:null);toast(w2l(W2.elite)+' +18 '+T.gold,'rare');}if(tag==='vaultwarden'){state.world2.vaultRuns++;state.world2.vaultRelics=0;state.world2.vaultSeed=((state.world2.vaultSeed*1103515245+12345)&0x7fffffff)||1;state.gold+=220;state.steel+=5;state.runes+=1;addXp(240);toast(w2l(W2.vaultClear),'legend');}_w2EnemyDeath(e);save();updateMission();};
var _w2Update=update;update=function(dt){_w2Update(dt);w2Reveal();for(var i=0;i<enemies.length;i++){var d=enemies[i].userData.e;if(d&&d.elite&&!d.boss)enemies[i].scale.setScalar(1.10);}};
var _w2UpdateMission=updateMission;updateMission=function(){_w2UpdateMission();if(!mission)return;if(areaKey==='vault'){$('missionTitle').textContent=T.mission+': '+l(AREA_NAMES.vault);$('missionText').textContent=w2l(W2.vaultObjective)+' · '+(state.world2.vaultRelics||0)+'/3';return;}var s=state.world2.side;if(s.accepted&&!s.done&&areaKey==='surface')$('missionText').textContent+=' · '+w2l(W2.sideName)+' '+w2SideProgress();};
var _w2RenderMini=renderMini;renderMini=function(){_w2RenderMini();if(!mission||!player)return;var c=$('minimap'),x=c.getContext('2d'),w=c.width,h=c.height,f=state.world2.fog[areaKey]||{},sx=areaBounds.maxX-areaBounds.minX,sz=areaBounds.maxZ-areaBounds.minZ,cw=6/sx*w,ch=6/sz*h;x.fillStyle='rgba(1,4,6,.88)';for(var gx=0;gx<Math.ceil(sx/6);gx++)for(var gz=0;gz<Math.ceil(sz/6);gz++)if(!f[gx+','+gz])x.fillRect(gx*cw,gz*ch,cw+1,ch+1);function mx(v){return (v-areaBounds.minX)/sx*w;}function mz(v){return (v-areaBounds.minZ)/sz*h;}x.fillStyle='#61b6ee';x.beginPath();x.arc(mx(player.position.x),mz(player.position.z),5,0,Math.PI*2);x.fill();};
var _w2RenderWorkshop=renderWorkshop;renderWorkshop=function(){_w2RenderWorkshop();var zr=$('zones');if(zr){var d=document.createElement('div'),s=state.world2.side;d.className='card zone'+(s.done?' sel':'');d.innerHTML='<strong>'+(s.done?'✓ ':'• ')+w2l(W2.sideName)+'</strong><p>'+w2l(W2.sideAsk)+'</p><p>'+(s.accepted?w2SideProgress():'NPC: '+w2l(W2.npcName))+'</p>';zr.appendChild(d);}};