/* GRIND & WELD v2.4: contracts, dual equipment, consumables, nemesis hunts and repeatable Rust Rift endgame. */
if(!state.world4)state.world4={};
var w4=state.world4;
if(w4.contractsDone==null)w4.contractsDone=0;
if(!w4.contract)w4.contract={active:false,type:0,target:0,progress:0,reward:0};
if(w4.medkits==null)w4.medkits=2;
if(w4.equipWeapon==null)w4.equipWeapon=-1;
if(w4.equipArmor==null)w4.equipArmor=-1;
if(w4.nemesisCycle==null)w4.nemesisCycle=0;
if(w4.riftTier==null)w4.riftTier=1;
if(w4.riftRuns==null)w4.riftRuns=0;
if(!w4.riftSeed)w4.riftSeed=(Math.random()*2147483646|0)+1;
if(w4.riftCleared==null)w4.riftCleared=false;
if(w4.equipWeapon<0||!state.inventory[w4.equipWeapon]||state.inventory[w4.equipWeapon].slot!=='weapon'){
 if(state.equipped>=0&&state.inventory[state.equipped]&&state.inventory[state.equipped].slot==='weapon')w4.equipWeapon=state.equipped;
}
if(w4.equipArmor<0||!state.inventory[w4.equipArmor]||state.inventory[w4.equipArmor].slot!=='armor'){
 if(state.equipped>=0&&state.inventory[state.equipped]&&state.inventory[state.equipped].slot==='armor')w4.equipArmor=state.equipped;
}
AREA_NAMES.rift=['Rozsdahasádék','Rust Rift','Rostspalt','Falla de Óxido','Faille de Rouille','锈蚀裂隙','Faglia di Ruggine','Fenda da Ferrugem','Szczelina Rdzy','Roestspleet','Falia Ruginii','Ржавый разлом'];
var W4={
board:['Szerződéstábla','Contract Board','Auftragstafel','Tablón de contratos','Tableau des contrats','合同板','Bacheca incarichi','Quadro de contratos','Tablica zleceń','Opdrachtenbord','Panou de contracte','Доска контрактов'],
accepted:['Szerződés felvéve','Contract accepted','Auftrag angenommen','Contrato aceptado','Contrat accepté','已接受合同','Incarico accettato','Contrato aceito','Zlecenie przyjęte','Opdracht aangenomen','Contract acceptat','Контракт принят'],
turnin:['Szerződés teljesítve','Contract complete','Auftrag erfüllt','Contrato completado','Contrat terminé','合同完成','Incarico completato','Contrato concluído','Zlecenie ukończone','Opdracht voltooid','Contract finalizat','Контракт выполнен'],
kill:['Semlegesíts ellenfeleket','Eliminate enemies','Gegner ausschalten','Elimina enemigos','Éliminer des ennemis','消灭敌人','Elimina nemici','Elimine inimigos','Pokonaj wrogów','Schakel vijanden uit','Elimină inamici','Уничтожьте врагов'],
elite:['Vadászd le az eliteket','Hunt elite enemies','Elite jagen','Caza élites','Chasser les élites','猎杀精英','Caccia gli élite','Cace elites','Poluj na elitę','Jaag op elites','Vânează elite','Охотьтесь на элиту'],
cache:['Nyiss ellátmányládákat','Open supply caches','Versorgungskisten öffnen','Abre alijos','Ouvrir des caches','开启补给箱','Apri casse','Abra caixas','Otwórz skrzynie','Open voorraadkisten','Deschide lăzi','Откройте тайники'],
medkit:['Javítócsomag','Repair kit','Reparaturset','Kit de reparación','Kit de réparation','修复包','Kit riparazione','Kit de reparo','Zestaw naprawczy','Reparatieset','Kit de reparație','Ремкомплект'],
weapon:['Fegyver slot','Weapon slot','Waffenslot','Ranura de arma','Emplacement arme','武器栏','Slot arma','Slot de arma','Slot broni','Wapenslot','Slot armă','Слот оружия'],
armor:['Páncél slot','Armor slot','Rüstungsslot','Ranura de armadura','Emplacement armure','护甲栏','Slot armatura','Slot de armadura','Slot pancerza','Pantser slot','Slot armură','Слот брони'],
nemesis:['Nemezis érkezett','Nemesis has arrived','Nemesis ist da','Ha llegado Némesis','Le Némésis est arrivé','宿敌已出现','È arrivata la Nemesi','Nêmesis chegou','Nemezis nadciągnął','Nemesis is verschenen','Nemesis a sosit','Немезида прибыла'],
nemesisDead:['Nemezis legyőzve','Nemesis defeated','Nemesis besiegt','Némesis derrotado','Némésis vaincu','宿敌已击败','Nemesi sconfitta','Nêmesis derrotado','Nemezis pokonany','Nemesis verslagen','Nemesis învins','Немезида побеждена'],
rift:['Rozsdahasádék','Rust Rift','Rostspalt','Falla de Óxido','Faille de Rouille','锈蚀裂隙','Faglia di Ruggine','Fenda da Ferrugem','Szczelina Rdzy','Roestspleet','Falia Ruginii','Ржавый разлом'],
riftObj:['Győzd le a Hasadék Őrét','Defeat the Rift Guardian','Besiege den Spaltwächter','Derrota al Guardián','Vaincre le Gardien','击败裂隙守卫','Sconfiggi il Guardiano','Derrote o Guardião','Pokonaj Strażnika','Versla de Wachter','Învinge Gardianul','Победите Стража'],
riffDone:['Hasadékszint teljesítve','Rift tier cleared','Spaltstufe geschafft','Nivel de falla superado','Palier terminé','裂隙层已完成','Livello completato','Nível concluído','Poziom ukończony','Niveau voltooid','Nivel finalizat','Уровень разлома пройден'],
guardian:['Hasadék Őre','Rift Guardian','Spaltwächter','Guardián de la Falla','Gardien de la Faille','裂隙守卫','Guardiano della Faglia','Guardião da Fenda','Strażnik Szczeliny','Wachter van de Spleet','Gardianul Faliei','Страж Разлома'],
rareNames:[
 ['Rozsdakirály','Rust King','Rostkönig','Rey del Óxido','Roi de Rouille','锈王','Re della Ruggine','Rei da Ferrugem','Król Rdzy','Roestkoning','Regele Ruginii','Король Ржавчины'],
 ['Ívfaló','Arc Eater','Bogenfresser','Devoraarcos','Dévoreur d’Arc','噬弧者','Divora-Arco','Devorador de Arco','Pożeracz Łuku','Boogvreter','Devoratorul de Arc','Пожиратель Дуги'],
 ['Kohóvadász','Forge Stalker','Schmiedepirscher','Acechaforjas','Traqueur de Forge','熔炉猎手','Cacciatore di Forgia','Caçador da Forja','Łowca Kuźni','Smederijstalker','Vânătorul Forjei','Охотник Кузни'],
 ['Acélkísértet','Steel Wraith','Stahlgeist','Espectro de Acero','Spectre d’Acier','钢铁幽魂','Spettro d’Acciaio','Espectro de Aço','Widmo Stali','Staalgeest','Spectrul de Oțel','Стальной Призрак']
 ],
stat:['CRIT','LEECH','ENERGY','SPEED']
};
function w4l(a){return a[Math.max(0,Math.min(11,lang))]||a[1];}
function w4ContractText(){var c=w4.contract;if(!c.active)return w4l(W4.board)+' · '+w4.contractsDone;var n=c.type===0?W4.kill:c.type===1?W4.elite:W4.cache;return w4l(n)+': '+Math.min(c.target,c.progress)+'/'+c.target;}
function w4NewContract(){var k=w4.contractsDone%3,t=k===0?0:k===1?1:2,target=t===0?14+Math.min(12,w4.contractsDone*2):t===1?4+Math.min(4,(w4.contractsDone/3)|0):3+Math.min(3,(w4.contractsDone/4)|0);w4.contract={active:true,type:t,target:target,progress:0,reward:140+state.level*18+w4.contractsDone*25};save();toast(w4l(W4.accepted)+' · '+w4ContractText(),'magic');updateMission();}
function w4BoardInteract(){var c=w4.contract;if(!c.active){w4NewContract();return;}if(c.progress<c.target){toast(w4ContractText(),'magic');return;}state.gold+=c.reward;state.steel+=3+(w4.contractsDone%3);if(c.type===1)state.runes+=1;w4.contractsDone++;c.active=false;toast(w4l(W4.turnin)+' · +'+c.reward+' '+T.gold,'legend');save();updateMission();}
function w4Board(x,z){var g=new THREE.Group();addTo(g,box(1.9,.18,.9,0x3b4145,0,.1,0,.7));addTo(g,box(1.5,1.25,.14,0x6a4a32,0,1.0,0,.7));for(var i=-1;i<=1;i++)addTo(g,box(.28,.35,.03,i===0?0xd9b35c:0xc9c2aa,i*.42,1.05,.09,.4));g.position.set(x,0,z);root.add(g);interactables.push({type:'w4_board',g:g,x:x,z:z,used:false});campaignBeacon(x,z,0xd9b35c,w4l(W4.board));}
function w4KitUse(){if(w4.medkits<=0){toast(w4l(W4.medkit)+': 0','rare');return false;}if(hp>=maxHp*.98&&en>=maxEn*.9)return false;w4.medkits--;hp=Math.min(maxHp,hp+maxHp*.42);en=Math.min(maxEn,en+maxEn*.28);spawnSparks(player.position,0x7be0a4,16);toast(w4l(W4.medkit)+' -1','magic');save();return true;}
function w4ItemAt(type){var idx=type==='weapon'?w4.equipWeapon:w4.equipArmor;if(idx>=0&&state.inventory[idx]&&state.inventory[idx].slot===type)return state.inventory[idx];if(state.equipped>=0&&state.inventory[state.equipped]&&state.inventory[state.equipped].slot===type)return state.inventory[state.equipped];return null;}
function w4ItemIndex(type){var idx=type==='weapon'?w4.equipWeapon:w4.equipArmor;return idx>=0&&state.inventory[idx]&&state.inventory[idx].slot===type?idx:-1;}
function w4StatText(it){if(!it||it.w4stat==null)return '';return ' · '+W4.stat[it.w4stat%4]+' +'+(it.w4val||1);}
var _w4MakeItem=makeItem;makeItem=function(tier){var it=_w4MakeItem(tier);if(it.r>=2&&it.w4stat==null){it.w4stat=(Math.random()*4)|0;it.w4val=1+it.r+((Math.random()*2)|0);}return it;};
var _w4ItemName=itemName;itemName=function(it){return _w4ItemName(it)+w4StatText(it);};
equippedBonus=function(type){var it=w4ItemAt(type),b=it?(it.power||0):0;if(it){if(it.mod===0||it.mod2===0)b+=2;if(type==='armor'&&(it.mod===1||it.mod2===1))b+=3;if(type==='weapon'&&(it.mod===2||it.mod2===2))b+=3;if(it.mod===3||it.mod2===3)b+=Math.max(1,(it.r||0));}if(w3.blessing&&w3.blessing.end>time){if(type==='weapon'&&w3.blessing.type===0)b+=4;if(type==='armor'&&w3.blessing.type===1)b+=4;}return b;};
var _w4PlayerStats=playerStats;playerStats=function(){var c=_w4PlayerStats(),a=w4ItemAt('armor'),m=1,enx=0;if(a&&a.w4stat===3)m+=.025*(a.w4val||1);if(a&&a.w4stat===2)enx=5*(a.w4val||1);if(m!==1||enx){return {id:c.id,hp:c.hp,en:c.en+enx,speed:c.speed*m,damage:c.damage,color:c.color};}return c;};
var _w4DamageEnemy=damageEnemy;damageEnemy=function(e,dmg){var it=w4ItemAt('weapon');if(it&&it.w4stat===0&&Math.random()<.035*(it.w4val||1)){dmg*=1.65;spawnSparks(e.position,0xffd85d,12);}var before=e&&e.userData&&e.userData.e?e.userData.e.hp:0,r=_w4DamageEnemy(e,dmg);if(it&&it.w4stat===1&&before>0)hp=Math.min(maxHp,hp+Math.max(1,dmg*.012*(it.w4val||1)));return r;};
function w4RebuildLoadout(){var lr=$('loadout');if(!lr)return;lr.innerHTML='';if(!state.inventory.length){lr.innerHTML='<div class="tiny">-</div>';return;}for(var j=0;j<state.inventory.length;j++){(function(j){var it=state.inventory[j],d=document.createElement('div'),on=(it.slot==='weapon'?w4.equipWeapon:w4.equipArmor)===j;d.className='lootrow '+rarityNames[it.r];d.innerHTML='<b>'+itemName(it)+'</b>'+it.slot.toUpperCase()+' +'+it.power+(on?' · '+T.equipped:'');d.onclick=function(){state.equipped=j;if(it.slot==='weapon')w4.equipWeapon=j;else w4.equipArmor=j;save();renderWorkshop();};lr.appendChild(d);})(j);}}
var _w4RenderWorkshop=renderWorkshop;renderWorkshop=function(){_w4RenderWorkshop();w4RebuildLoadout();var pb=$('profileBox'),ci=clsIndex(),wi=w4ItemIndex('weapon'),ai=w4ItemIndex('armor'),wn=wi>=0?itemName(state.inventory[wi]):'-',an=ai>=0?itemName(state.inventory[ai]):'-';if(pb)pb.innerHTML='<b>'+l(CLASS_NAMES[ci])+'</b><br>'+T.level+' '+state.level+' · XP '+state.xp+'/'+xpNeed()+'<br>'+T.weapon+' +'+state.weapon+' · '+T.armor+' +'+state.armor+'<br><span class="eq">'+w4l(W4.weapon)+': '+wn+'<br>'+w4l(W4.armor)+': '+an+'</span>';var r=$('resourceBox');if(r)r.innerHTML+='<br><span class="eq">'+w4l(W4.medkit)+': '+w4.medkits+' · '+w4ContractText()+(w3.deepCleared?' · '+w4l(W4.rift)+' T'+w4.riftTier:'')+'</span>';};
function w4ShouldNemesis(){return w4.contractsDone>=3&&w4.nemesisCycle<Math.floor(w4.contractsDone/3);}
function w4SpawnNemesis(){if(!w4ShouldNemesis())return;var x=34,z=-27;spawnEnemy(4,true,x,z);var e=enemies[enemies.length-1],d=e.userData.e,tier=Math.max(1,Math.floor(w4.contractsDone/3));e.scale.setScalar(1.45+Math.min(.35,tier*.03));d.tag='w4_nemesis';d.hp=Math.round(d.hp*(2.0+tier*.18));d.max=d.hp;d.damage=Math.round(d.damage*(1.35+tier*.05));d.speed*=1.08;d.nemesisName=w4l(W4.rareNames[(tier-1)%W4.rareNames.length]);var ring=new THREE.Mesh(new THREE.TorusGeometry(.95,.075,8,28),new THREE.MeshBasicMaterial({color:0xf0b54a,transparent:true,opacity:.92}));ring.rotation.x=Math.PI/2;ring.position.y=.09;e.add(ring);campaignBeacon(x,z,0xf0b54a,d.nemesisName);toast(w4l(W4.nemesis)+': '+d.nemesisName,'legend');}
function w4RiftBoss(tier){spawnEnemy(4,true,23,23);var e=enemies[enemies.length-1],d=e.userData.e;e.scale.setScalar(1.5+Math.min(.45,tier*.025));d.tag='w4_riftboss';d.hp=Math.round(d.hp*(2.0+tier*.22));d.max=d.hp;d.damage=Math.round(d.damage*(1.25+tier*.07));d.speed*=1+Math.min(.28,tier*.015);var ring=new THREE.Mesh(new THREE.TorusGeometry(1.0,.08,8,30),new THREE.MeshBasicMaterial({color:0xa86cff,transparent:true,opacity:.9}));ring.rotation.x=Math.PI/2;ring.position.y=.1;e.add(ring);campaignBeacon(23,23,0xa86cff,w4l(W4.guardian)+' T'+tier);}
function w4BuildRift(){areaKey='rift';zoneIndex=5;setCampaignBounds(-40,40,-40,40);areaEntry={x:-34,z:-34};scene.background.set(0x08050b);scene.fog.color.copy(scene.background);campaignGround();campaignBoundary();campaignReturn(-35,-35,-32,-31);var tier=Math.max(1,w4.riftTier),rnd=w2Seeded((w4.riftSeed+tier*104729+w4.riftRuns*7919)|0);campaignRoad(0,0,9,70,0x27222b);campaignRoad(0,0,70,9,0x27222b);for(var i=0;i<18;i++){var x=-30+rnd()*60,z=-30+rnd()*60,w=2.5+rnd()*5,d=2.5+rnd()*5;if(Math.abs(x)<7||Math.abs(z)<7||Math.hypot(x+34,z+34)<8||Math.hypot(x-23,z-23)<7)continue;addObstacle(x,z,w,d,1.7+rnd()*1.5,rnd()>.45?0x44394b:0x3c4146,'wall');if(rnd()>.55)barrel(x+(rnd()-.5)*(w+2),z+(rnd()-.5)*(d+2),rnd()>.5?0x703629:0x3f5360);}for(i=0;i<10;i++){var cx=-28+rnd()*56,cz=-28+rnd()*56;if(!collides(cx,cz,.8))crate(cx,cz,.9+rnd()*.4);}for(i=0;i<7;i++){var lx=-27+rnd()*54,lz=-27+rnd()*54;if(!collides(lx,lz,.8))lamp(lx,lz,i%2?0xa86cff:0xff7b43);}chest(-25,25);chest(25,-22);w3Shrine(-18,18,tier%3);var before=enemies.length;spawnAmbient(Math.min(28,14+tier));for(i=before;i<enemies.length;i++){var ed=enemies[i].userData.e;ed.hp=Math.round(ed.hp*(1+tier*.08));ed.max=ed.hp;ed.damage=Math.round(ed.damage*(1+tier*.045));if((i-before)%3===1&&!ed.elite)w2UpgradeElite(enemies[i],i-before+tier);}w4.riftCleared=false;w4RiftBoss(tier);}
var _w4BuildSurface=buildSurface;buildSurface=function(){_w4BuildSurface();w4Board(-14,-35);if(w3.deepCleared)campaignPortal(38,22,'rift');w4SpawnNemesis();};
var _w4PortalUnlocked=portalUnlocked;portalUnlocked=function(t){if(t==='rift')return !!w3.deepCleared;return _w4PortalUnlocked(t);};
var _w4BuildArea=buildArea;buildArea=function(key,spawnX,spawnZ){if(key!=='rift'){_w4BuildArea(key,spawnX,spawnZ);return;}clearWorld();matCache={};questBeacons=[];areaKey='rift';bossSpawned=false;w4BuildRift();player=makeHumanoid(clsIndex(),false);player.position.set(spawnX!=null?spawnX:areaEntry.x,0,spawnZ!=null?spawnZ:areaEntry.z);root.add(player);playerParts=player.userData.parts;state.world2.lastArea='rift';w2Reveal();updateMission();save();};
var _w4EnemyDeath=enemyDeath;enemyDeath=function(e){var d=e&&e.userData?e.userData.e:null,c=w4.contract;if(c.active){if(c.type===0)c.progress=Math.min(c.target,c.progress+1);else if(c.type===1&&d&&d.elite)c.progress=Math.min(c.target,c.progress+1);}var nem=d&&d.tag==='w4_nemesis',rift=d&&d.tag==='w4_riftboss';_w4EnemyDeath(e);if(Math.random()<.085&&w4.medkits<6){w4.medkits++;toast(w4l(W4.medkit)+' +1','magic');}if(nem){w4.nemesisCycle=Math.floor(w4.contractsDone/3);state.gold+=350+w4.nemesisCycle*40;state.runes+=2;addXp(260+w4.nemesisCycle*35);for(var i=0;i<2;i++)spawnLoot(new THREE.Vector3((Math.random()-.5)*2,0,(Math.random()-.5)*2),i?3:2);toast(w4l(W4.nemesisDead),'legend');}if(rift){var tier=w4.riftTier;w4.riftCleared=true;w4.riftRuns++;w4.riftTier++;state.gold+=250+tier*55;state.steel+=4+Math.min(8,tier);state.runes+=1+(tier%4===0?1:0);addXp(180+tier*45);for(i=0;i<3;i++)spawnLoot(new THREE.Vector3(22+(Math.random()-.5)*3,0,22+(Math.random()-.5)*3),i===2?3:2);toast(w4l(W4.riffDone)+' T'+tier,'legend');}save();updateMission();};
var _w4Interact=interact;interact=function(){var q=nearestInteract();if(!q){w4KitUse();return;}if(q.type==='w4_board'){w4BoardInteract();return;}var chest=q.type==='chest'&&!q.used;_w4Interact();if(chest&&q.used&&w4.contract.active&&w4.contract.type===2){w4.contract.progress=Math.min(w4.contract.target,w4.contract.progress+1);if(Math.random()<.28){for(var i=0;i<3;i++){var a=i*Math.PI*2/3,xx=player.position.x+Math.cos(a)*4,zz=player.position.z+Math.sin(a)*4;if(!collides(xx,zz,.7))spawnEnemy(i%2,false,xx,zz);}toast('AMBUSH','rare');}save();updateMission();}};
var _w4UpdateMission=updateMission;updateMission=function(){_w4UpdateMission();if(!mission)return;var extra=w4.contract.active?w4ContractText():'';if(areaKey==='rift')extra=w4l(W4.riftObj)+' · T'+w4.riftTier+(w4.riftCleared?' ✓':'');if(extra)$('missionText').textContent+=' · '+extra;};
