/* GRIND & WELD v2.6 - multi-act campaign, richer items, visual inventory, enemy variants and stronger skill FX. */
if(!state.world6)state.world6={};
var w6=state.world6;
if(w6.a2==null)w6.a2=0;if(w6.a2done==null)w6.a2done=false;if(w6.a3==null)w6.a3=0;if(w6.a3done==null)w6.a3done=false;if(w6.runes==null)w6.runes=0;if(w6.bosses==null)w6.bosses=0;
var w6fx=[];
AREA_NAMES.ashworks=['Hamukohó','Ashworks','Aschewerk','Forja de Ceniza','Fonderie des Cendres','灰烬工坊','Forgia di Cenere','Forja de Cinzas','Popielna Kuźnia','Aswerk','Forja de Cenușă','Пепельная Кузня'];
AREA_NAMES.blackrail=['Fekete Síntelep','Black Rail Yard','Schwarzer Rangierbahnhof','Patio del Riel Negro','Dépôt du Rail Noir','黑轨货场','Scalo Ferro Nero','Pátio do Trilho Negro','Czarna Bocznica','Zwart Spooremplacement','Depoul Șinei Negre','Чёрная Сортировочная'];
var W6={
 a2:['II. felvonás · Hamukohó','Act II · Ashworks','Akt II · Aschewerk','Acto II · Forja de Ceniza','Acte II · Fonderie des Cendres','第二幕·灰烬工坊','Atto II · Forgia di Cenere','Ato II · Forja de Cinzas','Akt II · Popielna Kuźnia','Akte II · Aswerk','Actul II · Forja de Cenușă','Акт II · Пепельная Кузня'],
 a3:['III. felvonás · Fekete Síntelep','Act III · Black Rail Yard','Akt III · Schwarzer Rangierbahnhof','Acto III · Patio del Riel Negro','Acte III · Dépôt du Rail Noir','第三幕·黑轨货场','Atto III · Scalo Ferro Nero','Ato III · Pátio do Trilho Negro','Akt III · Czarna Bocznica','Akte III · Zwart Spooremplacement','Actul III · Depoul Șinei Negre','Акт III · Чёрная Сортировочная'],
 slag:['Salakpecsétek','Slag Seals','Schlackensiegel','Sellos de Escoria','Sceaux de Scorie','熔渣封印','Sigilli di Scoria','Selos de Escória','Pieczęcie Żużla','Slakzegels','Sigilii de Zgură','Шлаковые Печати'],
 sw:['Váltókapcsolók','Rail Switches','Weichenschalter','Cambios de Vía','Aiguillages','轨道开关','Scambi Ferroviari','Chaves de Trilho','Zwrotnice','Wissels','Macazuri','Стрелочные Переводы'],
 cinder:['Parázs Kolosszus','Cinder Colossus','Glutkoloss','Coloso de Ascua','Colosse de Braise','余烬巨像','Colosso di Brace','Colosso de Brasa','Koloss Żaru','Sintelkoloß','Colosul de Jar','Угольный Колосс'],
 rail:['Síntelep Zsarnoka','Rail Tyrant','Schienen-Tyrann','Tirano del Riel','Tyran du Rail','铁轨暴君','Tiranno dei Binari','Tirano do Trilho','Tyran Torów','Spoortiran','Tiranul Șinelor','Рельсовый Тиран'],
 done:['Felvonás teljesítve','Act completed','Akt abgeschlossen','Acto completado','Acte terminé','幕章完成','Atto completato','Ato concluído','Akt ukończony','Akte voltooid','Act finalizat','Акт завершён'],
 rune:['Rúnaszó','Rune Word','Runenwort','Palabra Rúnica','Mot Runique','符文之语','Parola Runica','Palavra Rúnica','Słowo Runiczne','Runewoord','Cuvânt Runic','Рунное Слово'],
 armory:['Felszerelés','Armory','Arsenal','Armería','Armurerie','军械库','Armeria','Arsenal','Zbrojownia','Wapenkamer','Armurărie','Арсенал'],
 rw:[['MŰHELY','WORKSHOP','WERKSTATT','TALLER','ATELIER','工坊','OFFICINA','OFICINA','WARSZTAT','WERKPLAATS','ATELIER','МАСТЕРСКАЯ'],['ÍVFÉNY','ARCFLASH','LICHTBOGEN','ARCO','ARC','弧光','ARCO','ARCO','ŁUK','BOOG','ARC','ДУГА'],['ACÉLSZÍV','STEELHEART','STAHLHERZ','CORAZÓN DE ACERO','CŒUR D’ACIER','钢铁之心','CUORE D’ACCIAIO','CORAÇÃO DE AÇO','STALOWE SERCE','STAALHART','INIMĂ DE OȚEL','СТАЛЬНОЕ СЕРДЦE']]
};
function w6l(a){return a[Math.max(0,Math.min(11,lang))]||a[1];}
function w6Status(){if(!w5.cryptDone)return w5Status();if(!w6.a2done)return w6l(W6.slag)+': '+w6.a2+'/4';if(!w6.a3done)return w6l(W6.sw)+': '+w6.a3+'/3';return w6l(W6.done)+' III';}
var _w6Make=makeItem;makeItem=function(t){var it=_w6Make(t);if(it.r>=1&&it.sockets==null&&Math.random()<.30)it.sockets=1+((Math.random()*(it.r>=3?3:2))|0);if(it.sockets&&it.r>=2&&it.rword==null&&Math.random()<.25){it.rword=(Math.random()*W6.rw.length)|0;it.power+=3+it.r;w6.runes++;}if(it.r>=3&&it.aspect==null)it.aspect=(Math.random()*4)|0;return it;};
var _w6Name=itemName;itemName=function(it){var n=_w6Name(it);if(it.rword!=null)n='«'+w6l(W6.rw[it.rword])+'» '+n;if(it.sockets)n+=' ['+it.sockets+'S]';if(it.aspect!=null)n+=' ✦';return n;};
var _w6Bonus=equippedBonus;equippedBonus=function(type){var b=_w6Bonus(type),it=w4ItemAt?w4ItemAt(type):null;if(it&&it.sockets)b+=it.sockets*2;if(it&&it.rword!=null)b+=4+(it.rword===1&&type==='weapon'?3:0)+(it.rword===2&&type==='armor'?3:0);if(it&&it.aspect!=null)b+=2;return b;};
function w6Style(){if($('w6css'))return;var s=document.createElement('style');s.id='w6css';s.textContent='.w6ico{display:inline-flex;position:relative;width:42px;height:42px;align-items:center;justify-content:center;margin-right:7px;border:2px solid #777;background:radial-gradient(circle,#2b2d2f,#101214 68%);border-radius:5px;vertical-align:middle;box-shadow:inset 0 0 8px #000,0 2px 8px #0009}.w6ico i{font-style:normal;font-size:22px;color:#ddd}.w6ico.magic{border-color:#3f89e8}.w6ico.rare{border-color:#a64bd8}.w6ico.legend{border-color:#d9a931}.w6ico em{position:absolute;right:2px;bottom:1px;font-size:9px;color:#ffe08a}.w6act{border:1px solid #725427;padding:8px;margin-top:7px;border-radius:6px;background:linear-gradient(#211810,#0e0b08)}.w6act b{color:#e0b35d}.w6rune{color:#7fc7ff}.w6eq{display:flex;align-items:center;min-height:50px}';document.head.appendChild(s);}
function w6Icon(it){var k=it.slot==='weapon'?'⚒':'⬟';return '<span class="w6ico '+(rarityNames[it.r]||'common')+'"><i>'+k+'</i>'+(it.sockets?'<em>'+it.sockets+'</em>':'')+'</span>';}
var _w6Draw=renderDrawer;renderDrawer=function(){w6Style();_w6Draw();var d=$('drawer'),rows=d?d.querySelectorAll('.slot'):[];for(var i=0;i<state.inventory.length&&i<rows.length;i++){var it=state.inventory[i];rows[i].classList.add('w6eq');rows[i].innerHTML=w6Icon(it)+'<span>'+rows[i].innerHTML+(it.rword!=null?'<br><span class="w6rune">'+w6l(W6.rune)+': '+w6l(W6.rw[it.rword])+'</span>':'')+'</span>';}if(d){var q=document.createElement('div');q.className='w6act';q.innerHTML='<b>'+w6l(W6.armory)+'</b><br>'+w6Status();d.appendChild(q);}};
var _w6RW=renderWorkshop;renderWorkshop=function(){w6Style();_w6RW();var z=$('zones');if(z){var a=document.createElement('div');a.className='w6act';a.innerHTML='<b>'+(w6.a2done?'✓ ':'')+w6l(W6.a2)+'</b><br>'+w6l(W6.slag)+' '+w6.a2+'/4 · '+(w5.cryptDone?'OPEN':T.locked);z.appendChild(a);var b=document.createElement('div');b.className='w6act';b.innerHTML='<b>'+(w6.a3done?'✓ ':'')+w6l(W6.a3)+'</b><br>'+w6l(W6.sw)+' '+w6.a3+'/3 · '+(w6.a2done?'OPEN':T.locked);z.appendChild(b);}var r=$('resourceBox');if(r)r.innerHTML+='<br><span class="w6rune">'+w6l(W6.rune)+': '+w6.runes+'</span>';};
function w6Node(type,x,z,color,label){var g=new THREE.Group();addTo(g,cyl(.42,.5,.55,0x4d4740,0,.27,0,.75,10));var o=addTo(g,sphere(.16,color,0,.72,0,.1,10));o.material=new THREE.MeshBasicMaterial({color:color});g.position.set(x,0,z);root.add(g);interactables.push({type:type,g:g,x:x,z:z,used:false});campaignBeacon(x,z,color,label);}
function buildAshworks(){areaKey='ashworks';zoneIndex=4;scene.background.set(0x100806);scene.fog.color.copy(scene.background);dungeonShell(76,66);areaEntry={x:0,z:-29};campaignReturn(0,-29,-4,-35);campaignRoad(0,0,70,10,0x342a25);campaignRoad(0,0,10,60,0x342a25);for(var i=-28;i<=28;i+=14){weldingTable(i,-14);barrel(i,14,0x763225);crate(i+3,21,1.2);lamp(i,-24,0xff7a39);}for(i=0;i<6;i++){var a=i*Math.PI/3,x=Math.cos(a)*23,z=Math.sin(a)*20;addObstacle(x,z,4,4,2.4,0x5a4034,'wall');}chest(-31,25);chest(31,25);chest(-31,-23);chest(31,-23);if(!w6.a2done){var p=[[-25,-4],[-8,22],[13,-18],[28,8]];for(i=w6.a2;i<4;i++)w6Node('w6slag',p[i][0],p[i][1],0xff8c42,w6l(W6.slag));if(w6.a2>=4&&!bossSpawned){spawnEnemy(4,true,0,25);var e=enemies[enemies.length-1];e.userData.e.tag='cinder';e.scale.setScalar(1.55);bossSpawned=true;toast(w6l(W6.cinder),'legend');}}spawnAmbient(22);}
function buildBlackRail(){areaKey='blackrail';zoneIndex=5;scene.background.set(0x070b0e);scene.fog.color.copy(scene.background);dungeonShell(86,60);areaEntry={x:-36,z:-24};campaignReturn(-36,-24,4,-35);for(var r=-18;r<=18;r+=12){campaignRoad(0,r,80,2.2,0x25292b);for(var x=-34;x<=34;x+=17)root.add(box(6,.08,.55,0x5a4430,x,.04,r,.15));}for(var i=0;i<9;i++){cableDrum(-30+i*8,-8+(i%3)*8);crate(-25+i*6,24-(i%2)*6,1.1);}lamp(-34,22,0x69a8d5);lamp(0,22,0xff9147);lamp(34,22,0x69a8d5);chest(35,-20);chest(-5,24);if(!w6.a3done){var p=[[-22,-18],[0,18],[24,-6]];for(i=w6.a3;i<3;i++)w6Node('w6switch',p[i][0],p[i][1],0x6bb7e5,w6l(W6.sw));if(w6.a3>=3&&!bossSpawned){spawnEnemy(4,true,31,21);var e=enemies[enemies.length-1];e.userData.e.tag='railtyrant';e.scale.setScalar(1.62);bossSpawned=true;toast(w6l(W6.rail),'legend');}}spawnAmbient(24);}
var _w6BA=buildArea;buildArea=function(k,x,z){if(k==='ashworks'){clearWorld();matCache={};questBeacons=[];bossSpawned=false;buildAshworks();player=makeHumanoid(clsIndex(),false);player.position.set(x!=null?x:areaEntry.x,0,z!=null?z:areaEntry.z);root.add(player);playerParts=player.userData.parts;updateMission();save();return;}if(k==='blackrail'){clearWorld();matCache={};questBeacons=[];bossSpawned=false;buildBlackRail();player=makeHumanoid(clsIndex(),false);player.position.set(x!=null?x:areaEntry.x,0,z!=null?z:areaEntry.z);root.add(player);playerParts=player.userData.parts;updateMission();save();return;}_w6BA(k,x,z);if(k==='surface'){if(w5.cryptDone)campaignPortal(-18,-42,'ashworks');if(w6.a2done)campaignPortal(18,-42,'blackrail');}};
var _w6PU=portalUnlocked;portalUnlocked=function(t){if(t==='ashworks')return !!w5.cryptDone;if(t==='blackrail')return !!w6.a2done;return _w6PU(t);};
var _w6I=interact;interact=function(){var q=nearestInteract();if(!q){_w6I();return;}if(q.type==='w6slag'){q.used=true;w6.a2=Math.min(4,w6.a2+1);spawnSparks(q.g.position,0xff8c42,20);root.remove(q.g);toast(w6l(W6.slag)+' '+w6.a2+'/4','magic');if(w6.a2>=4&&!bossSpawned){spawnEnemy(4,true,0,25);var e=enemies[enemies.length-1];e.userData.e.tag='cinder';e.scale.setScalar(1.55);bossSpawned=true;}save();updateMission();return;}if(q.type==='w6switch'){q.used=true;w6.a3=Math.min(3,w6.a3+1);spawnSparks(q.g.position,0x6bb7e5,20);root.remove(q.g);toast(w6l(W6.sw)+' '+w6.a3+'/3','magic');if(w6.a3>=3&&!bossSpawned){spawnEnemy(4,true,31,21);var e2=enemies[enemies.length-1];e2.userData.e.tag='railtyrant';e2.scale.setScalar(1.62);bossSpawned=true;}save();updateMission();return;}_w6I();};
var _w6ED=enemyDeath;enemyDeath=function(e){var d=e&&e.userData?e.userData.e||{}:{},c=d.tag==='cinder',r=d.tag==='railtyrant';_w6ED(e);if(c&&!w6.a2done){w6.a2done=true;w6.bosses++;state.gold+=380;state.steel+=10;state.runes+=2;addXp(520);for(var i=0;i<3;i++)spawnLoot(new THREE.Vector3((Math.random()-.5)*4,0,25+(Math.random()-.5)*3),i===2?3:2);toast(w6l(W6.done)+' II','legend');openExtraction();save();}if(r&&!w6.a3done){w6.a3done=true;w6.bosses++;state.gold+=520;state.steel+=12;state.runes+=3;addXp(720);for(var j=0;j<4;j++)spawnLoot(new THREE.Vector3(31+(Math.random()-.5)*4,0,21+(Math.random()-.5)*3),j>=2?3:2);toast(w6l(W6.done)+' III','legend');openExtraction();save();}};
var _w6UM=updateMission;updateMission=function(){_w6UM();if(!mission)return;if(areaKey==='ashworks'){$('missionTitle').textContent=T.mission+': '+w6l(W6.a2);$('missionText').textContent=w6.a2done?w6l(W6.done):(w6l(W6.slag)+' '+w6.a2+'/4'+(w6.a2>=4?' · '+w6l(W6.cinder):''));}else if(areaKey==='blackrail'){$('missionTitle').textContent=T.mission+': '+w6l(W6.a3);$('missionText').textContent=w6.a3done?w6l(W6.done):(w6l(W6.sw)+' '+w6.a3+'/3'+(w6.a3>=3?' · '+w6l(W6.rail):''));}};
var _w6SE=spawnEnemy;spawnEnemy=function(k,b,x,z){_w6SE(k,b,x,z);var e=enemies[enemies.length-1];if(!e||b)return;var d=e.userData.e||{};if(Math.random()<.22){d.variant=(Math.random()*3)|0;if(d.variant===0){var s=new THREE.Mesh(new THREE.TorusGeometry(.31,.08,6,14),new THREE.MeshStandardMaterial({color:0xaab0b2,metalness:.85,roughness:.35}));s.position.set(.58,1.2,0);s.rotation.y=Math.PI/2;e.add(s);d.saw=s;}else if(d.variant===1){var c=cyl(.18,.18,.55,0x6b8ca2,.55,1.25,0,.75,10);c.rotation.z=Math.PI/2;e.add(c);d.coil=c;}else e.add(box(.92,.12,.52,0x684c32,0,1.72,0,.7));if(Math.random()<.16){d.champion=true;d.hp*=1.7;d.max=d.hp;d.damage*=1.25;var a=new THREE.Mesh(new THREE.TorusGeometry(.72,.055,7,22),new THREE.MeshBasicMaterial({color:0xffb04a,transparent:true,opacity:.7}));a.rotation.x=Math.PI/2;a.position.y=.06;e.add(a);d.aura=a;}}};
function w6Ring(pos,color,r0,r1,life){var m=new THREE.Mesh(new THREE.RingGeometry(r0,r1,28),new THREE.MeshBasicMaterial({color:color,transparent:true,opacity:.82,side:THREE.DoubleSide,depthWrite:false}));m.rotation.x=-Math.PI/2;m.position.copy(pos);m.position.y=.08;root.add(m);w6fx.push({m:m,life:life,max:life,grow:2.6});}
var _w6Atk=attack;attack=function(){if(mission&&attackCd<=0&&player)w6Ring(player.position.clone(),0xffa94f,.55,.72,.28);return _w6Atk();};
var _w6S1=skill1;skill1=function(){if(mission&&s1Cd<=0&&player)w6Ring(player.position.clone(),clsIndex()===1?0x63c9ff:clsIndex()===2?0x9f8dff:0xff9a47,.7,1.0,.55);return _w6S1();};
var _w6S2=skill2;skill2=function(){if(mission&&s2Cd<=0&&player){var p=player.position.clone(),c=clsIndex()===0?0xffce67:clsIndex()===1?0xaeeeff:0xa58cff;for(var i=0;i<3;i++)setTimeout((function(i,p,c){return function(){if(root)w6Ring(p, c,1+i*.55,1.18+i*.55,.65);};})(i,p,c),i*70);}return _w6S2();};
var _w6Dash=dash;dash=function(){if(mission&&dashCd<=0&&player)w6Ring(player.position.clone(),0x86b4cf,.3,.48,.32);return _w6Dash();};
var _w6Up=update;update=function(dt){_w6Up(dt);for(var i=w6fx.length-1;i>=0;i--){var f=w6fx[i];f.life-=dt;f.m.scale.multiplyScalar(1+dt*f.grow);if(f.m.material)f.m.material.opacity=Math.max(0,f.life/f.max*.82);if(f.life<=0){try{root.remove(f.m);disposeObject(f.m);}catch(e){}w6fx.splice(i,1);}}for(i=0;i<enemies.length;i++){var d=enemies[i].userData.e||{};if(d.saw)d.saw.rotation.z+=dt*9;if(d.coil)d.coil.rotation.x+=dt*3;if(d.aura){d.aura.rotation.z+=dt;d.aura.material.opacity=.48+Math.sin(time*4+i)*.16;}}};
var _w6RF=w5Refresh;w5Refresh=function(){_w6RF();if($('w5Lore'))$('w5Lore').innerHTML=w5l(W5.lore)+'<br><span class="w6rune">'+w6l(W6.a2)+(w6.a2done?' ✓':'')+'</span><br><span class="w6rune">'+w6l(W6.a3)+(w6.a3done?' ✓':'')+'</span>';};
save();
