/* GRIND & WELD v2.3: Diablo-like deep world systems - NPC services, elite bounty, affix loot, shrines and multi-floor dungeon. */
if(!state.world3)state.world3={};
var w3=state.world3;
if(!w3.bounty)w3.bounty={accepted:false,kills:0,done:false,rewarded:false};
if(w3.deepKey==null)w3.deepKey=false;
if(w3.relays==null)w3.relays=0;
if(w3.seals==null)w3.seals=0;
if(w3.deepCleared==null)w3.deepCleared=false;
if(w3.reforges==null)w3.reforges=0;
if(!w3.shrines)w3.shrines={};
if(!w3.blessing)w3.blessing={type:-1,end:0};
if(!state.world2.waypoints.vault2)state.world2.waypoints.vault2=false;
if(!state.world2.waypoints.vault3)state.world2.waypoints.vault3=false;
AREA_NAMES.vault2=['Bontókamra mélyszint','Salvage Vault Depths','Schrottgewölbe-Tiefen','Profundidades de la Bóveda','Profondeurs du Caveau','回收密库深层','Profondità della Cripta','Profundezas do Cofre','Głębia Skarbca','Diepten van de Schrootkluis','Adâncurile Seifului','Глубины Хранилища'];
AREA_NAMES.vault3=['Őskohó szentély','Ancient Forge Sanctum','Uralte Schmiede','Santuario de la Forja','Sanctuaire de la Forge','远古熔炉圣所','Santuario della Forgia','Santuário da Forja','Sanktuarium Kuźni','Heiligdom van de Smidse','Sanctuarul Forjei','Святилище древней кузни'];
var W3={
scout:['Kelemen felderítő','Scout Kelemen','Späher Kelemen','Explorador Kelemen','Éclaireur Kelemen','侦察员凯莱门','Esploratore Kelemen','Batedor Kelemen','Zwiadowca Kelemen','Verkenner Kelemen','Cercetașul Kelemen','Разведчик Келемен'],
smith:['Ilona kovácsmester','Master Smith Ilona','Schmiedemeisterin Ilona','Maestra herrera Ilona','Maître forgeron Ilona','锻造大师伊洛娜','Maestra fabbra Ilona','Mestra ferreira Ilona','Mistrzyni kowalstwa Ilona','Meestersmid Ilona','Maestra fierar Ilona','Мастер-кузнец Илона'],
bounty:['Elitvadászat','Elite Hunt','Elitejagd','Caza de élites','Chasse aux élites','精英猎杀','Caccia agli élite','Caça de elites','Polowanie na elitę','Elitejacht','Vânătoare de elite','Охота на элиту'],
bountyAsk:['Ölj meg 5 elit ellenfelet. A jutalom egy kulcs a Bontókamra mélyszintjéhez.','Kill 5 elite enemies. The reward is a key to the Salvage Vault Depths.','Besiege 5 Elitegegner. Als Belohnung erhältst du den Schlüssel zu den Tiefen.','Derrota a 5 enemigos élite. La recompensa abre las profundidades.','Éliminez 5 ennemis élite. La récompense ouvre les profondeurs.','击败5名精英敌人，奖励可开启密库深层。','Sconfiggi 5 nemici élite. La ricompensa apre le profondità.','Derrote 5 inimigos elite. A recompensa abre as profundezas.','Pokonaj 5 elitarnych wrogów. Nagroda otwiera głębię.','Versla 5 elitevijanden. De beloning opent de diepten.','Învinge 5 inamici elită. Recompensa deschide adâncurile.','Уничтожьте 5 элитных врагов. Награда откроет глубины.'],
accepted:['Elitvadászat felvéve','Elite Hunt accepted','Elitejagd angenommen','Caza aceptada','Chasse acceptée','已接受精英猎杀','Caccia accettata','Caça aceita','Polowanie przyjęte','Elitejacht aangenomen','Vânătoare acceptată','Охота принята'],
key:['Mélyszint kulcs megszerezve','Depth Key acquired','Tiefenschlüssel erhalten','Llave de profundidad obtenida','Clé des profondeurs obtenue','已获得深层钥匙','Chiave delle profondità ottenuta','Chave das profundezas obtida','Zdobyto klucz głębi','Dieptesleutel verkregen','Cheia adâncurilor obținută','Ключ глубин получен'],
reforge:['Újrakovácsolás','Reforge','Neu schmieden','Reforjar','Reforger','重铸','Riforgia','Reforjar','Przekuj','Hersmeden','Reforjare','Перековка'],
noItem:['Nincs felszerelt tárgy','No equipped item','Kein Gegenstand ausgerüstet','No hay objeto equipado','Aucun objet équipé','未装备物品','Nessun oggetto equipaggiato','Nenhum item equipado','Brak założonego przedmiotu','Geen item uitgerust','Niciun obiect echipat','Нет экипированного предмета'],
relay:['Biztonsági relé','Security relay','Sicherheitsrelais','Relé de seguridad','Relais de sécurité','安全继电器','Relè di sicurezza','Relé de segurança','Przekaźnik bezpieczeństwa','Veiligheidsrelais','Releu de siguranță','Защитное реле'],
seal:['Kohópecsét','Forge seal','Schmiedesiegel','Sello de forja','Sceau de forge','熔炉封印','Sigillo della forgia','Selo da forja','Pieczęć kuźni','Smederijzegel','Sigiliul forjei','Печать кузни'],
deepBoss:['Őskohó Gépúr','Ancient Forge Overlord','Uralter Schmiede-Fürst','Señor de la Forja Antigua','Seigneur de la Forge Antique','远古熔炉霸主','Signore della Forgia Antica','Senhor da Forja Antiga','Władca Starej Kuźni','Heer van de Oude Smidse','Stăpânul Forjei Vechi','Владыка древней кузни'],
deepDone:['Őskohó megtisztítva','Ancient Forge cleared','Uralte Schmiede gesäubert','Forja Antigua despejada','Forge Antique purifiée','远古熔炉已清理','Forgia Antica ripulita','Forja Antiga limpa','Stara Kuźnia oczyszczona','Oude Smidse gezuiverd','Forja Veche curățată','Древняя кузня очищена'],
shrine:['Műhelyszentély','Workshop shrine','Werkstattschrein','Santuario del taller','Sanctuaire d’atelier','工坊圣坛','Santuario d’officina','Santuário da oficina','Kapliczka warsztatu','Werkplaatsschrijn','Altar de atelier','Святилище мастерской'],
fury:['Túlhajtás','Overdrive','Übersteuerung','Sobrecarga','Surrégime','超载','Sovraccarico','Sobrecarga','Przeciążenie','Overdrive','Supraturare','Форсаж'],
guard:['Megerősítés','Reinforcement','Verstärkung','Refuerzo','Renforcement','强化','Rinforzo','Reforço','Wzmocnienie','Versterking','Întărire','Укрепление'],
haste:['Gyorsjárat','Quickstep','Schnellgang','Paso rápido','Pas rapide','疾行','Passo rapido','Passo rápido','Szybki krok','Snelle stap','Pas rapid','Быстрый ход'],
eliteAff:[['Olvadó','Molten','Glühend','Fundido','En fusion','熔火','Fuso','Fundido','Stopiony','Gesmolten','Topit','Расплавленный'],['Ívkisüléses','Arc-charged','Lichtbogen','Carga de arco','Chargé d’arc','电弧充能','Carica d’arco','Carga de arco','Łukowy','Booggeladen','Încărcat cu arc','Дуговой'],['Vámpirikus','Vampiric','Vampirisch','Vampírico','Vampirique','吸血','Vampirico','Vampírico','Wampiryczny','Vampirisch','Vampiric','Вампирический'],['Pajzsolt','Shielded','Geschirmt','Escudado','Protégé','护盾','Schermato','Blindado','Osłonięty','Afgeschermd','Ecranat','Щитовой'],['Őrjöngő','Frenzied','Rasend','Frenético','Frénétique','狂暴','Frenetico','Frenético','Szałowy','Razend','Frenetic','Яростный']],
itemAff:[['Edzett','Tempered','Gehärtet','Templado','Trempé','淬火','Temprato','Temperado','Hartowany','Gehard','Călit','Закалённый'],['Megerősített','Reinforced','Verstärkt','Reforzado','Renforcé','强化','Rinforzato','Reforçado','Wzmocniony','Versterkt','Întărit','Усиленный'],['Töltött','Charged','Geladen','Cargado','Chargé','充能','Caricato','Carregado','Naładowany','Geladen','Încărcat','Заряженный'],['Mesteri','Masterwork','Meisterlich','Magistral','Chef-d’œuvre','大师级','Magistrale','Obra-prima','Mistrzowski','Meesterwerk','Măiestrit','Мастерский']]};
function w3l(a){return a[Math.max(0,Math.min(11,lang))]||a[1];}
function w3Npc(x,z,kind){var g=makeHumanoid(kind==='smith'?0:1,false);g.scale.setScalar(.94);g.position.set(x,0,z);g.rotation.y=Math.PI*.55;root.add(g);var col=kind==='smith'?0xe28743:0x76c9d8,ring=new THREE.Mesh(new THREE.TorusGeometry(.74,.06,7,24),new THREE.MeshBasicMaterial({color:col,transparent:true,opacity:.9}));ring.rotation.x=Math.PI/2;ring.position.y=.08;g.add(ring);interactables.push({type:'npc_'+kind,g:g,x:x,z:z,used:false});campaignBeacon(x,z,col,w3l(kind==='smith'?W3.smith:W3.scout));}
function w3Scout(){var b=w3.bounty;if(!b.accepted){b.accepted=true;b.kills=0;toast(w3l(W3.accepted),'magic');save();updateMission();return;}if(!b.done&&b.kills>=5){b.done=true;w3.deepKey=true;state.gold+=220;state.steel+=5;addXp(190);toast(w3l(W3.key),'legend');save();updateMission();return;}toast(w3l(W3.bounty)+': '+Math.min(5,b.kills)+'/5','magic');}
function w3Smith(){if(state.equipped<0||!state.inventory[state.equipped]){toast(w3l(W3.noItem),'rare');return;}if(state.gold<100){toast(T.nores,'rare');return;}var it=state.inventory[state.equipped];state.gold-=100;it.power=Math.min(99,(it.power||1)+1);if(it.mod==null)it.mod=(Math.random()*4)|0;else if(Math.random()<.35)it.mod=(it.mod+1)%4;w3.reforges++;spawnSparks(player?player.position:new THREE.Vector3(),0xffa54a,20);toast(w3l(W3.reforge)+' +1','legend');save();updateHud();}
function w3Shrine(x,z,type){var used=!!w3.shrines[areaKey+'_'+type],col=type===0?0xe35437:type===1?0x72a9ff:0x7be0a4,g=new THREE.Group();addTo(g,cyl(.68,.82,.42,0x3d4245,0,.21,0,.7,10));var orb=sphere(.22,used?0x596064:col,0,.82,0,.1,12);orb.material=new THREE.MeshBasicMaterial({color:used?0x596064:col});g.add(orb);g.position.set(x,0,z);root.add(g);interactables.push({type:'w3_shrine',g:g,x:x,z:z,shrine:type,used:used});campaignBeacon(x,z,col,w3l(W3.shrine));}
function w3UseShrine(q){var key=areaKey+'_'+q.shrine;if(w3.shrines[key])return;w3.shrines[key]=1;w3.blessing={type:q.shrine,end:time+90};q.used=true;hp=maxHp;en=maxEn;spawnSparks(q.g.position,q.shrine===0?0xe35437:q.shrine===1?0x72a9ff:0x7be0a4,30);toast(w3l(q.shrine===0?W3.fury:q.shrine===1?W3.guard:W3.haste)+' · 90s','legend');save();}
function w3Stairs(x,z,target,label,col){var g=new THREE.Group();for(var i=0;i<4;i++)addTo(g,box(2.3,.18,1.0,0x454b4f,0,.09+i*.12,i*.42,.7));var r=new THREE.Mesh(new THREE.TorusGeometry(.62,.06,8,24),new THREE.MeshBasicMaterial({color:col||0x6ccbe7,transparent:true,opacity:.85}));r.rotation.x=Math.PI/2;r.position.set(0,.75,1.15);g.add(r);g.position.set(x,0,z);root.add(g);interactables.push({type:'w3_stairs',g:g,x:x,z:z,target:target,used:false});campaignBeacon(x,z,col||0x6ccbe7,label||l(AREA_NAMES[target]));}
function w3Relay(x,z){var g=new THREE.Group();addTo(g,box(.72,.9,.72,0x444c50,0,.45,0,.75));var c=sphere(.14,0xff9b4b,0,1.02,0,.1,10);c.material=new THREE.MeshBasicMaterial({color:0xff9b4b});g.add(c);g.position.set(x,0,z);root.add(g);interactables.push({type:'w3_relay',g:g,x:x,z:z,used:false});campaignBeacon(x,z,0xff9b4b,w3l(W3.relay));}
function w3Seal(x,z){var g=new THREE.Group();addTo(g,cyl(.6,.75,.38,0x4d4140,0,.19,0,.7,10));var c=sphere(.17,0xe65b50,0,.7,0,.1,10);c.material=new THREE.MeshBasicMaterial({color:0xe65b50});g.add(c);g.position.set(x,0,z);root.add(g);interactables.push({type:'w3_seal',g:g,x:x,z:z,used:false});campaignBeacon(x,z,0xe65b50,w3l(W3.seal));}
function w3BuildVault2(){areaKey='vault2';zoneIndex=3;setCampaignBounds(-34,34,-34,34);areaEntry={x:-28,z:-28};scene.background.set(0x080909);scene.fog.color.copy(scene.background);campaignGround();campaignBoundary();campaignReturn(-29,-29,-37,20);w2Waypoint(-26,-26,'vault2');campaignRoad(0,0,7,60,0x252729);campaignRoad(0,0,60,7,0x252729);for(var i=-24;i<=24;i+=12){addObstacle(i,-12,7,2,2.4,0x493f39,'wall');addObstacle(i,12,7,2,2.4,0x493f39,'wall');}for(i=-18;i<=18;i+=12){crate(i,-21,1.05);barrel(i+3,20,0x6a3528);lamp(i,4,i%24?0xff8844:0x65b8e6);}chest(-22,21);chest(22,-20);var rs=[[-18,-5],[5,18],[20,3]],p=Math.max(0,Math.min(3,w3.relays||0));for(i=p;i<3;i++)w3Relay(rs[i][0],rs[i][1]);if(p>=3)w3Stairs(27,27,'vault3',l(AREA_NAMES.vault3),0xd88948);w3Shrine(-7,25,1);spawnAmbient(20);}
function w3BuildVault3(){areaKey='vault3';zoneIndex=4;setCampaignBounds(-36,36,-36,36);areaEntry={x:-29,z:-29};scene.background.set(0x100807);scene.fog.color.copy(scene.background);campaignGround();campaignBoundary();campaignRoad(0,0,10,64,0x2c2524);campaignRoad(0,0,64,10,0x2c2524);w2Waypoint(-27,-27,'vault3');w3Stairs(-30,-30,'vault2',l(AREA_NAMES.vault2),0x6ccbe7);for(var a=0;a<8;a++){var ang=a*Math.PI/4,x=Math.cos(ang)*23,z=Math.sin(ang)*23;addObstacle(x,z,3.2,3.2,3.2,0x55403a,'pillar');lamp(x*.78,z*.78,a%2?0xff6a3d:0xe4a451);}var ss=[[-18,0],[18,0],[0,-18],[0,18]],p=Math.max(0,Math.min(4,w3.seals||0));for(var i=p;i<4;i++)w3Seal(ss[i][0],ss[i][1]);if(p>=4&&!w3.deepCleared){spawnEnemy(4,true,0,0);var e=enemies[enemies.length-1];e.scale.setScalar(1.55);e.userData.e.tag='deepmaster';e.userData.e.hp=Math.round(e.userData.e.hp*1.8);e.userData.e.max=e.userData.e.hp;toast(T.boss+': '+w3l(W3.deepBoss),'legend');}w3Shrine(-23,19,0);spawnAmbient(18);}
var _w3W2BuildVault=w2BuildVault;w2BuildVault=function(){_w3W2BuildVault();w3Shrine(12,-18,2);if(w3.deepKey)w3Stairs(24,-22,'vault2',l(AREA_NAMES.vault2),0xd88948);};
var _w3BuildSurface=buildSurface;buildSurface=function(){_w3BuildSurface();w3Npc(-30,-34,'scout');w3Npc(-25,-34,'smith');w3Shrine(-20,-34,2);};
var _w3BuildArea=buildArea;buildArea=function(key,spawnX,spawnZ){if(key!=='vault2'&&key!=='vault3'){_w3BuildArea(key,spawnX,spawnZ);return;}clearWorld();matCache={};questBeacons=[];areaKey=key;bossSpawned=false;if(key==='vault2')w3BuildVault2();else w3BuildVault3();player=makeHumanoid(clsIndex(),false);player.position.set(spawnX!=null?spawnX:areaEntry.x,0,spawnZ!=null?spawnZ:areaEntry.z);root.add(player);playerParts=player.userData.parts;state.world2.lastArea=key;w2Reveal();updateMission();save();};
var _w3PortalUnlocked=portalUnlocked;portalUnlocked=function(t){if(t==='vault2')return !!w3.deepKey;if(t==='vault3')return w3.relays>=3;return _w3PortalUnlocked(t);};
var _w3UnlockedWp=w2UnlockedWaypointKeys;w2UnlockedWaypointKeys=function(){var a=_w3UnlockedWp();if(state.world2.waypoints.vault2)a.push('vault2');if(state.world2.waypoints.vault3)a.push('vault3');return a;};
var _w3MakeItem=makeItem;makeItem=function(tier){var it=_w3MakeItem(tier);if(it.mod==null&&it.r>=1)it.mod=(Math.random()*4)|0;if(it.r===3&&Math.random()<.72)it.mod2=((it.mod||0)+1+((Math.random()*3)|0))%4;return it;};
var _w3ItemName=itemName;itemName=function(it){var s=_w3ItemName(it);if(it.mod!=null)s=w3l(W3.itemAff[it.mod%4])+' '+s;if(it.mod2!=null)s+=' · '+w3l(W3.itemAff[it.mod2%4]);return s;};
var _w3EqBonus=equippedBonus;equippedBonus=function(type){var b=_w3EqBonus(type),it=state.equipped>=0?state.inventory[state.equipped]:null;if(it&&it.slot===type){if(it.mod===0||it.mod2===0)b+=2;if(type==='armor'&&(it.mod===1||it.mod2===1))b+=3;if(type==='weapon'&&(it.mod===2||it.mod2===2))b+=3;if(it.mod===3||it.mod2===3)b+=Math.max(1,(it.r||0));}if(w3.blessing&&w3.blessing.end>time){if(type==='weapon'&&w3.blessing.type===0)b+=4;if(type==='armor'&&w3.blessing.type===1)b+=4;}return b;};
var _w3PlayerStats=playerStats;playerStats=function(){var c=_w3PlayerStats();if(w3.blessing&&w3.blessing.end>time&&w3.blessing.type===2)return {id:c.id,hp:c.hp,en:c.en,speed:c.speed*1.18,damage:c.damage,color:c.color};return c;};
var _w3UpgradeElite=w2UpgradeElite;w2UpgradeElite=function(e,index){_w3UpgradeElite(e,index);if(!e||!e.userData||!e.userData.e)return;var d=e.userData.e;if(d.affix==null)d.affix=(index+state.level+zoneIndex)%5;d.affixCd=.7+Math.random()*1.2;var col=[0xf05a32,0x62c8f0,0xc34e73,0x719cff,0xe2b34b][d.affix],o=sphere(.11,col,0,1.65,0,.1,8);o.material=new THREE.MeshBasicMaterial({color:col});o.name='affixOrb';e.add(o);if(d.affix===3)d.shield=2+(d.eliteRank||1);if(d.affix===4){d.speed*=1.18;d.damage=Math.round(d.damage*1.12);}};
var _w3DamageEnemy=damageEnemy;damageEnemy=function(e,dmg){var d=e&&e.userData&&e.userData.e;if(d&&d.elite&&d.affix===3&&d.shield>0){d.shield--;dmg*=.42;spawnSparks(e.position,0x719cff,10);}return _w3DamageEnemy(e,dmg);};
var _w3EnemyDeath=enemyDeath;enemyDeath=function(e){var d=e&&e.userData?e.userData.e:null;if(d&&d.elite&&w3.bounty.accepted&&!w3.bounty.done)w3.bounty.kills=Math.min(5,w3.bounty.kills+1);var deep=d&&d.tag==='deepmaster';_w3EnemyDeath(e);if(deep){w3.deepCleared=true;state.gold+=600;state.steel+=12;state.runes+=4;addXp(650);toast(w3l(W3.deepDone),'legend');for(var i=0;i<3;i++){var p=new THREE.Vector3((Math.random()-.5)*3,0,(Math.random()-.5)*3);spawnLoot(p,i===2?3:2);}save();}updateMission();};
var _w3Interact=interact;interact=function(){var q=nearestInteract();if(!q)return;if(q.type==='npc_scout'){w3Scout();return;}if(q.type==='npc_smith'){w3Smith();return;}if(q.type==='w3_shrine'){w3UseShrine(q);return;}if(q.type==='w3_stairs'){if(!portalUnlocked(q.target)){toast(T.locked,'rare');return;}buildArea(q.target);toast(l(AREA_NAMES[q.target]),'magic');return;}if(q.type==='w3_relay'){q.used=true;w3.relays=Math.min(3,w3.relays+1);spawnSparks(q.g.position,0xff9b4b,22);toast(w3l(W3.relay)+': '+w3.relays+'/3','rare');if(w3.relays>=3)w3Stairs(27,27,'vault3',l(AREA_NAMES.vault3),0xd88948);save();updateMission();return;}if(q.type==='w3_seal'){q.used=true;w3.seals=Math.min(4,w3.seals+1);spawnSparks(q.g.position,0xe65b50,25);toast(w3l(W3.seal)+': '+w3.seals+'/4','rare');if(w3.seals>=4&&!w3.deepCleared){spawnEnemy(4,true,0,0);var e=enemies[enemies.length-1];e.scale.setScalar(1.55);e.userData.e.tag='deepmaster';e.userData.e.hp=Math.round(e.userData.e.hp*1.8);e.userData.e.max=e.userData.e.hp;toast(T.boss+': '+w3l(W3.deepBoss),'legend');}save();updateMission();return;}_w3Interact();};
var _w3Update=update;update=function(dt){_w3Update(dt);if(!mission||!player)return;w2Reveal();if(w3.blessing&&w3.blessing.end<=time)w3.blessing={type:-1,end:0};for(var i=0;i<enemies.length;i++){var e=enemies[i],d=e.userData&&e.userData.e;if(!d||!d.elite)continue;d.affixCd=(d.affixCd||0)-dt;if(d.affixCd>0)continue;var dist=e.position.distanceTo(player.position);if(d.affix===0){d.affixCd=1.15;if(dist<2.35){playerHit(7+state.level*.8,e);spawnSparks(e.position,0xf05a32,9);}}else if(d.affix===1){d.affixCd=1.65;if(dist<5.5){playerHit(5+state.level*.7,e);spawnSparks(player.position,0x62c8f0,8);}}else if(d.affix===2){d.affixCd=1.4;if(dist<3.0){d.hp=Math.min(d.max,d.hp+Math.max(2,d.max*.035));spawnSparks(e.position,0xc34e73,5);}}else d.affixCd=2.0;}};
var _w3UpdateMission=updateMission;updateMission=function(){_w3UpdateMission();if(!mission)return;var extra='';if(areaKey==='vault2')extra=w3l(W3.relay)+': '+w3.relays+'/3';else if(areaKey==='vault3')extra=w3.deepCleared?w3l(W3.deepDone):w3l(W3.seal)+': '+w3.seals+'/4';else if(w3.bounty.accepted&&!w3.bounty.done)extra=w3l(W3.bounty)+': '+Math.min(5,w3.bounty.kills)+'/5';if(extra)$('missionText').textContent+=' · '+extra;};
var _w3RenderWorkshop=renderWorkshop;renderWorkshop=function(){_w3RenderWorkshop();var r=$('resourceBox');if(r){var b=w3.bounty.accepted?(w3.bounty.done?'✓':Math.min(5,w3.bounty.kills)+'/5'):'-';r.innerHTML+='<br><span class="eq">'+w3l(W3.bounty)+': '+b+' · '+(w3.deepKey?'KEY ✓':'KEY -')+(w3.deepCleared?' · '+w3l(W3.deepDone):'')+'</span>';}};