/* GRIND & WELD v2.7 - Act IV Iron Citadel, elite events, relic cores, gem sockets, quest board and deeper endgame. */
if(!state.world7)state.world7={};
var w7=state.world7;
if(w7.a4==null)w7.a4=0;if(w7.a4done==null)w7.a4done=false;if(w7.relic==null)w7.relic=0;if(w7.events==null)w7.events=0;if(w7.gems==null)w7.gems=0;if(w7.bounties==null)w7.bounties=0;if(w7.bountyGoal==null)w7.bountyGoal=0;if(w7.bountyKills==null)w7.bountyKills=0;if(w7.bountyReward==null)w7.bountyReward=0;
var w7fx=[];
AREA_NAMES.citadel=['Vaserőd','Iron Citadel','Eisenzitadelle','Ciudadela de Hierro','Citadelle de Fer','钢铁堡垒','Cittadella di Ferro','Cidadela de Ferro','Żelazna Cytadela','IJzeren Citadel','Citadela de Fier','Железная Цитадель'];
var W7={
 a4:['IV. felvonás · Vaserőd','Act IV · Iron Citadel','Akt IV · Eisenzitadelle','Acto IV · Ciudadela de Hierro','Acte IV · Citadelle de Fer','第四幕·钢铁堡垒','Atto IV · Cittadella di Ferro','Ato IV · Cidadela de Ferro','Akt IV · Żelazna Cytadela','Akte IV · IJzeren Citadel','Actul IV · Citadela de Fier','Акт IV · Железная Цитадель'],
 cores:['Erőmagok','Power Cores','Energiekerne','Núcleos de Energía','Cœurs d’Énergie','动力核心','Nuclei Energetici','Núcleos de Energia','Rdzenie Mocy','Energiekernen','Nuclee de Putere','Энергетические Ядра'],
 boss:['Fekete Kovács','Black Forgemaster','Schwarzer Schmiedemeister','Maestro Forjador Negro','Maître-Forgeron Noir','黑暗锻造大师','Mastro Fabbro Nero','Mestre Ferreiro Negro','Czarny Mistrz Kuźni','Zwarte Smeedmeester','Maestrul Fierar Negru','Чёрный Кузнец'],
 quest:['Haditanács','War Council','Kriegsrat','Consejo de Guerra','Conseil de Guerre','战争议会','Consiglio di Guerra','Conselho de Guerra','Rada Wojenna','Krijgsraad','Consiliul de Război','Военный Совет'],
 bounty:['Fejvadászat','Bounty Hunt','Kopfgeldjagd','Caza de Recompensas','Chasse à la Prime','悬赏猎杀','Caccia alla Taglia','Caça de Recompensas','Polowanie na Nagrody','Premiejacht','Vânătoare de Recompense','Охота за Наградой'],
 relic:['Relikviamag','Relic Core','Reliktkern','Núcleo Reliquia','Cœur Relique','遗物核心','Nucleo Reliquia','Núcleo Relíquia','Rdzeń Reliktu','Reliekkern','Nucleu Relicvă','Реликтовое Ядро'],
 gem:['Műhelykő','Workshop Gem','Werkstattstein','Gema de Taller','Gemme d’Atelier','工坊宝石','Gemma d’Officina','Gema de Oficina','Klejnot Warsztatu','Werkplaatsedelsteen','Nestemată de Atelier','Камень Мастерской'],
 event:['Világesemény','World Event','Weltereignis','Evento Mundial','Événement Mondial','世界事件','Evento Mondiale','Evento Mundial','Wydarzenie Świata','Wereldgebeurtenis','Eveniment Mondial','Мировое Событие'],
 forge:['Őskohó oltára','Ancestral Forge Altar','Ahnen-Schmiedealtar','Altar de Forja Ancestral','Autel de Forge Ancestrale','先祖锻炉祭坛','Altare della Forgia Ancestrale','Altar da Forja Ancestral','Ołtarz Pradawnej Kuźni','Voorouderlijke Smidsaltaar','Altarul Forjei Ancestrale','Алтарь Древней Кузни'],
 done:['A kampány megtisztítva','Campaign cleansed','Kampagne gereinigt','Campaña purificada','Campagne purifiée','战役已净化','Campagna purificata','Campanha purificada','Kampania oczyszczona','Campagne gezuiverd','Campania curățată','Кампания очищена'],
 elite:['Elit raj','Elite Pack','Elitegruppe','Grupo Élite','Groupe d’Élite','精英群','Gruppo Elite','Grupo de Elite','Elitarna Grupa','Elitegroep','Grup Elită','Элитная Группа'],
 socket:['Foglalat','Socket','Sockel','Engarce','Châsse','插槽','Incavo','Encaixe','Gniazdo','Socket','Soclu','Гнездо']
};
function w7l(a){return a[Math.max(0,Math.min(11,lang))]||a[1];}
function w7Status(){if(!w6.a3done)return w6Status();if(!w7.a4done)return w7l(W7.cores)+': '+w7.a4+'/5';return w7l(W7.done);}

var _w7Make=makeItem;makeItem=function(t){var it=_w7Make(t);if(it.r>=2&&it.gem==null&&Math.random()<.24){it.gem=1+((Math.random()*3)|0);w7.gems++;}if(it.r>=3&&it.relic==null&&Math.random()<.12){it.relic=1+((Math.random()*3)|0);it.power+=4+it.relic;w7.relic++;}return it;};
var _w7Name=itemName;itemName=function(it){var n=_w7Name(it);if(it.gem)n+=' ♦'+it.gem;if(it.relic)n+=' ✹'+it.relic;return n;};
var _w7Bonus=equippedBonus;equippedBonus=function(type){var b=_w7Bonus(type),it=w4ItemAt?w4ItemAt(type):null;if(it&&it.gem)b+=it.gem*2;if(it&&it.relic)b+=it.relic*3;return b;};

function w7Style(){if($('w7css'))return;var s=document.createElement('style');s.id='w7css';s.textContent='.w7q{border:1px solid #7c6232;background:linear-gradient(#251c11,#100c08);padding:9px;margin-top:7px;border-radius:6px}.w7q b{color:#f0c56e}.w7gem{color:#7fe7ff}.w7rel{color:#ffc66d}.w7bar{height:8px;background:#080808;border:1px solid #55462e;border-radius:3px;overflow:hidden;margin-top:5px}.w7bar i{display:block;height:100%;background:linear-gradient(90deg,#7f561d,#e0b54f)}';document.head.appendChild(s);}
var _w7Drawer=renderDrawer;renderDrawer=function(){w7Style();_w7Drawer();var d=$('drawer');if(!d)return;var q=document.createElement('div');q.className='w7q';var pct=w7.bountyGoal?Math.min(100,Math.floor(100*w7.bountyKills/w7.bountyGoal)):0;q.innerHTML='<b>'+w7l(W7.quest)+'</b><br>'+w7Status()+'<br><span class="w7gem">'+w7l(W7.gem)+': '+w7.gems+'</span> · <span class="w7rel">'+w7l(W7.relic)+': '+w7.relic+'</span>'+(w7.bountyGoal?'<br>'+w7l(W7.bounty)+': '+w7.bountyKills+'/'+w7.bountyGoal+'<div class="w7bar"><i style="width:'+pct+'%"></i></div>':'');d.appendChild(q);};
var _w7Workshop=renderWorkshop;renderWorkshop=function(){w7Style();_w7Workshop();var z=$('zones');if(z){var a=document.createElement('div');a.className='w7q';a.innerHTML='<b>'+(w7.a4done?'✓ ':'')+w7l(W7.a4)+'</b><br>'+w7l(W7.cores)+' '+w7.a4+'/5 · '+(w6.a3done?'OPEN':T.locked);z.appendChild(a);}var tip=$('workshopTip');if(tip)tip.innerHTML+='<br>'+w7l(W7.quest)+': '+w7Status();};

function w7Node(type,x,z,color,label){var g=new THREE.Group();addTo(g,cyl(.48,.58,.7,0x4b4540,0,.35,0,.8,12));var r=addTo(g,sphere(.18,color,0,.9,0,.1,12));r.material=new THREE.MeshBasicMaterial({color:color});g.position.set(x,0,z);root.add(g);interactables.push({type:type,g:g,x:x,z:z,used:false});campaignBeacon(x,z,color,label);w7fx.push({g:g,core:r,t:Math.random()*6});}
function w7Banner(x,z,c){var g=new THREE.Group();addTo(g,cyl(.06,.07,3,0x6b6761,0,1.5,0,.8,8));var f=addTo(g,box(1.1,1.35,.06,c||0x641d17,.58,2.05,0,.08));g.position.set(x,0,z);root.add(g);w7fx.push({g:g,flag:f,t:Math.random()*6});}
function w7ElitePack(x,z,n){for(var i=0;i<n;i++){var a=(Math.PI*2*i)/n;spawnEnemy(3+(i%2),i===0,x+Math.cos(a)*4,z+Math.sin(a)*4);var e=enemies[enemies.length-1];if(e&&e.userData&&e.userData.e){e.userData.e.elite=true;e.userData.e.hp=Math.floor(e.userData.e.hp*1.5);e.userData.e.max=e.userData.e.hp;e.scale.setScalar(i===0?1.32:1.12);}}w7.events++;toast(w7l(W7.elite),'rare');}
function buildCitadel(){areaKey='citadel';zoneIndex=6;scene.background.set(0x07090b);scene.fog.color.copy(scene.background);dungeonShell(92,72);areaEntry={x:0,z:-32};campaignReturn(0,-32,0,-35);campaignRoad(0,0,86,9,0x292d30);campaignRoad(0,0,9,66,0x292d30);for(var i=-36;i<=36;i+=12){addObstacle(i,-22,4,3,2.8,0x514b46,'wall');addObstacle(i,22,4,3,2.8,0x514b46,'wall');if(i%24===0){w7Banner(i,-27,0x5a1715);w7Banner(i,27,0x243f61);}}for(i=-28;i<=28;i+=14){lamp(i,-17,0xff9a43);lamp(i,17,0x70aee0);crate(i+2,-8,1.2);barrel(i-2,9,0x613126);}chest(-39,29);chest(39,29);chest(-39,-28);chest(39,-28);if(!w7.a4done){var p=[[-32,-4],[-16,18],[0,-15],[18,17],[34,-5]];for(i=w7.a4;i<5;i++)w7Node('w7core',p[i][0],p[i][1],i%2?0xff9b45:0x6fb9ec,w7l(W7.cores));if(w7.a4>=5&&!bossSpawned){spawnEnemy(4,true,0,27);var e=enemies[enemies.length-1];e.userData.e.tag='blackforge';e.scale.setScalar(1.85);e.userData.e.hp=Math.floor(e.userData.e.hp*1.7);e.userData.e.max=e.userData.e.hp;bossSpawned=true;toast(w7l(W7.boss),'legend');}}if(Math.random()<.65)w7ElitePack(-22+Math.random()*44,-5+Math.random()*10,4);spawnAmbient(28);}

var _w7BA=buildArea;buildArea=function(k,x,z){if(k==='citadel'){clearWorld();matCache={};questBeacons=[];bossSpawned=false;buildCitadel();player=makeHumanoid(clsIndex(),false);player.position.set(x!=null?x:areaEntry.x,0,z!=null?z:areaEntry.z);root.add(player);playerParts=player.userData.parts;updateMission();save();return;}_w7BA(k,x,z);if(k==='surface'&&w6.a3done)campaignPortal(0,42,'citadel');};
var _w7PU=portalUnlocked;portalUnlocked=function(t){if(t==='citadel')return !!w6.a3done;return _w7PU(t);};
var _w7I=interact;interact=function(){var q=nearestInteract();if(!q){_w7I();return;}if(q.type==='w7core'){q.used=true;w7.a4=Math.min(5,w7.a4+1);spawnSparks(q.g.position,0xffb15b,24);root.remove(q.g);toast(w7l(W7.cores)+' '+w7.a4+'/5','magic');if(w7.a4>=5&&!bossSpawned){spawnEnemy(4,true,0,27);var e=enemies[enemies.length-1];e.userData.e.tag='blackforge';e.scale.setScalar(1.85);e.userData.e.hp=Math.floor(e.userData.e.hp*1.7);e.userData.e.max=e.userData.e.hp;bossSpawned=true;}save();updateMission();return;}_w7I();};

var _w7Death=enemyDeath;enemyDeath=function(e){var d=e&&e.userData?e.userData.e||{}:{};var boss=d.tag==='blackforge';var elite=!!d.elite;_w7Death(e);if(w7.bountyGoal>0){w7.bountyKills++;if(w7.bountyKills>=w7.bountyGoal){state.gold+=w7.bountyReward||180;state.steel+=4;w7.bounties++;toast(w7l(W7.bounty)+' ✓','legend');w7.bountyGoal=0;w7.bountyKills=0;w7.bountyReward=0;}}if(elite&&Math.random()<.35){state.runes++;w7.gems++;}if(boss&&!w7.a4done){w7.a4done=true;w7.relic+=2;state.gold+=420;state.steel+=12;state.runes+=3;addXp(650);for(var i=0;i<3;i++)state.inventory.push(makeItem(state.level+6));toast(w7l(W7.done),'legend');openExtraction();save();}};

function w7StartBounty(){if(w7.bountyGoal>0)return;w7.bountyGoal=8+((Math.random()*8)|0);w7.bountyKills=0;w7.bountyReward=160+w7.bountyGoal*14;toast(w7l(W7.bounty)+': '+w7.bountyGoal,'magic');save();}
var _w7RW=renderWorkshop;renderWorkshop=function(){_w7RW();var rb=$('resourceBox');if(rb){var b=document.createElement('div');b.className='w7q';b.innerHTML='<b>'+w7l(W7.bounty)+'</b><br>'+(w7.bountyGoal?w7.bountyKills+'/'+w7.bountyGoal:'READY');b.onclick=function(){w7StartBounty();renderWorkshop();};rb.appendChild(b);}};

var _w7UM=updateMission;updateMission=function(){_w7UM();if(!mission)return;if(areaKey==='citadel'){$('missionTitle').textContent=T.mission+': '+w7l(W7.a4);$('missionText').textContent=w7.a4done?w7l(W7.done):(w7l(W7.cores)+' '+w7.a4+'/5'+(w7.a4>=5?' · '+w7l(W7.boss):''));}else if(w7.bountyGoal>0)$('missionText').textContent+=' · '+w7l(W7.bounty)+' '+w7.bountyKills+'/'+w7.bountyGoal;};

var _w7Update=update;update=function(dt){_w7Update(dt);for(var i=w7fx.length-1;i>=0;i--){var a=w7fx[i];if(!a||!a.g||!a.g.parent){w7fx.splice(i,1);continue;}a.t+=dt;if(a.core){var s=.85+Math.abs(Math.sin(a.t*3.4))*.35;a.core.scale.setScalar(s);a.core.position.y=.9+Math.sin(a.t*4.1)*.035;}if(a.flag)a.flag.rotation.z=Math.sin(a.t*2.2)*.055;}};

var _w7Save=save;save=function(){try{if(state.world7!==w7)state.world7=w7;}catch(e){}_w7Save();};
