/* GRIND & WELD v2.7: Act IV Iron Citadel, hireling, mastery, Rift modifiers, Scrap Runner events and phased boss. */
if(!state.world7)state.world7={};
var w7=state.world7;
if(w7.act4==null)w7.act4=0;
if(w7.act4done==null)w7.act4done=false;
if(w7.merc==null)w7.merc=false;
if(w7.mercLvl==null)w7.mercLvl=1;
if(w7.mastery==null)w7.mastery=0;
if(w7.masteryRank==null)w7.masteryRank=0;
if(w7.scrapRuns==null)w7.scrapRuns=0;
if(w7.runnerKills==null)w7.runnerKills=0;
if(w7.bossPhase==null)w7.bossPhase=0;
AREA_NAMES.ironcitadel=['Vaskohó Citadella','Iron Forge Citadel','Eisenschmiede-Zitadelle','Ciudadela de la Forja','Citadelle de la Forge','钢铁熔炉堡垒','Cittadella della Forgia','Cidadela da Forja','Cytadela Kuźni','IJzersmederij Citadel','Citadela Forjei','Цитадель Кузницы'];
var W7={
 act4:['IV. felvonás · Vaskohó Citadella','Act IV · Iron Forge Citadel','Akt IV · Eisenschmiede-Zitadelle','Acto IV · Ciudadela de la Forja','Acte IV · Citadelle de la Forge','第四幕·钢铁熔炉堡垒','Atto IV · Cittadella della Forgia','Ato IV · Cidadela da Forja','Akt IV · Cytadela Kuźni','Akte IV · IJzersmederij Citadel','Actul IV · Citadela Forjei','Акт IV · Цитадель Кузницы'],
 anchor:['Kohóhorgony','Forge anchor','Schmiedeanker','Anclaje de forja','Ancre de forge','熔炉锚点','Ancora della forgia','Âncora da forja','Kotwa kuźni','Smederij-anker','Ancoră de forjă','Якорь кузницы'],
 castellan:['Vas Castellán','Iron Castellan','Eisen-Kastellan','Castellano de Hierro','Châtelain de Fer','钢铁城主','Castellano di Ferro','Castelão de Ferro','Żelazny Kasztelan','IJzeren Kastelein','Castelanul de Fier','Железный Кастелян'],
 actDone:['A Citadella megtisztítva','Citadel cleansed','Zitadelle gesäubert','Ciudadela purificada','Citadelle purifiée','堡垒已净化','Cittadella purificata','Cidadela purificada','Cytadela oczyszczona','Citadel gezuiverd','Citadela a fost curățată','Цитадель очищена'],
 merc:['Segéd','Hireling','Helfer','Ayudante','Mercenaire','助手','Aiutante','Ajudante','Pomocnik','Hulp','Ajutor','Помощник'],
 recruit:['Segéd felfogadva','Hireling recruited','Helfer angeheuert','Ayudante reclutado','Mercenaire recruté','助手已招募','Aiutante reclutato','Ajudante recrutado','Pomocnik zatrudniony','Hulp ingehuurd','Ajutor recrutat','Помощник нанят'],
 mastery:['Mesterség','Mastery','Meisterschaft','Maestría','Maîtrise','专精','Maestria','Maestria','Mistrzostwo','Meesterschap','Măiestrie','Мастерство'],
 masteries:[
  ['Pörölyerő','Hammercraft','Hammerkraft','Maestría del Martillo','Maîtrise du Marteau','锤艺','Arte del Martello','Arte do Martelo','Mistrz Młota','Hamerkunst','Arta Ciocanului','Мастер Молота'],
  ['Ívvezérlés','Arc Control','Lichtbogenkontrolle','Control de Arco','Contrôle d’Arc','电弧控制','Controllo Arco','Controle de Arco','Kontrola Łuku','Boogcontrole','Controlul Arcului','Контроль Дуги'],
  ['Bontómester','Salvage Master','Bergungsmeister','Maestro del Rescate','Maître Récupérateur','回收大师','Maestro Recupero','Mestre da Sucata','Mistrz Złomu','Bergingsmeester','Maestru Recuperator','Мастер Разборки']
 ],
 upgrade:['Fejlesztés','Upgrade','Aufwerten','Mejorar','Améliorer','升级','Migliora','Melhorar','Ulepsz','Verbeter','Îmbunătățește','Улучшить'],
 rift:['Hasadék módosító','Rift modifier','Riss-Modifikator','Modificador de Falla','Modificateur de Faille','裂隙词缀','Modificatore Faglia','Modificador da Fenda','Modyfikator Szczeliny','Spleetmodifier','Modificator Falia','Модификатор Разлома'],
 mods:[
  ['Túlhevülés','Overheat','Überhitzung','Sobrecalentamiento','Surchauffe','过热','Surriscaldamento','Superaquecimento','Przegrzanie','Oververhitting','Supraîncălzire','Перегрев'],
  ['Áramszünet','Blackout','Stromausfall','Apagón','Coupure','停电','Blackout','Apagão','Blackout','Stroomuitval','Pană de curent','Отключение'],
  ['Megerősített','Fortified','Verstärkt','Fortificado','Fortifié','强化','Fortificato','Fortificado','Wzmocniony','Versterkt','Fortificat','Укреплённый'],
  ['Bontási láz','Salvage Fever','Bergungsfieber','Fiebre de Rescate','Fièvre de Récupération','回收狂热','Febbre da Recupero','Febre de Sucata','Gorączka Złomu','Bergingskoorts','Febra Recuperării','Лихорадка Разборки']
 ],
 runner:['Roncsfutár','Scrap Runner','Schrottläufer','Corredor de Chatarra','Coureur de Ferraille','废料跑者','Corriere di Rottami','Corredor de Sucata','Biegacz Złomu','Schrootloper','Curier de Fier Vechi','Бегун за Ломом'],
 phase2:['2. fázis · Túlvezérelt kohó','Phase 2 · Overdriven Forge','Phase 2 · Übersteuerte Schmiede','Fase 2 · Forja Sobrecargada','Phase 2 · Forge Suralimentée','第二阶段·过载熔炉','Fase 2 · Forgia Sovraccarica','Fase 2 · Forja Sobrecarregada','Faza 2 · Przeciążona Kuźnia','Fase 2 · Overdrive Smederij','Faza 2 · Forjă Supraîncărcată','Фаза 2 · Перегруженная Кузница']
};
function w7l(a){return a[Math.max(0,Math.min(11,lang))]||a[1];}
function w7Node(type,x,z,color){var g=new THREE.Group();addTo(g,cyl(.5,.58,.72,0x4b4640,0,.36,0,.75,10));var o=addTo(g,sphere(.19,color,0,.92,0,.1,12));o.material=new THREE.MeshBasicMaterial({color:color});g.position.set(x,0,z);root.add(g);interactables.push({type:type,g:g,x:x,z:z,used:false});campaignBeacon(x,z,color,w7l(W7.anchor));}
function buildIronCitadel(){areaKey='ironcitadel';zoneIndex=6;scene.background.set(0x090807);scene.fog.color.copy(scene.background);dungeonShell(92,72);areaEntry={x:0,z:-31};campaignReturn(0,-31,0,-35);campaignRoad(0,0,84,11,0x302927);campaignRoad(0,3,12,62,0x302927);for(var i=-32;i<=32;i+=16){addObstacle(i,-12,5,4,2.8,0x514238,'wall');addObstacle(i,16,5,4,2.8,0x514238,'wall');lamp(i,-25,i%32?0xff8b41:0x6bb7e5);crate(i+3,25,1.15);barrel(i-2,-23,0x6e3126);}for(i=0;i<8;i++){var a=i*Math.PI/4;addObstacle(Math.cos(a)*28,Math.sin(a)*22,3.4,3.4,3.0,0x59493f,'pillar');}chest(-38,27);chest(38,27);chest(-38,-26);chest(38,-26);if(!w7.act4done){var p=[[-27,-4],[-8,24],[13,-20],[30,7]];for(i=w7.act4;i<4;i++)w7Node('w7anchor',p[i][0],p[i][1],0xffa24a);if(w7.act4>=4&&!bossSpawned)w7SpawnCastellan();}spawnAmbient(28);}
function w7SpawnCastellan(){spawnEnemy(4,true,0,27);var e=enemies[enemies.length-1];if(!e)return;e.scale.setScalar(1.78);e.userData.e.tag='castellan';e.userData.e.hp=Math.round(e.userData.e.hp*2.15);e.userData.e.max=e.userData.e.hp;e.userData.e.damage=Math.round(e.userData.e.damage*1.28);w7.bossPhase=1;bossSpawned=true;toast(T.boss+': '+w7l(W7.castellan),'legend');}
function w7MercNpc(){if(w7.merc||!w6.a2done)return;var g=makeHumanoid(0,false);g.scale.setScalar(.9);g.position.set(-12,0,-34);root.add(g);interactables.push({type:'w7mercnpc',g:g,x:-12,z:-34,used:false});campaignBeacon(-12,-34,0x8ed07e,w7l(W7.merc));}
var w7Merc=null,w7MercCd=0;
function w7SpawnMerc(){if(!mission||!w7.merc||!player||w7Merc)return;try{w7Merc=makeHumanoid(0,false);w7Merc.scale.setScalar(.78);w7Merc.position.copy(player.position).add(new THREE.Vector3(-1.2,0,1.2));root.add(w7Merc);}catch(e){w7Merc=null;}}
function w7DropMerc(){if(w7Merc){try{root.remove(w7Merc);disposeObject(w7Merc);}catch(e){}w7Merc=null;}w7MercCd=0;}
function w7MasteryBonus(){var r=Math.max(0,w7.masteryRank|0);return {d:w7.mastery===0?r*2.2:0,h:w7.mastery===1?r*7:0,s:w7.mastery===2?r*.035:0};}
function w7MasteryUpgrade(){var cost=1+Math.floor(w7.masteryRank/2);if(w7.masteryRank>=6){toast('MAX','magic');return;}if(state.runes<cost){toast(T.need+' '+cost+' '+T.runes,'rare');return;}state.runes-=cost;w7.masteryRank++;toast(w7l(W7.mastery)+' +'+w7.masteryRank,'magic');save();renderWorkshop();}
function w7SetMastery(i){w7.mastery=Math.max(0,Math.min(2,i|0));toast(w7l(W7.masteries[w7.mastery]),'magic');save();renderWorkshop();}
window.GWMastery=function(i){w7SetMastery(i);};window.GWMasteryUp=function(){w7MasteryUpgrade();};
function w7RiftMod(){return Math.abs(((w4.riftSeed||1)+(w4.riftTier||1)*17+(w4.riftRuns||0)*31))%4;}
function w7RiftText(){return w7l(W7.mods[w7RiftMod()]);}
function w7MaybeRunner(){if(!mission||!player||(areaKey!=='surface'&&areaKey!=='rift')||Math.random()>.16)return;var ang=Math.random()*Math.PI*2,r=7+Math.random()*5;spawnEnemy(2,true,player.position.x+Math.cos(ang)*r,player.position.z+Math.sin(ang)*r);var e=enemies[enemies.length-1];if(!e)return;var d=e.userData.e;d.tag='scraprunner';d.hp=Math.round(d.hp*.72);d.max=d.hp;d.damage=Math.round(d.damage*.35);d.speed*=1.65;e.scale.setScalar(.78);toast(w7l(W7.runner),'legend');}
var _w7BA=buildArea;buildArea=function(k,x,z){w7DropMerc();if(k==='ironcitadel'){clearWorld();matCache={};questBeacons=[];bossSpawned=false;buildIronCitadel();player=makeHumanoid(clsIndex(),false);player.position.set(x!=null?x:areaEntry.x,0,z!=null?z:areaEntry.z);root.add(player);playerParts=player.userData.parts;updateMission();save();setTimeout(w7SpawnMerc,40);return;}_w7BA(k,x,z);if(k==='surface'){if(w6.a3done)campaignPortal(0,-46,'ironcitadel');w7MercNpc();}setTimeout(w7SpawnMerc,40);if(k==='rift')toast(w7l(W7.rift)+': '+w7RiftText(),'rare');setTimeout(w7MaybeRunner,250);};
var _w7PU=portalUnlocked;portalUnlocked=function(t){if(t==='ironcitadel')return !!w6.a3done;return _w7PU(t);};
var _w7PS=playerStats;playerStats=function(){var c=_w7PS(),b=w7MasteryBonus();return {id:c.id,hp:c.hp+b.h,en:c.en,speed:c.speed*(1+b.s),damage:(c.damage||10)+b.d,color:c.color};};
var _w7SE=spawnEnemy;spawnEnemy=function(k,b,x,z){_w7SE(k,b,x,z);var e=enemies[enemies.length-1];if(!e||!e.userData||!e.userData.e)return;if(areaKey==='rift'){var d=e.userData.e,m=w7RiftMod();if(m===0)d.damage=Math.round(d.damage*1.18);else if(m===2){d.hp=Math.round(d.hp*1.32);d.max=d.hp;}else if(m===3&&!b&&Math.random()<.15){d.elite=true;d.hp=Math.round(d.hp*1.4);d.max=d.hp;}}};
var _w7I=interact;interact=function(){var q=nearestInteract();if(!q){_w7I();return;}if(q.type==='w7anchor'){q.used=true;w7.act4=Math.min(4,w7.act4+1);spawnSparks(q.g.position,0xffa24a,24);root.remove(q.g);toast(w7l(W7.anchor)+' '+w7.act4+'/4','magic');if(w7.act4>=4&&!bossSpawned)w7SpawnCastellan();save();updateMission();return;}if(q.type==='w7mercnpc'){w7.merc=true;w7.mercLvl=Math.max(1,state.level);spawnSparks(q.g.position,0x8ed07e,20);root.remove(q.g);toast(w7l(W7.recruit),'magic');save();setTimeout(w7SpawnMerc,20);return;}_w7I();};
var _w7ED=enemyDeath;enemyDeath=function(e){var d=e&&e.userData?e.userData.e||{}:{},boss=d.tag==='castellan',runner=d.tag==='scraprunner';_w7ED(e);if(runner){w7.runnerKills++;w7.scrapRuns++;state.gold+=75+state.level*8;state.steel+=2;for(var q=0;q<3;q++)spawnLoot(e.position.clone().add(new THREE.Vector3((Math.random()-.5)*2,0,(Math.random()-.5)*2)),q===2?2:1);toast(w7l(W7.runner)+' ✓','legend');save();}if(boss&&!w7.act4done){w7.act4done=true;w7.bossPhase=3;state.gold+=720;state.steel+=16;state.runes+=4;addXp(950);for(var i=0;i<5;i++)spawnLoot(new THREE.Vector3((Math.random()-.5)*5,0,27+(Math.random()-.5)*4),i>=3?3:2);toast(w7l(W7.actDone),'legend');openExtraction();save();}};
var _w7RW=renderWorkshop;renderWorkshop=function(){_w7RW();var z=$('zones');if(z){var a=document.createElement('div');a.className='w6act';a.innerHTML='<b>'+(w7.act4done?'✓ ':'')+w7l(W7.act4)+'</b><br>'+w7l(W7.anchor)+' '+w7.act4+'/4 · '+(w6.a3done?'OPEN':T.locked);z.appendChild(a);}var tip=$('workshopTip');if(tip){tip.innerHTML+='<div style="margin-top:8px;padding:7px;border:1px solid #705a34;border-radius:7px"><b>'+w7l(W7.mastery)+'</b>: '+w7l(W7.masteries[w7.mastery])+' Lv.'+w7.masteryRank+'<br><button class="btn" style="margin:4px 3px 0 0" onclick="GWMastery(0)">1</button><button class="btn" style="margin:4px 3px 0 0" onclick="GWMastery(1)">2</button><button class="btn" style="margin:4px 3px 0 0" onclick="GWMastery(2)">3</button><button class="btn" style="margin:4px 0 0 6px" onclick="GWMasteryUp()">'+w7l(W7.upgrade)+'</button>'+(w7.merc?'<br>'+w7l(W7.merc)+' Lv.'+w7.mercLvl:'')+'</div>';}};
var _w7UM=updateMission;updateMission=function(){_w7UM();if(!mission)return;if(areaKey==='ironcitadel'){$('missionTitle').textContent=T.mission+': '+w7l(W7.act4);$('missionText').textContent=w7.act4done?w7l(W7.actDone):(w7l(W7.anchor)+' '+w7.act4+'/4'+(w7.act4>=4?' · '+w7l(W7.castellan):''));}else if(areaKey==='rift')$('missionText').textContent+=' · '+w7l(W7.rift)+': '+w7RiftText();};
var _w7U=update;update=function(dt){_w7U(dt);if(!mission||!player)return;if(w7.merc&&!w7Merc)w7SpawnMerc();if(w7Merc){var desired=player.position.clone().add(new THREE.Vector3(-1.25,0,1.05)),dv=desired.clone().sub(w7Merc.position),dist=dv.length();if(dist>6)w7Merc.position.copy(desired);else if(dist>.45)w7Merc.position.add(dv.normalize().multiplyScalar(Math.min(dist,dt*4.5)));w7Merc.rotation.y=Math.atan2(dv.x,dv.z);w7MercCd-=dt;if(w7MercCd<=0){var best=null,bd=5.5;for(var i=0;i<enemies.length;i++){var ee=enemies[i],dd=ee.position.distanceTo(w7Merc.position);if(dd<bd){bd=dd;best=ee;}}if(best){w7MercCd=.75;damageEnemy(best,3+state.level*.75+w7.mercLvl*.25);spawnSparks(best.position,0x8ed07e,5);}}}
 for(var j=0;j<enemies.length;j++){var e=enemies[j],d=e.userData&&e.userData.e;if(!d)continue;if(d.tag==='scraprunner'){var away=e.position.clone().sub(player.position);away.y=0;if(away.lengthSq()>.01)e.position.add(away.normalize().multiplyScalar(dt*d.speed*.55));}if(d.tag==='castellan'&&d.max>0&&!w7.act4done){var ratio=d.hp/d.max;if(ratio<.52&&w7.bossPhase<2){w7.bossPhase=2;d.damage=Math.round(d.damage*1.22);d.speed*=1.18;spawnSparks(e.position,0xff7b35,35);toast(w7l(W7.phase2),'legend');for(var n=0;n<3;n++)spawnEnemy(2,false,e.position.x+(n-1)*2.3,e.position.z-3);}}}
};
var _w7SD=shutdown;shutdown=function(){w7DropMerc();_w7SD();};
save();
