package com.gatecraft.game;

import android.content.Context;
import android.graphics.Canvas;
import android.graphics.Color;
import android.graphics.Paint;
import android.graphics.RectF;
import android.view.MotionEvent;
import android.view.View;

final class GameLauncherView extends View {
  private static final float LW=960f,LH=540f;
  private final GateCraftGame owner; private final Paint p=new Paint(); private float scale=1,ox,oy;
  private final RectF[] cards={new RectF(36,118,924,226),new RectF(36,238,924,346),new RectF(36,358,924,466)};
  private final RectF exit=new RectF(806,16,940,66);
  GameLauncherView(Context c,GateCraftGame owner){super(c);this.owner=owner;p.setAntiAlias(false);p.setFilterBitmap(false);setBackgroundColor(Color.BLACK);}
  private String t(String hu,String en,String de,String es,String fr,String zh,String it,String pt,String pl,String nl,String ro,String ru){String[]a={hu,en,de,es,fr,zh,it,pt,pl,nl,ro,ru};return a[Math.max(0,Math.min(11,owner.getLanguage()-1))];}
  private void fill(Canvas c,int color,float l,float t,float r,float b){p.setStyle(Paint.Style.FILL);p.setColor(color);c.drawRect(l,t,r,b,p);} private void line(Canvas c,int color,float w,float x1,float y1,float x2,float y2){p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(w);p.setColor(color);c.drawLine(x1,y1,x2,y2,p);p.setStyle(Paint.Style.FILL);} private void stroke(Canvas c,int color,float w,float l,float t,float r,float b){p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(w);p.setColor(color);c.drawRect(l,t,r,b,p);p.setStyle(Paint.Style.FILL);} private void text(Canvas c,String s,float x,float y,float size,int col,Paint.Align align,boolean bold){p.setColor(col);p.setTextSize(size);p.setTextAlign(align);p.setTypeface(bold?android.graphics.Typeface.DEFAULT_BOLD:android.graphics.Typeface.MONOSPACE);c.drawText(s,x,y,p);}
  @Override protected void onDraw(Canvas c){super.onDraw(c);scale=Math.min(getWidth()/LW,getHeight()/LH);ox=(getWidth()-LW*scale)/2;oy=(getHeight()-LH*scale)/2;c.save();c.translate(ox,oy);c.scale(scale,scale);
    fill(c,Color.rgb(6,9,14),0,0,LW,LH);for(int y=0;y<540;y+=28)fill(c,(y/28)%2==0?Color.rgb(12,18,25):Color.rgb(8,13,20),0,y,LW,y+14);for(int x=0;x<960;x+=72){fill(c,Color.rgb(27,32,36),x,82,x+3,515);fill(c,Color.rgb(4,7,11),x+3,82,x+5,515);}fill(c,Color.rgb(10,13,19),0,0,960,96);line(c,Color.rgb(185,126,44),4,0,94,960,94);
    text(c,"GATECRAFT ARCADE",36,44,30,Color.rgb(248,211,79),Paint.Align.LEFT,true);text(c,"CLASSIC HERITAGE EDITION",36,73,15,Color.rgb(208,174,105),Paint.Align.LEFT,true);text(c,t("A klasszikus 90-es évek platformerei, stratégiái és verekedős játékai nyomán","Built from the DNA of classic 90s platformers, strategy games and fighters","Nach dem Vorbild klassischer 90er Plattform-, Strategie- und Kampfspiele","Inspirado en plataformas, estrategia y lucha clásicas de los 90","Inspiré des classiques plateforme, stratégie et combat des années 90","汲取90年代经典平台、策略与格斗游戏的设计精髓","Ispirato ai classici platform, strategia e picchiaduro anni 90","Inspirado nos clássicos de plataforma, estratégia e luta dos anos 90","W duchu klasycznych platformówek, strategii i bijatyk lat 90.","Gebouwd op klassieke platform-, strategie- en vechtgames uit de jaren 90","Inspirat din platformere, strategii și jocuri de luptă clasice din anii 90","В духе классических платформеров, стратегий и файтингов 90-х"),405,73,12,Color.LTGRAY,Paint.Align.LEFT,false);
    String[]names={"WORKSHOP RUN '95","HEROES OF CRAFT & GATES II","METAL FIGHTER '98"};
    String[]subs={t("Run-and-gun • kapuk • boss • rivet gun • titkos felső út","Run-and-gun • gates • boss • rivet gun • bonus upper route","Run-and-gun • Tore • Boss • Nietpistole • Bonusroute","Run-and-gun • puertas • jefe • remachadora • ruta bonus","Run-and-gun • portes • boss • riveteuse • route bonus","跑轰 • 大门 • Boss • 铆钉枪 • 奖励路线","Run-and-gun • cancelli • boss • rivettatrice • percorso bonus","Run-and-gun • portões • chefe • rebitador • rota bônus","Run-and-gun • bramy • boss • nitownica • trasa bonus","Run-and-gun • poorten • baas • klinknagelpistool • bonusroute","Run-and-gun • porți • boss • pistol de nituri • rută bonus","Run-and-gun • ворота • босс • заклёпочник • бонусный путь"),
      t("15×10 világ • köd • bányák • napi bevétel • rivális AI • brigád","15×10 world • fog • mines • daily income • rival AI • crew battles","15×10 Welt • Nebel • Minen • Tageseinkommen • Rivalen-KI • Teams","Mundo 15×10 • niebla • minas • ingresos • rival IA • brigadas","Monde 15×10 • brouillard • mines • revenus • rival IA • équipes","15×10世界 • 战争迷雾 • 矿井 • 日收入 • 对手AI • 小队战","Mondo 15×10 • nebbia • miniere • entrate • rivale IA • squadre","Mundo 15×10 • névoa • minas • renda • rival IA • equipes","Świat 15×10 • mgła • kopalnie • dochód • rywal AI • drużyny","15×10 wereld • mist • mijnen • inkomen • rivaal-AI • teams","Lume 15×10 • ceață • mine • venit • rival AI • echipe","Мир 15×10 • туман • шахты • доход • ИИ-соперник • бригады"),
      t("Arcade ladder • 5 rivális • guard break • lövedék • OVERLOAD","Arcade ladder • 5 rivals • guard break • projectiles • OVERLOAD","Arcade-Leiter • 5 Rivalen • Guard Break • Projektile • OVERLOAD","Escalera arcade • 5 rivales • guard break • proyectiles • OVERLOAD","Ladder arcade • 5 rivaux • guard break • projectiles • OVERLOAD","街机天梯 • 5名对手 • 破防 • 飞行道具 • OVERLOAD","Scala arcade • 5 rivali • guard break • proiettili • OVERLOAD","Escada arcade • 5 rivais • guard break • projéteis • OVERLOAD","Drabinka arcade • 5 rywali • guard break • pociski • OVERLOAD","Arcadeladder • 5 rivalen • guard break • projectielen • OVERLOAD","Scară arcade • 5 rivali • guard break • proiectile • OVERLOAD","Аркадная лестница • 5 соперников • guard break • снаряды • OVERLOAD")};
    int[]cols={Color.rgb(30,122,90),Color.rgb(137,89,35),Color.rgb(151,44,43)};for(int i=0;i<3;i++){RectF r=cards[i];boolean u=owner.modeUnlocked(i+1);fill(c,Color.rgb(2,4,7),r.left-5,r.top-5,r.right+5,r.bottom+5);fill(c,u?cols[i]:Color.rgb(47,50,55),r.left,r.top,r.right,r.bottom);fill(c,Color.argb(48,255,255,255),r.left+7,r.top+7,r.right-7,r.top+16);fill(c,Color.argb(95,0,0,0),r.left,r.top,r.left+198,r.bottom);drawPreview(c,i,r.left+98,r.centerY());text(c,names[i],r.left+220,r.top+42,25,Color.WHITE,Paint.Align.LEFT,true);text(c,subs[i],r.left+220,r.top+76,13,Color.rgb(234,232,222),Paint.Align.LEFT,false);if(u){text(c,"▶",r.right-38,r.centerY()+12,36,Color.WHITE,Paint.Align.CENTER,true);text(c,t("INDÍTÁS","PLAY","START","JUGAR","JOUER","开始","GIOCA","JOGAR","GRAJ","SPEEL","JOACĂ","ИГРАТЬ"),r.right-72,r.bottom-15,12,Color.rgb(255,236,166),Paint.Align.RIGHT,true);}else text(c,t("ZÁR","LOCK","SPERRE","BLOQ","VERROU","锁定","BLOCCO","BLOQ","BLOK","SLOT","BLOC","ЗАМОК")+" "+owner.requiredFor(i+1),r.right-28,r.centerY()+7,17,Color.rgb(255,206,94),Paint.Align.RIGHT,true);}
    fill(c,Color.rgb(124,38,38),exit.left,exit.top,exit.right,exit.bottom);stroke(c,Color.rgb(225,210,178),2,exit.left,exit.top,exit.right,exit.bottom);text(c,t("KILÉP","EXIT","ENDE","SALIR","QUITTER","退出","ESCI","SAIR","WYJDŹ","AFSLUITEN","IEȘIRE","ВЫХОД"),exit.centerX(),exit.centerY()+7,17,Color.WHITE,Paint.Align.CENTER,true);text(c,t("GRIND & WELD külön végső bónusz marad","GRIND & WELD remains the separate final bonus","GRIND & WELD bleibt separater Endbonus","GRIND & WELD sigue como bonus final separado","GRIND & WELD reste le bonus final séparé","GRIND & WELD仍为独立最终奖励","GRIND & WELD resta bonus finale separato","GRIND & WELD continua como bônus final separado","GRIND & WELD pozostaje osobnym finałowym bonusem","GRIND & WELD blijft aparte eindbonus","GRIND & WELD rămâne bonus final separat","GRIND & WELD остаётся отдельным финальным бонусом"),36,505,13,Color.rgb(177,184,192),Paint.Align.LEFT,false);c.restore();}
  private void drawPreview(Canvas c,int mode,float cx,float cy){if(mode==0){fill(c,Color.rgb(29,34,42),cx-82,cy-40,cx+82,cy+40);fill(c,Color.rgb(83,86,84),cx-80,cy+14,cx+80,cy+35);SpriteKit.worker(c,p,cx-24,cy+16,.76f,1,2,System.currentTimeMillis()*.001f,false);fill(c,Color.rgb(79,72,64),cx+52,cy-20,cx+62,cy+31);line(c,Color.rgb(255,187,71),4,cx-1,cy-10,cx+43,cy-10);}else if(mode==1){fill(c,Color.rgb(45,87,48),cx-82,cy-40,cx+82,cy+40);for(int y=-30;y<35;y+=22)for(int x=-65;x<70;x+=38){p.setColor(((x+y)&1)==0?Color.rgb(69,123,62):Color.rgb(58,109,57));c.drawCircle(cx+x,cy+y,16,p);}SpriteKit.worker(c,p,cx-22,cy+25,.55f,1,0,0,false);SpriteKit.worker(c,p,cx+42,cy+7,.45f,-1,0,0,true);SpriteKit.icon(c,p,0,cx+55,cy-20,.5f);}else{fill(c,Color.rgb(73,42,88),cx-82,cy-40,cx+82,cy+40);fill(c,Color.rgb(42,49,56),cx-82,cy+18,cx+82,cy+40);SpriteKit.worker(c,p,cx-38,cy+24,.8f,1,2,0,false);SpriteKit.worker(c,p,cx+45,cy+24,.8f,-1,3,0,true);line(c,Color.rgb(98,199,255),5,cx-8,cy-17,cx+32,cy-25);}}
  @Override public boolean onTouchEvent(MotionEvent e){if(e.getActionMasked()!=MotionEvent.ACTION_DOWN)return true;float x=(e.getX()-ox)/scale,y=(e.getY()-oy)/scale;if(exit.contains(x,y)){owner.requestExitFromView();return true;}for(int i=0;i<3;i++)if(cards[i].contains(x,y)&&owner.modeUnlocked(i+1)){owner.launchMode(i+1);return true;}return true;}
}
