package com.gatecraft.game;

import android.content.Context;
import android.graphics.Canvas;
import android.graphics.Color;
import android.graphics.Paint;
import android.graphics.RectF;
import android.view.MotionEvent;
import android.view.View;

final class GameLauncherView extends View {
  private static final float LW=960f,LH=540f;
  private final GateCraftGame owner;
  private final Paint p=new Paint();
  private float scale=1,ox,oy;
  private final RectF[] cards={new RectF(36,118,924,226),new RectF(36,238,924,346),new RectF(36,358,924,466)};
  private final RectF exit=new RectF(806,16,940,66);
  GameLauncherView(Context c,GateCraftGame owner){super(c);this.owner=owner;p.setAntiAlias(false);p.setFilterBitmap(false);setBackgroundColor(Color.BLACK);}
  private String t(String hu,String en,String de,String es,String fr,String zh,String it,String pt,String pl,String nl,String ro,String ru){String[]a={hu,en,de,es,fr,zh,it,pt,pl,nl,ro,ru};return a[Math.max(0,Math.min(11,owner.getLanguage()-1))];}
  private void fill(Canvas c,int color,float l,float t,float r,float b){p.setStyle(Paint.Style.FILL);p.setColor(color);c.drawRect(l,t,r,b,p);} 
  private void line(Canvas c,int color,float w,float x1,float y1,float x2,float y2){p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(w);p.setColor(color);c.drawLine(x1,y1,x2,y2,p);p.setStyle(Paint.Style.FILL);} 
  private void stroke(Canvas c,int color,float w,float l,float t,float r,float b){p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(w);p.setColor(color);c.drawRect(l,t,r,b,p);p.setStyle(Paint.Style.FILL);} 
  private void text(Canvas c,String s,float x,float y,float size,int col,Paint.Align align,boolean bold){p.setColor(col);p.setTextSize(size);p.setTextAlign(align);p.setTypeface(bold?android.graphics.Typeface.DEFAULT_BOLD:android.graphics.Typeface.MONOSPACE);c.drawText(s,x,y,p);} 
  @Override protected void onDraw(Canvas c){super.onDraw(c);scale=Math.min(getWidth()/LW,getHeight()/LH);ox=(getWidth()-LW*scale)/2;oy=(getHeight()-LH*scale)/2;c.save();c.translate(ox,oy);c.scale(scale,scale);
    fill(c,Color.rgb(7,11,17),0,0,LW,LH);for(int y=0;y<540;y+=30)fill(c,(y/30)%2==0?Color.rgb(13,20,27):Color.rgb(10,16,23),0,y,LW,y+15);for(int x=0;x<960;x+=64){fill(c,Color.rgb(29,34,38),x,82,x+3,515);fill(c,Color.rgb(5,8,12),x+3,82,x+5,515);} 
    fill(c,Color.rgb(11,14,20),0,0,960,96);line(c,Color.rgb(173,118,43),4,0,94,960,94);text(c,"GATECRAFT ARCADE",36,47,31,Color.rgb(248,211,79),Paint.Align.LEFT,true);text(c,t("Három különálló, nagy képernyős retro játék","Three standalone full-screen retro games","Drei separate Retro-Spiele im Vollbild","Tres juegos retro independientes a pantalla completa","Trois jeux rétro indépendants plein écran","三个独立全屏复古游戏","Tre giochi rétro separati a schermo intero","Três jogos retrô separados em tela cheia","Trzy oddzielne pełnoekranowe gry retro","Drie losse retrospellen op volledig scherm","Trei jocuri retro separate pe ecran complet","Три отдельные полноэкранные ретро-игры"),36,76,14,Color.LTGRAY,Paint.Align.LEFT,false);
    String[] names={"WORKSHOP RUN","HEROES OF CRAFT & GATES","METAL FIGHTER"};String[] subs={t("Platformok • szerszámok • veszélyek • roham","Platforms • tools • hazards • dash","Plattformen • Werkzeuge • Gefahren • Sprint","Plataformas • herramientas • peligros • impulso","Plateformes • outils • dangers • ruée","平台 • 工具 • 危险 • 冲刺","Piattaforme • attrezzi • pericoli • scatto","Plataformas • ferramentas • perigos • arrancada","Platformy • narzędzia • pułapki • zryw","Platforms • gereedschap • gevaren • dash","Platforme • unelte • pericole • avânt","Платформы • инструменты • опасности • рывок"),t("Izometrikus térkép • műhely • taktikai csata","Isometric map • workshop • tactical battle","Isometrische Karte • Werkstatt • Taktikkampf","Mapa isométrico • taller • batalla táctica","Carte isométrique • atelier • bataille tactique","等距地图 • 工坊 • 战术战斗","Mappa isometrica • officina • battaglia tattica","Mapa isométrico • oficina • batalha tática","Mapa izometryczna • warsztat • bitwa taktyczna","Isometrische kaart • werkplaats • tactisch gevecht","Hartă izometrică • atelier • luptă tactică","Изометрическая карта • мастерская • тактический бой"),t("1v1 • ugrás • kombó • védekezés • ív-special","1v1 • jump • combo • block • arc special","1v1 • Sprung • Kombo • Block • Lichtbogen","1v1 • salto • combo • bloqueo • arco","1v1 • saut • combo • garde • arc","1v1 • 跳跃 • 连击 • 防御 • 电弧","1v1 • salto • combo • parata • arco","1v1 • pulo • combo • defesa • arco","1v1 • skok • combo • blok • łuk","1v1 • sprong • combo • blok • boog","1v1 • salt • combo • bloc • arc","1v1 • прыжок • комбо • блок • дуга")};
    int[] cols={Color.rgb(32,128,91),Color.rgb(143,92,34),Color.rgb(157,46,45)};
    for(int i=0;i<3;i++){RectF r=cards[i];boolean u=owner.modeUnlocked(i+1);fill(c,Color.rgb(3,5,8),r.left-5,r.top-5,r.right+5,r.bottom+5);fill(c,u?cols[i]:Color.rgb(48,52,57),r.left,r.top,r.right,r.bottom);fill(c,Color.argb(48,255,255,255),r.left+7,r.top+7,r.right-7,r.top+16);fill(c,Color.argb(90,0,0,0),r.left,r.top,r.left+198,r.bottom);drawPreview(c,i,r.left+98,r.centerY());text(c,names[i],r.left+220,r.top+42,25,Color.WHITE,Paint.Align.LEFT,true);text(c,subs[i],r.left+220,r.top+76,14,Color.rgb(234,232,222),Paint.Align.LEFT,false);if(u){text(c,"▶",r.right-38,r.centerY()+12,36,Color.WHITE,Paint.Align.CENTER,true);text(c,t("INDÍTÁS","PLAY","START","JUGAR","JOUER","开始","GIOCA","JOGAR","GRAJ","SPEEL","JOACĂ","ИГРАТЬ"),r.right-72,r.bottom-15,12,Color.rgb(255,236,166),Paint.Align.RIGHT,true);}else text(c,t("ZÁR","LOCK","SPERRE","BLOQ","VERROU","锁定","BLOCCO","BLOQ","BLOK","SLOT","BLOC","ЗАМОК")+" "+owner.requiredFor(i+1),r.right-28,r.centerY()+7,17,Color.rgb(255,206,94),Paint.Align.RIGHT,true);}
    fill(c,Color.rgb(124,38,38),exit.left,exit.top,exit.right,exit.bottom);stroke(c,Color.rgb(225,210,178),2,exit.left,exit.top,exit.right,exit.bottom);text(c,t("KILÉP","EXIT","ENDE","SALIR","QUITTER","退出","ESCI","SAIR","WYJDŹ","AFSLUITEN","IEȘIRE","ВЫХОД"),exit.centerX(),exit.centerY()+7,17,Color.WHITE,Paint.Align.CENTER,true);
    text(c,t("50 számolás: GRIND & WELD külön végső bónusz","50 calculations: GRIND & WELD remains a separate final bonus","50 Berechnungen: GRIND & WELD bleibt separater Endbonus","50 cálculos: GRIND & WELD sigue como bonus final separado","50 calculs : GRIND & WELD reste un bonus final séparé","50次计算：GRIND & WELD为独立最终奖励","50 calcoli: GRIND & WELD resta bonus finale separato","50 cálculos: GRIND & WELD fica como bônus final separado","50 obliczeń: GRIND & WELD pozostaje osobnym finałowym bonusem","50 berekeningen: GRIND & WELD blijft aparte eindbonus","50 calcule: GRIND & WELD rămâne bonus final separat","50 расчётов: GRIND & WELD остаётся отдельным финальным бонусом"),36,505,13,Color.rgb(177,184,192),Paint.Align.LEFT,false);
    c.restore();}
  private void drawPreview(Canvas c,int mode,float cx,float cy){if(mode==0){fill(c,Color.rgb(30,35,43),cx-82,cy-40,cx+82,cy+40);for(int x=-75;x<80;x+=30)line(c,Color.rgb(77,82,86),3,cx+x,cy-36,cx+x,cy+16);fill(c,Color.rgb(89,91,88),cx-80,cy+14,cx+80,cy+35);SpriteKit.worker(c,p,cx-12,cy+15,.75f,1,1,System.currentTimeMillis()*.001f,false);SpriteKit.icon(c,p,2,cx+48,cy-8,.7f);}else if(mode==1){fill(c,Color.rgb(45,87,48),cx-82,cy-40,cx+82,cy+40);for(int y=-30;y<35;y+=22)for(int x=-65;x<70;x+=38){p.setColor(((x+y)&1)==0?Color.rgb(69,123,62):Color.rgb(58,109,57));c.drawCircle(cx+x,cy+y,16,p);}SpriteKit.worker(c,p,cx,cy+25,.55f,1,0,0,false);SpriteKit.icon(c,p,0,cx+48,cy-15,.55f);}else{fill(c,Color.rgb(73,42,88),cx-82,cy-40,cx+82,cy+40);fill(c,Color.rgb(42,49,56),cx-82,cy+18,cx+82,cy+40);SpriteKit.worker(c,p,cx-38,cy+24,.8f,1,2,0,false);SpriteKit.worker(c,p,cx+45,cy+24,.8f,-1,0,0,true);line(c,Color.rgb(98,199,255),5,cx-8,cy-17,cx+26,cy-25);}}
  @Override public boolean onTouchEvent(MotionEvent e){if(e.getActionMasked()!=MotionEvent.ACTION_DOWN)return true;float x=(e.getX()-ox)/scale,y=(e.getY()-oy)/scale;if(exit.contains(x,y)){owner.requestExitFromView();return true;}for(int i=0;i<3;i++)if(cards[i].contains(x,y)&&owner.modeUnlocked(i+1)){owner.launchMode(i+1);return true;}return true;}
}
