package com.gatecraft.game;

import android.content.Context;
import android.graphics.Canvas;
import android.graphics.Color;
import android.graphics.Paint;
import android.graphics.RectF;
import android.view.MotionEvent;
import android.view.View;

final class GameLauncherV6View extends View {
  private static final float LW=960f,LH=540f;private final GateCraftGame owner;private final Paint p=new Paint();private float scale=1,ox,oy;
  private final RectF[] cards={new RectF(28,118,310,470),new RectF(338,118,620,470),new RectF(648,118,930,470)};private final RectF exit=new RectF(806,18,940,66);
  GameLauncherV6View(Context c,GateCraftGame owner){super(c);this.owner=owner;p.setAntiAlias(false);p.setFilterBitmap(false);setBackgroundColor(Color.BLACK);}
  private String t(String hu,String en,String de,String es,String fr,String zh,String it,String pt,String pl,String nl,String ro,String ru){String[]a={hu,en,de,es,fr,zh,it,pt,pl,nl,ro,ru};return a[Math.max(0,Math.min(11,owner.getLanguage()-1))];}
  private void fill(Canvas c,int col,float l,float tt,float r,float b){p.setStyle(Paint.Style.FILL);p.setColor(col);c.drawRect(l,tt,r,b,p);}private void stroke(Canvas c,int col,float w,float l,float tt,float r,float b){p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(w);p.setColor(col);c.drawRect(l,tt,r,b,p);p.setStyle(Paint.Style.FILL);}private void text(Canvas c,String s,float x,float y,float size,int col,Paint.Align a,boolean bold){p.setStyle(Paint.Style.FILL);p.setColor(col);p.setTextSize(size);p.setTextAlign(a);p.setTypeface(bold?android.graphics.Typeface.DEFAULT_BOLD:android.graphics.Typeface.MONOSPACE);c.drawText(s,x,y,p);}private void line(Canvas c,int col,float w,float x1,float y1,float x2,float y2){p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(w);p.setColor(col);c.drawLine(x1,y1,x2,y2,p);p.setStyle(Paint.Style.FILL);}
  @Override protected void onDraw(Canvas c){super.onDraw(c);scale=Math.min(getWidth()/LW,getHeight()/LH);ox=(getWidth()-LW*scale)/2;oy=(getHeight()-LH*scale)/2;c.save();c.translate(ox,oy);c.scale(scale,scale);fill(c,Color.rgb(6,8,12),0,0,960,540);for(int y=0;y<540;y+=28)fill(c,(y/28)%2==0?Color.rgb(14,18,24):Color.rgb(9,13,18),0,y,960,y+14);fill(c,Color.rgb(12,13,17),0,0,960,98);line(c,Color.rgb(177,123,45),4,0,96,960,96);text(c,"GATECRAFT CLASSIC ARCADE",30,43,30,Color.rgb(248,211,79),Paint.Align.LEFT,true);text(c,t("Három műfaj, klasszikus 90-es/2000-es örökséggel","Three genres built on classic 90s/2000s heritage","Drei Genres mit klassischem 90er/2000er Erbe","Tres géneros con herencia clásica de los 90/2000","Trois genres inspirés de l'héritage 90/2000","三种类型，承袭90/2000年代经典玩法","Tre generi con eredità classica anni 90/2000","Três gêneros com herança clássica dos anos 90/2000","Trzy gatunki z klasycznym dziedzictwem lat 90/2000","Drie genres met klassieke 90s/2000s-erfenis","Trei genuri cu moștenire clasică 90/2000","Три жанра в духе классики 90-х/2000-х"),30,74,14,Color.LTGRAY,Paint.Align.LEFT,false);
    String[] names={"WORKSHOP RUN '96","HEROES OF CRAFT & GATES III","METAL FIGHTER '99"};String[] sub={t("Run & gun • kapuk • ládák • miniboss","Run & gun • gates • crates • miniboss","Run & Gun • Tore • Kisten • Miniboss","Run & gun • puertas • cajas • miniboss","Run & gun • portes • caisses • miniboss","跑跳射击 • 大门 • 箱子 • 小头目","Run & gun • cancelli • casse • miniboss","Run & gun • portões • caixas • miniboss","Run & gun • bramy • skrzynie • miniboss","Run & gun • poorten • kisten • miniboss","Run & gun • porți • lăzi • miniboss","Run & gun • ворота • ящики • мини-босс"),t("Heti növekedés • bányák • toborzás • rivális AI","Weekly growth • mines • recruitment • rival AI","Wochenwachstum • Minen • Rekrutierung • Rivalen-KI","Crecimiento semanal • minas • reclutamiento • IA rival","Croissance hebdo • mines • recrutement • IA rivale","每周成长 • 矿场 • 招募 • 对手AI","Crescita settimanale • miniere • reclutamento • IA rivale","Crescimento semanal • minas • recrutamento • IA rival","Tygodniowy rozwój • kopalnie • rekrutacja • AI rywala","Wekelijkse groei • mijnen • rekrutering • rivaliserende AI","Creștere săptămânală • mine • recrutare • AI rival","Недельный рост • шахты • найм • ИИ соперника"),t("Arcade ladder • dobás • parry • super • 4 ellenfél","Arcade ladder • throw • parry • super • 4 rivals","Arcade-Leiter • Wurf • Parry • Super • 4 Rivalen","Escalera arcade • agarre • parry • super • 4 rivales","Ladder arcade • projection • parry • super • 4 rivaux","街机挑战 • 投技 • 格挡反击 • 超必杀 • 4对手","Ladder arcade • presa • parry • super • 4 rivali","Escada arcade • arremesso • parry • super • 4 rivais","Drabinka arcade • rzut • parry • super • 4 rywali","Arcade ladder • worp • parry • super • 4 rivalen","Scară arcade • aruncare • parry • super • 4 rivali","Аркадная лестница • бросок • парирование • супер • 4 соперника")};int[] cols={Color.rgb(39,122,92),Color.rgb(139,91,37),Color.rgb(151,48,48)};
    for(int i=0;i<3;i++){RectF r=cards[i];boolean u=owner.modeUnlocked(i+1);fill(c,Color.rgb(2,4,7),r.left-5,r.top-5,r.right+5,r.bottom+5);fill(c,u?cols[i]:Color.rgb(52,54,60),r.left,r.top,r.right,r.bottom);fill(c,Color.argb(80,0,0,0),r.left,r.top+180,r.right,r.bottom);stroke(c,Color.rgb(224,199,133),2,r.left,r.top,r.right,r.bottom);preview(c,i,r.centerX(),r.top+108);text(c,names[i],r.centerX(),r.top+225,20,Color.WHITE,Paint.Align.CENTER,true);text(c,sub[i],r.centerX(),r.top+258,11,Color.rgb(236,230,216),Paint.Align.CENTER,false);if(u){fill(c,Color.rgb(18,20,24),r.left+28,r.bottom-72,r.right-28,r.bottom-24);stroke(c,Color.rgb(245,215,132),2,r.left+28,r.bottom-72,r.right-28,r.bottom-24);text(c,t("INDÍTÁS","PLAY","START","JUGAR","JOUER","开始","GIOCA","JOGAR","GRAJ","SPEEL","JOACĂ","ИГРАТЬ"),r.centerX(),r.bottom-40,17,Color.rgb(255,233,164),Paint.Align.CENTER,true);}else{text(c,t("ZÁR","LOCK","SPERRE","BLOQ","VERROU","锁定","BLOCCO","BLOQ","BLOK","SLOT","BLOC","ЗАМОК")+" "+owner.requiredFor(i+1),r.centerX(),r.bottom-42,17,Color.rgb(255,207,96),Paint.Align.CENTER,true);}}
    fill(c,Color.rgb(124,38,38),exit.left,exit.top,exit.right,exit.bottom);stroke(c,Color.rgb(225,210,178),2,exit.left,exit.top,exit.right,exit.bottom);text(c,t("KILÉP","EXIT","ENDE","SALIR","QUITTER","退出","ESCI","SAIR","WYJDŹ","AFSLUITEN","IEȘIRE","ВЫХОД"),exit.centerX(),exit.centerY()+7,17,Color.WHITE,Paint.Align.CENTER,true);text(c,t("GRIND & WELD külön végső ARPG bónusz marad","GRIND & WELD remains the separate final ARPG bonus","GRIND & WELD bleibt separater finaler ARPG-Bonus","GRIND & WELD sigue como bonus ARPG final separado","GRIND & WELD reste le bonus ARPG final séparé","GRIND & WELD仍是独立最终ARPG奖励","GRIND & WELD resta il bonus ARPG finale separato","GRIND & WELD continua como bônus ARPG final separado","GRIND & WELD pozostaje osobnym finałowym bonusem ARPG","GRIND & WELD blijft de aparte finale ARPG-bonus","GRIND & WELD rămâne bonusul ARPG final separat","GRIND & WELD остаётся отдельным финальным ARPG-бонусом"),30,510,13,Color.rgb(175,184,193),Paint.Align.LEFT,false);c.restore();}
  private void preview(Canvas c,int m,float cx,float cy){if(m==0){fill(c,Color.rgb(26,31,39),cx-105,cy-76,cx+105,cy+76);for(int x=-90;x<100;x+=34)line(c,Color.rgb(77,82,86),3,cx+x,cy-66,cx+x,cy+38);fill(c,Color.rgb(89,91,88),cx-105,cy+35,cx+105,cy+70);SpriteKit.worker(c,p,cx-35,cy+38,.95f,1,2,0,false);SpriteKit.worker(c,p,cx+55,cy+38,.88f,-1,1,0,true);SpriteKit.icon(c,p,2,cx+4,cy-22,.75f);}else if(m==1){fill(c,Color.rgb(44,87,48),cx-105,cy-76,cx+105,cy+76);for(int y=-52;y<56;y+=26)for(int x=-82;x<86;x+=44){p.setColor(((x+y)&1)==0?Color.rgb(70,124,63):Color.rgb(57,107,56));c.drawCircle(cx+x,cy+y,18,p);}SpriteKit.worker(c,p,cx-28,cy+45,.68f,1,0,0,false);SpriteKit.worker(c,p,cx+50,cy-10,.62f,-1,0,0,true);SpriteKit.icon(c,p,3,cx+20,cy+30,.65f);}else{fill(c,Color.rgb(73,42,88),cx-105,cy-76,cx+105,cy+76);fill(c,Color.rgb(42,49,56),cx-105,cy+34,cx+105,cy+76);SpriteKit.worker(c,p,cx-48,cy+42,1.05f,1,2,0,false);SpriteKit.worker(c,p,cx+58,cy+42,1.05f,-1,3,0,true);line(c,Color.rgb(98,199,255),6,cx-8,cy-20,cx+35,cy-30);}}
  @Override public boolean onTouchEvent(MotionEvent e){if(e.getActionMasked()!=MotionEvent.ACTION_DOWN)return true;float x=(e.getX()-ox)/scale,y=(e.getY()-oy)/scale;if(exit.contains(x,y)){owner.requestExitFromView();return true;}for(int i=0;i<3;i++)if(cards[i].contains(x,y)&&owner.modeUnlocked(i+1)){owner.launchMode(i+1);return true;}return true;}
}
